- manifests/keplerExporter-serviceMonitor.yaml
- pkg/collector/collector.go
We have a list of metrics that can not be indexed by pod_namespace, pod_name, and command only, including
- pod_energy_total
- pod_energy_current
- pod_cpu_energy_current
- pod_cpu_energy_total
- pod_dram_energy_current
- pod_dram_energy_total
I also see the `command` field may change over time. I am not sure if that matters for users and I may just remove those.
> Organize all metrics separately

- manifests/deployment.yaml
- pkg/collector/collector.go
This PR fix the following issue:
1. Do not create monitoring ns for kepler deployment as Prometheus will also need that namespace.
2. The pod_total_energy was wrong.
> fix the pod_total_energy 0 value issues

- pkg/power/sysfs.go
- pkg/power/sysfs_util.go
**Why we need this PR:**
Before this PR, the logs were showing that the DRAM energy consumption was null.
After this PR, we can see accurate cpu and dram energy consumption:
**What this PR does:**
Investigating and analyzing both the [`rapl-read.c`](https://github.com/deater/uarch-configure/blob/master/rapl-read/rapl-read.c) code and the `sysfs` rapl sub-directory, the dram energy consumption file exist and the core energy consumption file that is missing in the measured system. Each `sysfs` rapl sub-directory has a file called `name` with the rapl event name.
In the old Kepler logic, the rapl `sysfs` event path was defined regarding a sub-folder id:
However, as we saw before, the ID varies. For example, in the old Kepler logic, `intel-rapl:%d:0/` is related to core power consumption, but …
> Update rapl sysfs event detection and measurement

- manifests/openshift/dashboard/00-openshift-monitoring-user-projects.yaml
- manifests/openshift/dashboard/01-grafana-operator.yaml
- manifests/openshift/dashboard/02-grafana-instance.yaml
- manifests/openshift/dashboard/03-grafana-datasource-UPDATETHIS.yaml
- manifests/openshift/dashboard/04-grafana-dashboard.yaml
Manifests for:
- Configuration to enable OCP/OKD native Prometheus for user workloads
- Installing Red Hat Grafana Operator
- Setup Grafana instance in Kepler's `monitoring` namespace
- Template for defining local Prometheus as GrafanaDataSource
> initial baseline for OCP/OKD native prometheus and grafana operator

- manifests/kubernetes/deployment.yaml
- manifests/openshift/kepler/01-kepler-install.yaml
This PR will
1) remove redundant `nodes/metrics` rbac rules.
2) disable the model server as it causes the following error.
```
Traceback (most recent call last):
File "server.py", line 5, in <module>
from kepler_model_trainer import archive_saved_model
File "/kepler_model_trainer.py", line 1, in <module>
import tensorflow as tf
File "/usr/local/lib64/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
from tensorflow.python.tools import module_util as _module_util
File "/usr/local/lib64/python3.8/site-packages/tensorflow/python/__init__.py", line 41, in <module>
from tensorflow.python.eager import context
File "/usr/local/lib64/python3.8/site-packages/tensorflow/python/eager/context.py", line 33, in <module>
from tensorflow.core.framework import function_pb2
File …
```
> Disable the kepler model server error for OSS demo

- grafana-dashboards/Kepler-Exporter-Dashboard-OSS-Demo.json
- manifests/kubernetes/deployment.yaml
- manifests/tests/cpu/random.yaml
This PR adds:
1) a random testing pod for CPU load
2) fix legend and sum_over_time errors to consider the 15-second sampling interval.
3) enable GPU for OSS demo
> Added CPU testing load and update dashboard for legents

- pkg/cgroup/slice_handler.go
- pkg/cgroup/slice_handler_test.go
- pkg/collector/collector.go
- pkg/collector/collector_test.go
- pkg/collector/suite_test.go
This PR is to export cgroup metrics of pods to the prometheus format. 
In addition to that, I refactor the collector struct for properly add desc of each metric to prometheus desc channel. 
Also, I implement the unit test for the collector too.
To run the test independently, go into collector folder and run `../../test-bin/ginkgo`. 
> note: this must be run after ginkgo is installed by `make ginkgo-set`
> add cgroup to collector with refactored code and unit test

- README.md
- dev/README.md
- hack/build-manifest.sh
- hack/cluster-clean.sh
- hack/cluster-deploy.sh
- hack/cluster-sync.sh
When extending Kepler, the developer needs an easy way to build and deploy Kepler in its cluster. 
This PR adds support to:
- build a docker image with custom container registry and tag using environment variables
- push the new image to the container registry
- generate the manifests using the custom image
- clean up the cluster (undeploy kepler)
- deploy kepler to the given cluster
Testing kepler will be as simple as running `make cluster-sync`
This is the typical workflow in other k8s bases systems
> Add support to deploy Kepler in a cluster in development mode

- pkg/collector/collector.go
- pkg/collector/reader.go
- pkg/power/rapl/power.go
- pkg/power/rapl/source/estimate.go
- pkg/power/rapl/source/msr.go
- pkg/power/rapl/source/msr_util.go
- pkg/power/rapl/source/package_energy.go
- pkg/power/rapl/source/sysfs.go
This PR is composed of two commits to
1.  defines PackageEnergy struct to keep RAPL energy per package and add GetPackageEnergy() function in the powerInterface for getting RAPL energy per package.  
2. add two new metrics to collector module. These values can be further used in model training.
- node_package_energy_joule: Current package energy by RAPL in joules
- pod_cpu_cpu_time_us:           Current CPU time per CPU of each Pod
> export package energy and CPU time per CPU core of each pod

- pkg/attacher/bcc_attacher.go
- pkg/cgroup/slice_handler.go
- pkg/collector/collector.go
- pkg/collector/metrics.go
- pkg/collector/metrics_test.go
This PR introduce metric.go in collector module to add flexibility to list available metrics and convert corresponding values from PodEnergy object.
- With this PR, counter metrics are detected by enabled attribute in perfCounter object from attacher module and cgroup metrics are detected by previously-implemented function GetAvailableCgroupMetrics() from cgroup module. 
- The future introduced metrics should implement the conversion in convertUIntCurrAggr() or converFloatCurrAggr().
_notes:_ there are still some hard-code metrics to update such as bytes_read, bytes_write, block_devices.
> add metrics.go to get available metrics dynamically

- pkg/config/config.go
This PR fixes the missing position when getting kernel release version to second decimal number (from x.x to x.xx). 
Additionally, to avoid unnecessary fatal failure when it cannot detect the kernel version from the system info, this PR returns -1 value instead.
_note: the current minimum kernel version check is down to second decimal number (4.18)._
> fix kernel version parsing position

- data/cpu_model.csv
- data/download_intel_cpu_models.sh
1. download_intel_cpu_models.sh
- check whether pup command exists firstly.
- add product web link for Intel processor Ice Lake
2. cpu-model.csv:
- refresh generated by updated script download_intel_cpu_models.sh
Signed-off-by: Lu Ken <ken.lu@intel.com>
> cpu-model: Add Intel Xeon processor "Ice Lake"

- dev/create_k8s_token.sh
- dev/role.yaml
From Kubernetes 1.24, secret will not be create automatically with service account. Thus create_k8s_token.sh would fail due to no secret is created.
Create secret manually to fix the issue.
Signed-off-by: Hao, Ruomeng <ruomeng.hao@intel.com>
> dev: create secret manually

- pkg/collector/collector.go
- pkg/collector/collector_test.go
- pkg/collector/metrics_test.go
- pkg/collector/node_energy.go
- pkg/collector/pod_energy.go
- pkg/collector/reader.go
- pkg/collector/types.go
- pkg/model/estimate.go
- pkg/model/estimate_test.go
**What's included in this PR:**
- define _UInt64StatCollection_ type for collections of any aggregated stat
_previous_: _ContainerUInt64Stat_ keeps collection of containers in a single pod
_this PR_: _UInt64StatCollection_ keeps collection of containers in a pod, package/sensor energy of the node
**objective**: to handle energy aggregated stat in the same way of other aggregated stat such as cgroup
- keep _PrevCurr_ stat when resetting _Curr_ value of _UInt64Stat_ and use if meeting overflow condition
_previous_: `s.Curr = newAggr + (math.MaxUint64 - oldAggr)`
_this PR_: `s.Curr = s.PrevCurr`
**objective**: to avoid uncertainty of maximum number of aggregated value for each stat
**related PR comment:**: https://github.com/sustainable-computing-io/kepler/pull/112#discussion_r957854026
- …
> fix exported metrics, handle energy overflow to use latest valid value

- grafana-dashboards/Kepler-Exporter.json
Kepler-Exporter.json dashboard has been generalized taking OpenShift Carbon USA legacy dashboard as an example. This PR partially addresses #119 issue.
Dashboard is now possible to import by hand and opens up correctly, not throwing any errors. This change doesn't include the URL changes necessary in manifests/openshift/04-grafana-dashboard.yaml.
> Generalize Grafana dashboard

- pkg/collector/collector.go
- pkg/collector/node_energy.go
fix the bug due to random order of energy label map in the node energy stat.
> fix random order of ENERGY_LABELS for node energy stat

- pkg/collector/node_energy.go
- pkg/collector/reader.go
- pkg/power/rapl/source/sysfs.go
- pkg/power/rapl/source/sysfs_util.go
This PR changes filling up the missing core or dram energy from (processed) current value instead of aggregated value to avoid overflow issue.
> fill core/dram curr energy from delta instead of aggregated value

- grafana-dashboards/Kepler-Exporter.json
* Fixes typo in Total pod CPU energy consumption metric query which resulted in missing CPU Total Pod Energy Consumption
* Fixes typo in Total pod DRAM energy consumption metric query which resulted in missing DRAM Total Pod Energy Consumption on graph.
Both issues can be seen on dashboard posted in #118 PR. Now all of the metrics can be observed, as noted on screenshot below.
> Fix dashboard typos for CPU and DRAM metrics on Total Pod Energy Consumption graph 

- dev/README.md
- dev/prepare_dev_env.sh
After local build for keper and run it, there will an error reports that `normalized_cpu_arch.csv` deson't exist:
Here is the message
```
[root@xxx kepler]# ./_output/bin/_/kepler
2022/09/06 00:58:56 InitSliceHandler: &{map[] /sys/fs/cgroup/cpu /sys/fs/cgroup/memory /sys/fs/cgroup/blkio}
no cpu info: open /var/lib/kepler/data/normalized_cpu_arch.csv: no such file or directory
power not supported
```
To resolve this issue, this pull request will:
1. Add a script named `dev/prepare_dev_env.sh` to copy the needed files for local build to the target folder
2. Update readme to remind developer to run this script
> copy files for dev local build

- Makefile
- pkg/attacher/bcc_attacher.go
- pkg/attacher/bcc_attacher_stub.go
- pkg/attacher/bpf_perf.go
- pkg/collector/collector_test.go
- pkg/collector/reader.go
- pkg/pod_lister/byte_order.go
- pkg/pod_lister/resolve_container.go
This PR removes static dependency to bcc library.
With this decoupling, we can make a quick test on collector package without need of bcc installation. 
Furthermore, in some system where bcc library cannot be installed in the host, we can still provide the other stat such as node energy and can provide other approach to export pod-level metrics such as using only kubelet and cgroup.
> make conditional build for bcc

- pkg/collector/collector.go
- pkg/collector/collector_test.go
- pkg/collector/metrics_test.go
This PR set podEnergyLabels after calling AttachBPFAssets by attacher to support the case that `attacher.EnableCPUFreq` is changed to _false_ due to attachment failure.
fix #131
> set pod prometheus label after attachment

- manifests/openshift/kepler/01-kepler-install.yaml
Multi-node OpenShift clusters can be configured to either allow the scheduler to launch user workloads on master (aka control plane) nodes or not. 
If Kepler is expected to be used for monitoring master nodes (and openshift-* namespaces) power usage in both schedulable and unschedulable master scenarioes, the proposed toleration is necessary in DaemonSet. It allows the scheduler to spawn Kepler Exporter pods despite master nodes being tainted as unschedulable for user workloads. It is not enough to label the master nodes with the "sustainable-computing.io/kepler" label.
It is open to discussion whether this is necessary.
> Improvement: Add tolerations to allow Kepler to spawn on unschedulable master nodes

- bpf_assets/perf_event/perf_event.c
- pkg/bpf_assets/perf_event_bindata.go
- pkg/config/config.go
- pkg/pod_lister/resolve_container.go
1. User space PID should take upper 32 bit of bpf_get_current_pid_tgid(). Please refer to https://github.com/iovisor/bcc/blob/master/docs/reference_guide.md#4-bpf_get_current_pid_tgid
2. Update path regex and containerID regex for cgroup v1 env. Note that this has only been tested with cgroup v1 + containerd
Signed-off-by: Hao, Ruomeng <ruomeng.hao@intel.com>
> Fix issue 107 in cgroup v1 environment

- pkg/pod_lister/resolve_container.go
Previous PR #138 updated the logic to extract the container ID from a cgroup path.
Unfortunately, I wrongly revised the PR #138 as it had a problem. With the changes, Kepler stopped collecting the container IDs in my environment....
My system has cgroup v1 and the OS is ubuntu, and after creating a kepler deployment, the cgroup path is as follows:
```
11:blkio:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod481c0ae9_7d40_46dd_b6ca_ba27cb64f87e.slice/docker-28a5e57257f81fcd6d592647dde27e06b53944d58af4fa546ad77a12ce8b41c2.scope
```
Note that the chunk that has `.slice` is actually the pod id and not the container id. The container id is in the chunk that has `.scope`. The previous PR introduced the logic to extract the id from the `.slice` chunk.
Also, in the previous PR, …
> Revert back the logic to extract container id from path

- pkg/power/rapl/source/estimate.go
This PR implements the missing GetPackageEnergy of estimateImpl which will be applied if other rapl source implementation is not available (such as on VM)
> implement GetPackageEnergy for rapl estimateImpl

- pkg/collector/metrics_test.go
This PR adds function clearPlatformDependentAvailability to clear platform-dependent available metrics from each source and make this UT valid for any platform.
Example of potential test failure on the platform that cgroup metrics are available. 
```bash
2022/09/08 21:51:25 Available counter metrics: []
2022/09/08 21:51:25 Available cgroup metrics: [cgroupfs_user_cpu_usage_us cgroupfs_memory_usage_bytes cgroupfs_cpu_usage_us cgroupfs_system_cpu_usage_us]
2022/09/08 21:51:25 Available kubelet metrics: []
Expected
<[]string | len:3, cap:3>: ["cpu_time", "bytes_read", "bytes_writes"]
to equal
<[]string | len:7, cap:10>: [
"cpu_time",
"cgroupfs_user_cpu_usage_us",
"cgroupfs_memory_usage_bytes",
"cgroupfs_cpu_usage_us",
"cgroupfs_system_cpu_usage_us",
"bytes_read",
"bytes_writes",
] …
```
> clear platform-dependent metric before UT

- pkg/cgroup/stat_reader.go
from 
```
/sys/fs/cgroup# cat cpu.stat
usage_usec 8210530646
user_usec 5555530859
system_usec 2654999787
nr_periods 0
nr_throttled 0
throttled_usec 0
```
I think from context it should be user_usec instead of usage_usec, maybe it's a typo?
> usage_usec => user_usec

- pkg/collector/node_energy.go
- pkg/collector/reader.go
- pkg/config/config.go
- pkg/model/estimate.go
- pkg/power/rapl/source/estimate.go
- pkg/power/rapl/source/sysfs.go
We have some logic to calculate missing core energy consumption using rapl pkg and dram energy consumption. However, package energy consumption does not include dram energy....
The official documentation is [Intel® 64 and IA-32 Architectures Software Developer's Manual: Volume 3](https://www.intel.com/content/www/us/en/architecture-and-technology/64-ia-32-architectures-software-developer-system-programming-manual-325384.html). See page 499+ for RAPL details.
Also, consider the image from the paper [RAPL in Action: Experiences in Using RAPL for Power Measurements](https://dl.acm.org/doi/pdf/10.1145/3177754):
- **Package**: The Package domain (PKG) measures the energy consumption of the entire socket. It includes consumption of all cores, integrated graphics and also uncore components (last …
> remove the dram energy from rapl pkg energy calculation

- .github/workflows/unit_test.yml
- Makefile
- automation/presubmit-tests/gofmt.sh
- pkg/collector/metrics_test.go
Add go fmt as a basic test case in CI.
If the code in the submitted PR is not well format, the test will fail and ask the developer to run `make format`.
This is the first step for testing the code quality, as describe in the issue #161
We will add later 
- [go vet](https://medium.com/a-journey-with-go/go-vet-command-is-more-powerful-than-you-think-563e9fdec2f5)
- [revive](https://blog.logrocket.com/linting-go-programs-improving-code-quality/)
> Add gofmt as a prerequisite for PRs in CI

- Makefile
Add all go vet checks as a basic test case in CI.
As part of building a test binary, go test runs go vet on the package and its test source files to identify significant problems. To run all go vet checks, we can use the -vet=all flag. More info [here](https://manpages.debian.org/testing/golang-go/go-test.1.en.html).
This is PR is part of the effort for testing the code quality, as describe in the issue #161
> Update go test to run all go vet checks

- .golangci.yml
- Makefile
- hack/golint.sh
Using linters improves the code quality and readability by highlighting problems before they are executed, and it helps with the standardization of the codebase.
This PR enables golint. But, fixing the issues is out of the scope of this PR and will be done in another PR.
Additionally, this is PR is part of the effort for testing the code quality, as describe in the issue https://github.com/sustainable-computing-io/kepler/issues/161
Signed-off-by: Marcelo Amaral [marcelo.amaral1@ibm.com](mailto:marcelo.amaral1@ibm.com)
> Add support for golint

- Makefile
- cluster-up/README.md
- cluster-up/cluster-down.sh
- cluster-up/cluster-up.sh
- cluster-up/cluster/kind/README.md
- cluster-up/cluster/kind/common.sh
- cluster-up/cluster/kind/manifests/kind.yml
- cluster-up/cluster/kind/manifests/local-registry.yml
- cluster-up/common.sh
- dev/README.md
- hack/build-manifest.sh
- hack/cluster-deploy.sh
- hack/cluster-down.sh
- hack/cluster-sync.sh
- hack/cluster-up.sh
After making changes to a kepler code, you should test it locally and the github should also trigger integration tests.
This PR introduce the code to provision and start containerized Kubernetes clusters in order to test Kepler on different Kubernetes configurations.
Currently, there is only support for creating a k8s cluster using the `kind` tool, but we will add support for other tools later such as `microshift`.
The developer will be able to simply run:
```bash
export CLUSTER_PROVIDER=`kind`
make cluster-up
```
After this PR, we will be able to update the github workflow that runs the integration test.
This PR is related to the PR #157.
> Adding support to easily create local kubernetes cluster for testing purposes

- .github/workflows/golangci-lint.yml
Before merging this PR, we need the PR #168 that adds support for golint with the revive package.
This action will highlight golint issues as the ones described in the issue #169.
This is PR is part of the effort for testing the code quality, as describe in the issue https://github.com/sustainable-computing-io/kepler/issues/161
> Add golint test to CI

- .github/workflows/integration_test.yml
- .github/workflows/unit_test.yml
- cluster-up/cluster/kind/README.md
- cluster-up/cluster/kind/common.sh
This PR updates the way that the integration test creates the local kubernetes cluster by using the scripts introduced in the PR #164.
This PR depends on the PR #164 be merged first.
> update integration test to use cluster up and sync

- grafana-dashboards/Kepler-Exporter.json
- grafana-dashboards/legacy/Kepler-Exporter-Dashboard-openshift.json
- grafana-dashboards/legacy/Kepler-Exporter-Dashboard.json
- hack/cluster-deploy.sh
- manifests/kubernetes/deployment.yaml
- manifests/openshift/kepler/00-kepler-scc.yaml
- manifests/openshift/kepler/01-kepler-install.yaml
This PR changes the kepler namespace from `monitoring` to its own namespace `kepler`.
When undeploying kepler using the `yml` file, it has the namespace definition. So just running `kubectl delete -f ${MANIFESTS_OUT_DIR}` will delete the `monitoring` namespace.
However, the `monitoring` namespace normally has other projects running like the prometheus stack and we shouldn't delete it when undeploying kepler...
Also, allowing kepler to have its own namespace has another advantage:
- Isolation. We don't need to worry about resource name collision.
- Permissions. Namespaces allow the use of Kubernetes RBAC specific to kepler only.
- Performance. The Kubernetes API will have fewer items to search for when performing operations, reducing latency and accelerating overall application …
> Update kepler namespace from monitoring to kepler

- .github/workflows/gofmt.yml
- .github/workflows/unit_test.yml
This PR keeps only the unit tests in the workflow file that describe the unit tests, and move the gofmt test to another file.
> refactor git workflows

- .github/workflows/image-base.yml
- build/Dockerfile.base.s390x
Build the amd64 and s390x base image, used separate Dockerfile.$arch file as it uses different packages to make it easy to maintain.
These base images will be used by kepler. We don't need a s390x builder as we can use the amd64 builder to build s390x images in future.
Signed-off-by: huoqifeng <huoqif@cn.ibm.com>
> s390x: build base image

- .github/workflows/unit_test.yml
- Makefile
resolve https://github.com/sustainable-computing-io/kepler/issues/193
change log:
add commit push condition for main branch.
move test coverage for default unit test.(to avoid test coverage based on specific build tag as bcc)
bug fix for test coverage file missing.
> Fix CI error

- grafana-dashboards/Kepler-Exporter.json
Without this patch, the default datasource is "Grafana" itself. So it requires to fix the datasource for each panel in kepler dashboard. This patch forge to set the data source to "prometheus".
It has been tested on a kubernetes cluster (v1.25.1).
Signed-off-by: Lu Ken <ken.lu@intel.com>
> grafana: Set the default datasource to "prometheus"

- manifests/kubernetes/keplerExporter-serviceMonitor.yaml
1. Move the service monitoring to the namespace of kepler align with deployment
2. Add Role and RoleBinding to allow prometheus monitoring the namespace kepler
This has been tested on a local kubernetes cluster.
Signed-off-by: Lu Ken <ken.lu@intel.com>
> prometheus: Fixes #197 permission issue for service monitoring

- .github/workflows/image-base.yml
- Makefile
- build/Dockerfile.base.arm64
- Cross-platform `kepler_base` image comes from different Dockerfile for different `arch` for maintain purpose. 
- It's a nightmare to maintain all arches in a single `Docekerfile`, so we build arch specific images first and then create a manifest then.
- arm64 base image is just a base, some necessary RPM might be needed in future
- Trigger it when there is a tag generated.
Signed-off-by: huoqifeng <huoqif@cn.ibm.com>
> multi-arch: create kepler_base multi-arch image

- pkg/power/acpi/acpi.go
fix the regression in https://github.com/sustainable-computing-io/kepler/commit/75f60857a022410fb03f6488c6a137527cae785f#diff-01d4e5e0e8a39b2a514a24ebfd7524d6d692272ef2c75a615bd7435f1b097931L177
> acpi power sensordon't continue if the power meter doesn't exist

- .github/workflows/integration_test.yml
- cluster-up/cluster/kind/common.sh
The current integration test tries to deploy the prometheus operator, but it doesn't work because the cluster doesn't have the docker images.
We don't see errors in the test because the test is not verifying if all containers were created successfully....
To deploy the prometheus operator on the kind cluster, we need to load the images into the cluster.
This PR adds that logic and wait all containers to be ready.
Also, I applied logic to deploy the minimum version of the prometheus operator to speed up the test execution.
After this PR anyone can create a kind cluster with prometheus using:
```
CLUSTER_PROVIDER="kind" PROMETHEUS_ENABLE="true" cluster-up
```
I don't think pushed a new image to quay should be part of an integration test.
We need to fix this in another PR.
Signed-off-by: …
> Add support to deploy prometheus operator via make cluster-up

- cmd/exporter.go
- go.mod
- manifests/kubernetes/deployment.yaml
- pkg/attacher/bcc_attacher.go
- pkg/bpfassets/perf_event_bindata.go
- pkg/cgroup/slice_handler.go
- pkg/collector/metrics.go
- pkg/collector/node_energy.go
- pkg/collector/pod_energy.go
- pkg/collector/reader.go
- pkg/collector/types.go
- pkg/config/config.go
- pkg/model/estimate.go
- pkg/model/model.go
- pkg/podlister/resolve_container.go
- pkg/power/acpi/acpi.go
- pkg/power/gpu/gpu_nvml.go
- pkg/power/rapl/power.go
- pkg/power/rapl/source/estimate.go
- pkg/power/rapl/source/sysfs.go
- pkg/power/rapl/source/sysfs_util.go
There are a lot of prints currently in the code generating a lot of log data.
To fix this, we must use a different log verbosity.
Also, as indicated in #212, we should standardize the use of fmt and log prints to just one way.
This PR is moving all prints from fmt or log to klog.
Klog was developed by the Kubernetes community and has some advantages over glog as described [here](https://pkg.go.dev/k8s.io/klog).
Signed by: Marcelo Amaral <marcelo.amaral1@ibm.com>
> Update log lib to klog to enable log verbosity support

- pkg/collector/node_energy.go
Power consumption of other host components is related to node cooling system, power supply, bus connection, etc, except RAPL (CPU Package and DRAM) and GPU power consumption.
Signed by: Marcelo Amaral <marcelo.amaral1@ibm.com>
> Remove the dram energy from the host other components energy consumption

- pkg/collector/collector.go
- pkg/collector/collector_test.go
- pkg/collector/node_energy.go
- pkg/collector/reader.go
- pkg/power/rapl/power.go
- pkg/power/rapl/source/dummy.go
- pkg/power/rapl/source/estimate.go
- pkg/power/rapl/source/msr.go
- pkg/power/rapl/source/msr_util.go
- pkg/power/rapl/source/package_energy.go
- pkg/power/rapl/source/sysfs.go
The `PackageEnergy` structure and functions actually return not just the package energy, but all the energy of RAPL components such as core and dram....
To make this clearer, I'm renaming PackageEnergy to RAPLEnergy
> Refactor the PackageEnergy to RAPLEnergy

- pkg/collector/reader.go
- pkg/podlister/resolve_container.go
- pkg/podlister/suite_test.go
This PR is to add initial inactive pods (e.g. nginx) at the beginning of collector package relating to this comment of the previous PR https://github.com/sustainable-computing-io/kepler/pull/268#issuecomment-1263694217.
This is supposed to solve the issue by also passing the result of podlister init function to the collector package and the podEnergy.  
> init podEnergy of inactive pods (e.g., nginx)

- cluster-up/cluster/kind/common.sh
- cluster-up/cluster/kind/manifests/kind.yml
On my Kind cluster, some pod names weren't being resolved
Actually the errors were related to no read access to `/proc/pid`
This is because when we create a `kind` cluster, the host directory `/proc` is not mounted in the `kind` worker node container
We mount the host directory `/proc` in the kind container as `/proc-host`
Unfortunately, we can't use the same directory name `/proc` -> `/proc`
So since the host proc directory has a different name, we also updated the kepler manifest to mount the correct directory
Signed by: Marcelo Amaral <marcelo.amaral1@ibm.com>
> mount host /proc in the kind cluster to resolve pod name

- manifests/openshift/dashboard/03-grafana-datasource-UPDATETHIS.yaml
resolves https://github.com/sustainable-computing-io/kepler/issues/262
Hardcodes the name of the GrafanaDatasource to `prometheus` rather than `Prometheus`. 
The OpenShift manifests have been broken since https://github.com/sustainable-computing-io/kepler/pull/201 merged, since GrafanaDataSource names are case-sensitive. This quickly gets things back to working.
> Prometheus->prometheus to fix grafana dashboard

- .github/workflows/integration_test.yml
- cmd/exporter.go
- pkg/attacher/bcc_attacher.go
Kepler should work in the case that it could not attach a bpf program. We have the logic for this.
However, there are sometimes that it causes a panic and then terminates the program.
The PR #275 having this problem where the VM does not have the `Module kheaders`, details are [here](https://github.com/sustainable-computing-io/kepler/actions/runs/3201921603/jobs/5230372207#step:8:13).
This PR fix the issue #282
Golang [recover](https://gobyexample.com/recover) function make it possible to recover from a panic.
Therefore, we use this when attaching the bpf program and instead of terminate the program we just log the error.
> Add panic handling when attaching the bpf program to do not termine kepler

- cmd/exporter.go
- pkg/attacher/bcc_attacher.go
- pkg/collector/metrics.go
- pkg/collector/metrics_test.go
- pkg/config/config.go
related to #258
fix 2 things
1) the exposure of hardware counter is able to be configured
2) klog initialized in main, so all global var init info including settings are not printed correctly, this PR also fixed that
> allow expose metrics with options

- pkg/collector/reader.go
- pkg/podlister/resolve_container.go
Reverts sustainable-computing-io/kepler#288
The PR #287 introduces the concept of use containerID, so that collecting the podID will not be necessary
Signed-off-by: Marcelo Amaral [marcelo.amaral1@ibm.com](mailto:marcelo.amaral1@ibm.com)
> Revert "user podID instead of podName to avoid duplicate"

- manifests/kubernetes/deployment.yaml
Currently kepler exporter cannot get data successfully on VM node. With this PR change, kepler exporter will not deploy on VM nodes. Only bare metal nodes will be scheduled for kepler deployment.
Signed-off-by: Hao, Ruomeng <ruomeng.hao@intel.com>
> Exclude VM node when deploy kepler exporter

- pkg/attacher/bcc_attacher.go
- pkg/cgroup/stat_reader.go
- pkg/collector/metrics.go
- pkg/config/config.go
- pkg/config/types.go
- pkg/podlister/kubelet_pod_lister.go
This PR add a function `getConfig` to set configuration values from ConfigMap file or environment variable.
Working in a similar way to this python code in kepler-model-server.
```py
def getConfig(key, default):
file = os.path.join(CONFIG_PATH, key)
if os.path.exists(file):
with open(file, "r") as f:
return f.read()
return os.getenv(key, default)
```
> set config values from configmap or environment vars

- .github/workflows/integration_test.yml
- e2e/e2e_suite_test.go
- e2e/healthcheck_test.go
- vendor/github.com/onsi/gomega/gbytes/buffer.go
- vendor/github.com/onsi/gomega/gbytes/io_wrappers.go
- vendor/github.com/onsi/gomega/gbytes/say_matcher.go
- vendor/github.com/onsi/gomega/gexec/build.go
- vendor/github.com/onsi/gomega/gexec/exit_matcher.go
- vendor/github.com/onsi/gomega/gexec/prefixed_writer.go
- vendor/github.com/onsi/gomega/gexec/session.go
- vendor/modules.txt
Details for this PR
e2e folder with end to end testing, will run with two models, base on environment kepler_address.
build kepler during test process and run it targets on local.
run test case targets on cluster after cluster port forwarding.
> impl for integration test

- manifests/openshift/cluster-prereqs/50-master-cgroupv2.yaml
- manifests/openshift/cluster-prereqs/50-worker-cgroupv2.yaml
- manifests/openshift/cluster-prereqs/51-master-kernel-devel.yaml
- manifests/openshift/cluster-prereqs/51-worker-kernel-devel.yaml
- manifests/openshift/cluster-prereqs/kustomization.yaml
From what I understand (@rootfs please correct me) the CGroupsv2 are no longer required to successfully run Kepler. On the other hand, kernel-devel packages seem to be necessary.
Since kernel-devel is necessary and cgroupsv2 aren't, my proposition is to split the manifests into kernel-devel and cgroupv2 added separately so it is possible to install kernel-devel via MachineConfigs separately. I don't have a cluster suitable to verify whether the kustomization.yaml works correctly right now, so it would be good to test it.
@williamcaban @sallyom WDYT? We could somehow make it optional in the OpenShift deploymen scripts to install CGroupsv2 or not, but I don't have time budget to work this out right now.
@sustainable-computing-io/kepler-deployment
> Split OpenShift machineconfigs into separate kernel-devel and cgroupv2

- e2e/healthcheck_test.go
The PR #225 is failing the integration test for mac environment
However, currently the test is not reporting the command execution output when it fails....
When using Ginkgo it can be convenient to direct output to the [GinkgoWriter](https://pkg.go.dev/github.com/onsi/gomega/gexec#Start), then the command will log output when running tests in verbose mode, or when a test fails.
> Add GinkgoWriter in the e2e test to see the kepler execution command output

- pkg/collector/reader.go
The PR #268 introduced the logic to remove from the cache the pods that were deleted.
However, it is removing the system process since it does not find a "pod alive".
So, this PR verifies if the pod is the system-process and does not delete it...
> Do not remove system-process from the cache

- pkg/model/pod_power.go
This PR handles an issue https://github.com/sustainable-computing-io/kepler/issues/308#issuecomment-1285159101 when the pod ratio is not applicable and also the model is not enabled (which is undesirable case in https://github.com/sustainable-computing-io/kepler/discussions/266#discussioncomment-3794406). 
The GetPodPowers  function will return zero values for all pods.
https://github.com/sustainable-computing-io/kepler/blob/ba30dc29bbb622e6e6aa38433f69400cf52e7236/pkg/model/pod_power.go#L53
> Return zeros for model disabled case

- pkg/collector/metrics.go
The model server is not enabled by default as it should be used mainly when we cannot collect RAPL metrics.
So even though the model server is disabled we are trying to connect to it during boot time
This PR updates to not configure the model server if not enabled and fix issue #308
Signed by: Marcelo Amaral <marcelo.amaral1@ibm.com>
> Do not configure the model server if it is not enabled

- README.md
- cluster-up/cluster-up.sh
- cluster-up/cluster/kind/common.sh
- hack/build-manifest.sh
- manifests/README.md
- manifests/kubernetes/deployment.yaml
I used following to fix #318 
```
CLUSTER_PROVIDER="kind" make cluster-up
CLUSTER_PROVIDER="kind" make cluster-sync
I can see this 
NAMESPACE            NAME                                         READY   STATUS    RESTARTS   AGE
kepler               kepler-exporter-g7qd8                        1/1     Running   0          2m55s
kube-system          coredns-565d847f94-fjg2t                     1/1     Running   0          5m12s
kube-system          coredns-565d847f94-llwwh                     1/1     Running   0          5m12s
kube-system          etcd-kind-control-plane                      1/1     Running   0          5m31s
kube-system          kindnet-jj5gf                                1/1     Running   0          5m12s
kube-system          kube-apiserver-kind-control-plane …
```
> fix can't make cluster-up/sync

- .github/workflows/commitMsg.yml
- Developer.md
this pr use https://github.com/GsActions/commit-message-checker with regex as implementation.
> CI: enable commit msg check

- .github/workflows/integration_test.yml
- cluster-up/README.md
- dev/README.md
- hack/build-manifest.sh
- hack/cluster-deploy.sh
in order to make cluster-sync happy, modified some make build-manifest  in previous PR
but this makes the image used for general deployment (not CI) using CI image (we sed it to devel )
and it lead to image not found issue
with this PR, check whether it's CI, if it's , sed the iamge
if it's not ,keep using latest image
> bug: Fix build manifest

- pkg/model/pod_power.go
- pkg/model/pod_power_test.go
In some edge case, for example BCC lib not found there will be some array out of bounds happens.
With this pr, makes the array inited with make function to avoid panic.
> Fix: to make pod_power.go logic robust

- Makefile
- cmd/exporter.go
- pkg/version/version.go
output
```
I1028 02:15:11.663915       1 exporter.go:74] Kepler running on version: v0.3-71-gbce84ee-dirty
```
> Add version output

- cmd/exporter.go
- pkg/cgroup/slice_handler.go
- pkg/collector/metric/stats.go
- pkg/collector/metric/utils.go
with this change, we can print those important info at beginning
```
I1104 11:32:22.132853       1 slice_handler.go:120] InitSliceHandler: &{map[] /sys/fs/cgroup/cpu /sys/fs/cgroup/memory /sys/fs/cgroup/blkio}
I1104 11:32:22.132925       1 bcc_attacher.go:143] hardeware counter metr true
I1104 11:32:22.192933       1 exporter.go:86] Initializing the Model Server
I1104 11:32:22.192968       1 bcc_attacher.go:143] hardeware counter metr true
I1104 11:32:22.192979       1 utils.go:42] Available counter metrics: [cpu_cycles cpu_instr cache_miss]
I1104 11:32:22.192989       1 utils.go:43] Available cgroup metrics from cgroup: []
I1104 11:32:22.192999       1 utils.go:44] Available cgroup metrics from kubelet: [container_cpu_usage_seconds_total container_memory_working_set_bytes]
I1104 …
```
> Use function to init instead of global variable

- pkg/collector/metric/container_metric.go
fix #362 
output looks like :(20180 below only occur once)
```
I1107 02:48:35.842949       1 metric_collector.go:127] energy from pod (1 processes): name: prometheus-k8s-0 namespace: monitoring
cgrouppid: 0 pid: [20180] comm: prometheus
ePkg (mJ): 0 (0) (eCore: 0 (0) eDram: 0 (0) eUncore: 0 (0)) eGPU (mJ): 0 (0) eOther (mJ): 0 (0)
eDyn (mJ): 0 (0)
avgFreq: 0.00
CPUTime:  4008 (1358979)
counters: map[cache_miss:0 (0) cpu_cycles:0 (0) cpu_instr:0 (0)]
cgroupfs: map[]
kubelets: map[container_cpu_usage_seconds_total:0 (14226) container_memory_working_set_bytes:65536 (1450950656)]
I1107 02:48:35.842969       1 metric_collector.go:127] energy from pod (1 processes): name: counter namespace: n1
cgrouppid: 0 pid: [24414 2356896 2356900 2356966 2357079 2357155 2357223 2357295 2357374 2357439 …
```
> fix: avoid put duplicate PID into array

- pkg/collector/metric/container_metric_test.go
- pkg/collector/metric/node_metric_test.go
- pkg/collector/metric/suite_test.go
add test coverage. Note some functions are not yet fully implemented, the stub tests are to be filled once they are properly implemented.
> unit test: test pod and node collector metrics

- pkg/model/estimator/local/lr.go
This PR is to fix this issue https://github.com/sustainable-computing-io/kepler/issues/389 by checking weight value instead of error and report no config when no error but no weight available.
> fix no config case at model init

- pkg/cgroup/resolve_container.go
per profiling stack in #381, the pod cache update causes the latency. As previously in [release 0.3](https://github.com/sustainable-computing-io/kepler/blob/release-0.3/pkg/podlister/resolve_container.go#L125), when the pod is not found, the system process name is used in the cache.
> pod cache: cache system process

- pkg/power/components/source/dummy.go
this should activate ML based estimator and fix the 0 counter issue on VM
cc @jichenjc @sallyom
> power: switch to model based estimator when the RAPL interface is not available

- cmd/exporter.go
to debug test failures or other runtime issues, we need to have the panic stack
I used this to debug #397 
```console
% go test ./e2e/... --race --bench=. -cover --count=1 --vet=all -v
=== RUN   TestE2eTest
Running Suite: E2eTest Suite - /Users/hchen/go/src/github.com/sustainable-computing-io/kepler/e2e
=================================================================================================
Random Seed: 1668628355
Will run 3 of 3 specs
keplerSession sdtErr
keplerSession sdtErr I1116 14:52:39.443328    5553 exporter.go:150] Kepler running on version:
I1116 14:52:39.443436    5553 config.go:89] using gCgroup ID in the BPF program: true
I1116 14:52:39.443497    5553 config.go:90] kernel version: 22.1
I1116 14:52:39.443544    5553 exporter.go:159] Initializing the Model Server
I1116 …
```
> cmd: don't silently exit, when there is a panic,print the panic stack

- grafana-dashboards/Kepler-Exporter.json
- grafana-dashboards/README.md
**Why this PR is needed?**
PR #287 will update Prometheus metrics and affect the current Grafana dashboard. Where the new metrics will report energy per container and have more meaningful names. More details are written in issue #286.
Currently, it is difficult to understand all the queries in the existing Grafana dashboard. There are some constant values ​​that are not obvious and some queries that are wrong. For example:
The `sum_over_time(pod_curr_energy_in_core_millijoule{pod_namespace=\"$namespace\", pod_name=\"$pod\"}[24h])*15/3/3600000000` metric:
`sum_over_time` sum the metric within the timeframe (the value in the square brackets) by getting a cumulative number from the gauge. The problem here is the granularity, we know the gauge is reported every 3s. So the query will not sum …
> Update Grafana dashboards with the new container metrics

- .github/workflows/unit_test.yml
use tar files at https://github.com/sustainable-computing-io/kepler-ci-artifacts/releases/tag/v0.25.0 in CI process to accelerate CI processing instead of build from source.
> CI: use bcc tar files

- pkg/cgroup/resolve_container.go
The PR #383 fixed the problem of not adding the system containerID to the cache.
However, it removed the logic  of using common name `system_process` to aggregate all the system process resource utilization. Without this logic, we will have the system processes resource utilization divided in different "container" instances because of using different containerIDs.
> Replace the containerID of system process with a common name for aggregation

- hack/build-manifest.sh
- manifests/config/base/patch/patch-model-server-kepler-config.yaml
- manifests/config/exporter/exporter.yaml
- manifests/config/model-server/kustomizeconfig.yaml
- manifests/config/model-server/model-server.yaml
- pkg/config/config.go
- pkg/model/estimator/local/lr.go
This PR fixed the model-server integration issue mentioned in https://github.com/sustainable-computing-io/kepler/issues/463.
significant fix points:
- kepler config map key-value items that are related to kepler-model-server endpoint
- dnsPolicy: ClusterFirstWithHostNet
- port name in model-server manifest
- change from else if to if to try getting weight from URL if from model server is failed
Note: the corresponding PR on kepler-model-server https://github.com/sustainable-computing-io/kepler-model-server/pull/62 is also needed to be reviewed and merged.
> Fix model-server configmap and kepler dnsPolicy

- pkg/collector/metric/container_metric.go
actually we are reporting container, not pod
related to https://github.com/sustainable-computing-io/kepler/issues/422
> logs: enhance pod/container logs

- hack/build-manifest.sh
- manifests/README.md
- manifests/config/base/kustomization.yaml
- manifests/config/base/patch/patch-debug.yaml
- manifests/config/exporter/exporter.yaml
- manifests/config/exporter/kustomization.yaml
- manifests/config/exporter/kustomizeconfig.yaml
- manifests/config/exporter/patch/patch-estimator-sidecar.yaml
According to https://github.com/sustainable-computing-io/kepler/issues/466, this PR introduces a new option for simple modification of kepler log in manifest building.
> add DEBUG_DEPLOY OPT in manifest-build

- build/Dockerfile
- build/Dockerfile.base
Per [compatibility matrix](https://docs.nvidia.com/deploy/cuda-compatibility/index.html), 11.8 supports most of the up to date GPU driver.
The latest cuda is 12.0, but the base image is not [there](https://hub.docker.com/r/nvidia/cuda/tags?page=1) yet
> image: use cuda image to support gpu

- pkg/collector/metric/utils.go
- pkg/model/estimator/local/ratio.go
The node total GPU usage is always 0, and thus forcing GPU energy evenly attributed on all Pods. Since GPU process utilization already accounts GPU resource usage, this PR uses GPU utilization, that is already set in the container metrics, to account GPU energy ratio.
> gpu power: add GPU features

- Makefile
The `grep` in the scape detect command is not working and all analysis are being reported, including the `does not scape` cases (where it means there is no problem).
The results are on stderr and we need to merge stderr with stdout.
> Update the scape detect command

- pkg/collector/metric/node_metric.go
- pkg/power/acpi/acpi.go
My test environment doesn't have the power_average hwmon file, but it does have the acpi node power metric.
This PR finds the original power_average acpi file when hwmon is not available.
By the way, even though I calibrated my system, hwmon still didn't report the file.
After this PR, I can see the node platform energy consumption.
> Add support to find acpi sensor power without hwmon

- pkg/bpfassets/perf_event_bindata.go
- pkg/power/components/power.go
estimate need files 
"/var/lib/kepler/data/normalized_cpu_arch.csv"   ==> from docker file 
"/var/lib/kepler/data/power_data.csv" ==> from docker file 
"/proc/meminfo" ==> host level, same to other /proc usage in kepler
> fix: switch from dummy to estimated method

- pkg/model/container_power_test.go
- pkg/model/model_test.go
- pkg/model/utils.go
This PR relates to model update corresponding to Kepler 0.4's new collection and exported power unit.
The updated modes were trained offline and uploaded in [kepler-model-server PR#64]( https://github.com/sustainable-computing-io/kepler-model-server/pull/64). 
> change model output from joule to millijoule

- build/Dockerfile.base.arm64
- data/normalized_cpu_arch.csv
- pkg/power/components/power.go
- pkg/power/components/source/apm_xgene_sysfs.go
This is based on the [Ampere wiki](https://github.com/AmpereComputing/ampere-lts-kernel/wiki/hwmon-drivers). Currently the xgene hwmon driver is used. There is no DIMM power reading in this module. 
The [altra hwmon](https://github.com/torvalds/linux/commits/master/drivers/hwmon/smpro-hwmon.c) is only recently merged to kernel source. It exposes DIMM and CPU power readings
> arm64: support Ampere xgene hwmon based power source

- pkg/collector/container_accelerator_collector.go
- pkg/collector/container_cgroup_collector.go
- pkg/collector/container_energy_collector.go
- pkg/collector/container_hc_collector.go
- pkg/collector/metric/container_metric.go
- pkg/collector/metric/container_metric_test.go
- pkg/collector/metric/node_metric.go
- pkg/collector/metric/node_metric_test.go
- pkg/collector/metric/stats.go
- pkg/collector/metric/utils.go
- pkg/collector/metric_collector.go
- pkg/collector/metric_collector_test.go
- pkg/collector/node_energy_collector.go
- pkg/collector/prometheus_collector.go
- pkg/collector/prometheus_collector_test.go
- pkg/model/container_power.go
- pkg/model/container_power_test.go
- pkg/model/estimator/local/ratio.go
- pkg/model/estimator/local/ratio_test.go
- pkg/model/model_test.go
- pkg/model/node_component_power.go
- pkg/model/node_total_power.go
- pkg/model/utils.go
Measuring idle power consumption is important for getting an accurate picture of overall energy usage. 
It's important to measure the idle and dynamic energy separately so that the energy consumption of resource-intensive processes can be evaluated fairly. For example, It's not fair to assign all idle energy to a process just considering the resource utilization since the idle power does not vary with the utilization.
Therefore, this PR adds the support of Idle and Dynamic energy calculation for a container.
The Idle energy is calculated by using the minimal observed energy. In my experiments, few seconds are enough to get the idle state.
Currently the model server only calculates the dynamic energy, so that the overall metrics will more transparent.
For the prometheus metrics, this PR …
> Add support of Idle and Dynamic energy calculation

- .gitignore
- CONTRIBUTING.md
- pkg/collector/metric/node_metric.go
- pkg/model/estimator/local/benchmark_test.go
- pkg/model/estimator/local/ratio.go
- pkg/model/estimator/local/ratio_test.go
add bench mark testing at code level for function UpdateContainerEnergyByRatioPowerModel
during implementation found we can do refactor for some values and functions to avoid calculate those in k-v loop to save cpu time.
> Test: Add benchmark testing and refactor

- build/Dockerfile.base
- data/normalized_cpu_arch.csv
- pkg/collector/metric/node_metric.go
- pkg/collector/metric/utils.go
- pkg/power/components/source/estimate.go
fix #522 
1. Use cpuid instead of archspec to retrieve correct CPUArchitecture information. 
2. Add Sapphire Rapids cpu model.
Signed-off-by: Zhou,Lei <lei.zhou@intel.com>
> Update the approach of checking the CPUArchitecture

- bpfassets/perf_event/perf_event.c
- pkg/bpfassets/attacher/attacher_types.go
- pkg/bpfassets/attacher/bcc_attacher.go
- pkg/bpfassets/attacher/bcc_attacher_stub.go
- pkg/bpfassets/perf_event_bindata.go
- pkg/collector/container_hc_collector.go
- pkg/collector/metric/container_metric.go
- pkg/collector/metric/stats.go
- pkg/collector/metric/utils.go
- pkg/collector/metric/utils_test.go
- pkg/collector/metric_collector_test.go
- pkg/collector/prometheus_collector.go
- pkg/config/config.go
- pkg/config/types.go
- pkg/model/container_power_test.go
fix #501
For environments that don't have containerized workloads (#511), the irq counters are used for ML training and estimation.
> ebpf: add soft irq counters

- bpfassets/perf_event/perf_event.c
- pkg/bpfassets/perf_event_bindata.go
> fix: avoid warnings about marco redefine

- manifests/config/exporter/exporter.yaml
fixes #527
related:  #71 
On Openshift port 9102 is already used on teh control plane by the OVN Kubernetes CNI. Attempting to reuse it caused the kepelr-exporter pod to get stuck in 'pending'. This commit stops kepler-export requiring the port and so allows it to start
> Turn off hostNetwork and hostPort to prevent port conflicts

- manifests/config/dashboard/00-servicemonitoring-kepler.yaml
- manifests/config/dashboard/README.md
- manifests/config/dashboard/deploy-grafana.sh
After testing the deploy-grafana.sh script on my openshift 4.12 single node cluster, it needs the following updates to run correctly:
This commit fixes three issues in the grafana installation
1) it updates the paths to reflect the new project filesystem layout introduced with PR #449
2) fix the ServiceMonitor port to point to the kepler service port name rather than the service name
3) update the README to reflect the script should be run in the top level of the repo
(due to its prepending of `pwd` to the paths)
> update grafana installation script and yaml files

- pkg/collector/container_accelerator_collector.go
- pkg/collector/container_hc_collector.go
- pkg/collector/metric/container_metric.go
- pkg/collector/metric/container_metric_test.go
- pkg/collector/metric/process_metric.go
- pkg/collector/metric_collector.go
- pkg/collector/metric_collector_test.go
- pkg/collector/process_energy_collector.go
- pkg/collector/prometheus_collector.go
- pkg/collector/prometheus_collector_test.go
- pkg/collector/prometheus_process_collector.go
- pkg/collector/utils.go
- pkg/config/config.go
- pkg/manager/manager.go
- pkg/model/container_power.go
- pkg/model/estimator/local/ratio.go
- pkg/model/estimator/local/ratio_process.go
- pkg/model/process_power.go
- pkg/model/utils.go
fix #512 
In Kepler, all processes that don't have container IDs are classified as `system process` container. So we can use this special container to calculate process based energy.
In this PR, those processes that do not have container IDs are allocated into `kepler_process` metrics. These processes' aggregate energy consumption is based on `system process` container.
> collector: add kepler_process metrics

- pkg/cgroup/slice_handler.go
- pkg/cgroup/stat_reader.go
- pkg/collector/metric/stats.go
- pkg/collector/metric_collector_test.go
- pkg/collector/prometheus_collector.go
- pkg/collector/prometheus_collector_test.go
- pkg/config/config.go
Regarding the issue https://github.com/sustainable-computing-io/kepler/issues/495, this PR added cgroups metrics to prometheus collector. 
Also, this PR updates exported naming of some existing metrics to the same format and add config to enable/disable the exporting. 
```
kepler_container_bpf_block_irq_total{container_name="containerA",container_namespace="test",pod_name="podA"} 0
kepler_container_bpf_block_irq_total{container_name="containerB",container_namespace="test",pod_name="podB"} 0
kepler_container_bpf_cpu_time_us_total{container_name="containerA",container_namespace="test",pod_name="podA"} 0
kepler_container_bpf_cpu_time_us_total{container_name="containerB",container_namespace="test",pod_name="podB"} 0
kepler_container_bpf_net_rx_irq_total{container_name="containerA",container_na …
```
> Export container's usage metrics separately (kepler_container_<metric source>_<metric name>_total)

- data/cpu_model.csv
- data/download_intel_cpu_models.sh
- data/normalized_cpu_arch.csv
1. download_intel_cpu_models.sh:
Add product web link for Intel processor Sapphire Rapids(Xeon 4th SP) and Sapphire Rapids HBM(Xeon Max series)
2. cpu-model.csv:
Refresh generated by updated script download_intel_cpu_models.sh
3. normalized_cpu_arch.csv
Add some missing architecture/microarchitecture names which may appear in cpuid output "uarch" section to avoid the unknown case.
Signed-off-by: Jie Ren <jie.ren@intel.com>
> Update Intel CPU models and architectures

- pkg/model/model.go
To use non-ratio models such as BPFCounterOnly for Kepler process metrics, the process estimator needs to be initiated.
> process: init process estimator so as to use other models

- pkg/config/config.go
- pkg/config/config_test.go
currently every config key has its own config file. This PR is to use yaml for all config keys.
This is tested with this config file `/etc/kepler/kepler.config`:
```
ENABLE_PROCESS_METRICS: true
MODEL_CONFIG: |
PROCESS_COMPONENTS_INIT_URL=https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/DynComponentModelWeight/BPFOnly/ScikitMixed
/ScikitMixed.json
```
> config: parse config yaml

- pkg/collector/container_hc_collector.go
- pkg/collector/metric/node_metric.go
- pkg/collector/metric/utils.go
Regarding https://github.com/sustainable-computing-io/kepler/issues/570 (specifically the idea in https://github.com/sustainable-computing-io/kepler/issues/570#issuecomment-1484535723),
**work included in this PR:**
- add function to getCPUPackageMap mapping from CPU ID to Package ID 
- refactor updateBPFMetrics function to prevent potential complexity test failed
**undo work (postponed to other PR):**
- expose pid_time BPFHash to ProcessCPUTimestamp Table in BpfModuleTables 
- reset the table together with main table (c.bpfHCMeter.Table) 
- readProcessCPUTimestamp and assign to c.ContainersMetrics/c.ProcessMetrics CPUIDs as a count of processes (pids) that use that CPU of considering container (for process case will be always 1)
- export CPUIDs to container metric …
> add process_count metric for mapping container to CPU/Package

- pkg/cgroup/cgroup_interface.go
- pkg/cgroup/cgroup_stats_darwin.go
- pkg/cgroup/cgroup_stats_linux.go
- pkg/collector/container_cgroup_collector.go
- pkg/collector/metric/container_metric.go
- pkg/utils/util_darwin.go
There is a bug in the current code that collects cgroup metrics.
We are calling the stat function only once, so that we do not update the cgroup metrics and are only using old values.
This PR fix this.
> Fix cgroup stat collector and build tags

- pkg/cgroup/cgroup_stats_linux.go
- pkg/collector/container_cgroup_collector.go
- pkg/collector/metric/container_metric.go
If the cgroup metrics of a container does not exist, it means that the container was deleted so that we can remove it from the metrics map.
This PR also removes some leftover debug messages.
> Delete metrics of deleted container

- pkg/collector/container_accelerator_collector.go
- pkg/power/accelerator/gpu.go
- pkg/power/accelerator/power.go
- pkg/power/accelerator/source/gpu_nvml.go
According to issue #610, null pointer access can occur while collecting GPU metrics.
This PR fixes the null pointer error and also includes an attempt to re-initialize the GPU driver in case it is no longer available.
This PR also fix the problem that the GPU error message was nil.
> Fix null pointer issue in gpu metrics

- pkg/cgroup/cgroup_stats_linux.go
Fix #636
The cgroup v1 stat had `IgnoreNotExist`, but if the cgroup does not exist if returns an empty structure, which leads to segmentation fault.
> Update cgroup v1 stat error handling

- pkg/collector/container_cgroup_collector.go
printing excess logs add quite some overhead
> log: reduce container cgroup collector verbosity

- pkg/collector/metric/node_metric.go
- pkg/power/accelerator/gpu.go
This PR fixes two issue: 
-  currently with gpu successfully init'ed, the errLib var is not reset, so the output message is confusing.
```console
I0424 17:44:39.940320       1 gpu_nvml.go:60] found 2 gpu devices
I0424 17:44:39.950882       1 gpu.go:40] Using nvml to obtain gpu power
I0424 17:44:39.954359       1 exporter.go:150] Kepler running on version: 396134a
I0424 17:44:39.954376       1 config.go:172] using gCgroup ID in the BPF program: true
I0424 17:44:39.954403       1 config.go:174] kernel version:
I0424 17:44:39.954520       1 power.go:66] use sysfs to obtain power
I0424 17:44:40.224739       1 exporter.go:175] Initializing the GPU collector
I0424 17:44:40.224758       1 exporter.go:180] Failed to initialize the GPU collector: could not start accelerator collector
I0424 …
```
> gpu: 1) reset err to nil upon successful init, 2) calculate dyn energy so the container gpu metric is calculated

- pkg/cgroup/cgroup_stats_linux.go
- pkg/collector/container_cgroup_collector.go
Some system does not collect all the cgroup stat metrics by default, as in the issue #636.
```bash
$ systemctl show |grep Accounting
DefaultCPUAccounting=no
DefaultBlockIOAccounting=no
DefaultMemoryAccounting=yes
DefaultTasksAccounting=yes
```
This PR fix the nil pointer access for cgroup stat metrics that are not enabled.
> cgroup: update verifying if stat is nil

- cmd/exporter.go
The ebpf compilation skews the overall picture of cpu usage by Kepler. This PR starts profiling after kepler is fully initialized so we can focus on the runtime cpu usage.
> exporter: only profile exporter, skip ebpf compilation

- pkg/collector/container_accelerator_collector.go
- pkg/collector/metric/container_metric.go
- pkg/collector/metric/container_metric_test.go
- pkg/collector/metric/process_metric.go
- pkg/collector/metric/process_metric_test.go
- pkg/collector/prometheus_collector.go
- pkg/collector/prometheus_collector_test.go
- pkg/collector/utils.go
- pkg/model/container_power.go
- pkg/model/estimator/local/benchmark_test.go
- pkg/model/estimator/local/ratio.go
- pkg/model/estimator/local/ratio_process.go
- pkg/model/estimator/local/ratio_test.go
- pkg/model/process_power.go
- pkg/power/accelerator/source/gpu_nvml.go
There exist clusters that lacks CPU power metrics, but exposes GPU power information instead (we are doing experiments in a cluster like that). When CPU power metrics are not available, the Kepler power typically relies on the estimator approach. However, in cases where GPU power metrics are present, it is preferable to use the estimator approach for CPU metrics and the ratio approach for GPU metrics.
This PR allows for the use of two different power models, addressing the aforementioned issue. Additionally, the pull request fixes a bug related to updating GPU metrics for deleted containers where a null pointer error was encountered.
> Fix container GPU power

- pkg/bpfassets/attacher/bcc_attacher.go
- pkg/utils/util_linux.go
Tested on setup with 64 cores, 32 are reserved by applications, kepler can only see 28 of them. This fix is to allow kepler to detect all the cores.
> bpf: read cpu cores from /proc/cpuinfo to get all the cores

- pkg/cgroup/resolve_container.go
Some systems, such as minikube creates a different cgroup path that has only the kubepods keyword
We search for the keywords “crio,” “docker,” or “containerd,” to extract the containerID from the path but this string don’t have these keywords.
`11:blkio:/kubepods/burstable/podf6adb0af-0855-4bab-b25b-c853f18d0ce2/35b97177dada20362ab90d90ac63cd54e8a41cf87bea34f270631b6da17f4a93`
For example, my kind cluster has:
`kubelet-kubepods-burstable.slice/kubelet-kubepods-burstable-pod26822839_8c92_4c60_a921_ffc5991fa00f.slice/cri-containerd-594f6557dc0faa92e0ceac237b78c9e19ad12db5c471c3d2d950d4f2d6b98e4d.scope`
This PR updates the logic extract container id from path.
> Update extract container id from path to support minikube

- pkg/cgroup/cgroup_stats_linux.go
This PR fixes the issue https://github.com/sustainable-computing-io/kepler/issues/687.
The idea is when there is no empty subsystem to get a unified path, we just use the most common subsystem that is pids to get the path. 
> Fix issue 687 by filling empty path

- pkg/cgroup/cgroup_stats_linux.go
- pkg/collector/container_cgroup_collector.go
As described in this GitHub pull PR comment (https://github.com/sustainable-computing-io/kepler/pull/635#pullrequestreview-1425906295), Minikube clusters may have varying cgroup paths, leading to errors when attempting to read cgroup stats.
Rather than assuming that the cgroup error signifies the container's deletion and deleting containerID from the map, we should handle such errors by ignoring them.
> Ignore cgroup error related to minikube cluster

- pkg/collector/metric/node_metric.go
- pkg/collector/metric/node_metric_test.go
- pkg/collector/metric_collector_test.go
- pkg/collector/node_energy_collector.go
- pkg/collector/prometheus_collector_test.go
- pkg/model/container_power_test.go
- pkg/model/estimator/local/benchmark_test.go
- pkg/model/estimator/local/ratio_test.go
- pkg/model/model_test.go
The pre-trained Power Model provides node component power estimates, which return gauge metrics in contrast to the counter metrics used by RAPL.
Consequently, updating the estimated node component as counters would be considered a bug, as it would not appropriately aggregate the gauge values.
To address this issue, this PR includes logic to determine whether a metric should be treated as a gauge or a counter, ensuring proper handling of gauge values.
> Update adding the estimated value to gauge logic

- .github/workflows/release.yml
This PR is to attach a Software bill of materials (SBOM) to the release.yml workflow.
This PR closes: https://github.com/sustainable-computing-io/kepler/issues/685 
I have tested this by forking the repo and creating a test quay.io account to ensure it works and it works fine. The produced SBOM is 19.3MB and will be attached after the container is pushed.
> feat: add sbom to release workflow

- Makefile
consume a tag before we merge a break change as
https://github.com/sustainable-computing-io/local-dev-cluster/pull/10
> update local cluster file to consume tag

- Makefile
When using podman to bring up a local cluster, using the command below,
```
export CLUSTER_PROVIDER=kind
make cluster-sync IMAGE_REPO="localhost:5001" IMAGE_TAG="devel"
```
it fails with the following error when pushing kepler image to local
registry.
```
Error: trying to reuse blob sha256:119391 at destination:
pinging container registry localhost:5001:
Get "https://localhost:5001/v2/": http: server gave HTTP response to HTTPS client
make[1]: *** [Makefile:128: push-image] Error 125
```
This patch fixes it by allowing push options to be specified. E.g. when
using podman, you can turn off tls-verify by ...
```
export CLUSTER_PROVIDER=kind
make cluster-sync IMAGE_REPO="localhost:5001" IMAGE_TAG="devel" CTR_CMD_PUSH_OPTIONS=--tls-verify=false
```
Signed-off-by: Sunil Thaha …
> fix: podman failing to push to local registry

- manifests/README.md
This PR fixes the typo in `manifests/README.md`. The `make build-manifest` command creates folder `_output/generated-manifest`
> Fix typo in README

- build/Dockerfile
- build/kernel-source-images/Dockerfile.ubi
- build/kernel-source-images/build-kernel-source-images.sh
- cmd/exporter.go
- manifests/config/exporter/exporter.yaml
- pkg/bpfassets/attacher/bcc_attacher.go
- pkg/config/config.go
> attacher: try different kernel sources if there is none in default locations

- doc/dev/README.md
with
```
export CLUSTER_PROVIDER=`kind`
```
results in incorrect env value. this fails kepler deployment on kind.
```
$ echo $CLUSTER_PROVIDER
kind creates and manages local Kubernetes clusters using Docker container 'nodes' Usage: kind [command] Available Commands: build Build one of [node-image] completion Output shell completion code for the specified shell (bash, zsh or fish) create Creates one of [cluster] delete Deletes one of [cluster] export Exports one of [kubeconfig, logs] get Gets one of [clusters, nodes, kubeconfig] help Help about any command load Loads images into nodes version Prints the kind CLI version Flags: -h, --help help for kind --loglevel string DEPRECATED: see -v instead -q, --quiet silence all stderr output -v, --verbosity int32 info log verbosity, higher value …
```
> doc: tiny fix for deployment on kind

- .github/workflows/integration_test.yml
- e2e/e2e_metric_test.go
Add bcc tags  in go test command to let the e2e_metric_test.go cases be executed in CI.
Since there is bcc "go:build" annotation there.
See #738.
> Add bcc tags to let the e2e_metric_test.go cases be executed in CI.

- pkg/collector/prometheus_collector.go
https://sustainable-computing.io/design/metrics/#kepler-metrics-overview
```
kepler_node_nodeInfo (Counter) This metric shows the node metada like the node CPU architecture.
Note that this metrics is deprecated and might be updated to kepler_node_info in the next release.
```
> fix: nodeInfo => info

- ADVISORS.md
- GOVERNANCE.md
- MAINTAINERS.md
As discussed in the 06/21 Kepler community meeting, the Kepler Advisory Committee is designed to promote R&D, community engagement, and end user adoption. The scope of the committee and seeding committee members are proposed in this PR.
> community: create Kepler Adivsory Committee and seeding advisors

- pkg/collector/metric_collector.go
- pkg/collector/node_energy_collector.go
- pkg/config/config.go
- pkg/manager/manager.go
- pkg/manager/manager_test.go
- pkg/power/components/power.go
- pkg/power/platform/power.go
- pkg/power/platform/source/acpi.go
- pkg/power/platform/source/hmc.go
Currently, we collect power measurements from various resources, including:
- NODE COMPONENTS: CPU and DRAM
- GPU
- PLATFORM (representing the total node power)
The power or energy consumption of each resource can come from different sources. For instance:
- NODE COMPONENTS can be obtained from different RAPL sources
- GPU power can be measured using nvml or other methods
- PLATFORM power can be derived from RAPL, ACPI, Redfish, or IPMI (currently we only have ACPI, but the PR #734 adds Redfish)
However, the code structure is somewhat confusing, particularly because the interfaces for NODE COMPONENTS and GPU allow the use of different sources, while the PLATFORM component lacks this flexibility.
This pull request aims to align the PLATFORM package with the other components, enabling the …
> Refactor platform package to use different sources like acpi or redfish

- pkg/cgroup/cgroup_stats_linux.go
If you look at how the containerd cgroup library defines an [entry](https://github.com/sustainable-computing-io/kepler/blob/2a32491025b34adc97cab7237ee7ab6070fe9b2a/vendor/github.com/containerd/cgroups/blkio.go#L211) and the format of the cgroup file it is reading from, you can see there are 6 entries for every block device (one for each type of IO operation). This is causing Kepler to record 6x the true number of block devices for V1 cgroups. Instead, we should just count once every time a specific operation is seen (such as "Read"), since each operation will have exactly one entry per block device.
> cgroup: fix incorrect block device count

- cmd/exporter.go
see this 
```
W0629 10:31:12.805210 3680280 exporter.go:160] failed to set kernel source dir to "": stat : no such file or directory
```
seems we should only set kernel path when it's not empty..
> fix: only report warning when given kernel path

- .github/workflows/integration_test.yml
It is well know that `port-forward` is unstable since it does not reconnect if the connection is lost.
But there is a common workaround approach to connect again if the connection is lost.
This PR is fixing this because the CI integration test is failing because of `port-forward` lost connection
> workflows: update port-forward to keep always running

- .github/workflows/gofmt.yml
- .github/workflows/gogc.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/govulnerability.yml
- .github/workflows/image.yml
- .github/workflows/integration_test.yml
- .github/workflows/local_env.yml
- .github/workflows/unit_test.yml
- .github/workflows/unit_test_mac.yml
ref https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
to add path ignore settings in CI to avoid rfc trigger an CI build.
> CI: add path ignore to ensure rfc will not trigger CI.

- .github/workflows/integration_test.yml
- Makefile
- hack/cluster-deploy.sh
- hack/cluster-sync.sh
- hack/cluster-up.sh
- hack/common.sh
- hack/verify.sh
- manifests/config/exporter/patch/patch-ci.yaml
Since we have added support for having microshift as a cluster in the [local-dev-cluster](https://github.com/sustainable-computing-io/local-dev-cluster/pull/18) repo and updated the [kepler-action](https://github.com/sustainable-computing-io/kepler-action/pull/48) as well This PR is in continuation to add support for running Kepler integration tests on microshift cluster.
**Dependency:**
There is an open [PR](https://github.com/sustainable-computing-io/kepler-action/pull/51) in Kepler-action to update some recent [changes](https://github.com/sustainable-computing-io/local-dev-cluster/pull/20) done to local-dev-cluster repo.
CC: @SamYuan1990 @rootfs
> Add support for Microshift in CI

- .github/workflows/integration_test.yml
as CI v0.0.1 released, bump version to v0.0.1 version and avoid checkout main branch for local dev cluster.
as an adjustment from dev branch CI to a release version.
> CI: bump up CI version

- hack/cluster-up.sh
This PR bumps up the version of local-dev-cluster used in cluster-up.sh.
CC: @rootfs @SamYuan1990
> Bump up version of local-dev-cluster in cluster-up.sh

- Makefile
Thanks to report from @jichenjc  in https://github.com/sustainable-computing-io/kepler/pull/752#issuecomment-1624791332, this PR fixes the logic change after merging the PR https://github.com/sustainable-computing-io/kepler/pull/761 by explicitly setting the default target to `kepler` before include `Makefile` in bpfassets. 
> explicitly set default make target

- .github/workflows/integration_test.yml
This PR adds env to build manifest to fix the issue https://github.com/sustainable-computing-io/kepler/issues/784.
However, I'm not sure whether which image should be used in manifest in `kepler.tar.gz` for `build-kepler` job. 
Is it expected to be official image or locally-built image? @vprashar2929  Could you please confirm this?
> set env for build-manifest on e2e test

- manifests/config/exporter/exporter.yaml
In MicroShift > 4.12, to run privileged workloads, you must set pod-security labels on the namespace to `privileged` instead of `restricted`.  This PR adds the necessary namespace labels.
> add pod-security-admission labels for OCP namespace

- enhancements/Release_workflow.md
before https://github.com/sustainable-computing-io/kepler/pull/762 this PR still trigger a CI workflow.
here is my proposal with regular security patch and a schedule to handle breaking change between kepler repos.
> init release flow discussion

- pkg/bpfassets/attacher/libbpf_attacher.go
This PR is follow-up request changes from PR https://github.com/sustainable-computing-io/kepler/pull/752 to request verbosity level to 5 when facing map lookup failure.
Note, thanks to @rootfs, this might be related issue to track: https://github.com/cilium/ebpf/issues/9
> low verbosity of lookup failure

- cmd/exporter.go
- manifests/config/exporter/exporter.yaml
- manifests/config/exporter/kustomization.yaml
- manifests/config/exporter/redfish.csv
- pkg/bpfassets/perf_event_bindata.go
- pkg/collector/metric/node_metric.go
- pkg/collector/metric/utils.go
- pkg/collector/prometheus_collector.go
- pkg/config/config.go
- pkg/nodecred/csv_cred.go
- pkg/nodecred/csv_cred_test.go
- pkg/nodecred/node_cred.go
- pkg/power/platform/power.go
- pkg/power/platform/source/redfish.go
- pkg/power/platform/source/redfish_test.go
- pkg/power/platform/source/redfish_util.go
Get power info from BMCs that support Redfish. Kepler only needs to access chassis and system to get the power info. Currently the existing redfish golang bindings based on OpenAPI client or gofish are overkill. This PR uses simple access models. 
#644
Tasks:
> Support redfish 

- .github/workflows/integration_test.yml
- .github/workflows/integration_test_libbpf.yml
- manifests/config/exporter/patch/patch-ci.yaml
- pkg/bpfassets/attacher/libbpf_attacher.go
- pkg/config/config.go
This PR is to follow CI issue in https://github.com/sustainable-computing-io/kepler/pull/798.
Because kind and microshift must use different manifest file (specifically, kind should use /proc-host mount even if it returns no error but all process goes to system_process while microshift doesn't have that). 
This PR also include adding MAX_LOOK_RETRY configuration via config map to be tuned if needed.
For ci, MAX_LOOK_RETRY=1.
> fix integration ci after adding patch-kind

- pkg/config/config.go
We can confiigure kepler-exporter via /etc/kepler/kepler.config and environment variables.
1. Read configuration from kepler.config
- succeeded: returns value from configMap
- failed: returns value from environment variable if it's available
2. return default value
Environment variable will not be used unless reading from configMap is failed. I think it is not intended, and it would be expected to override configuration from environment variable. So I think the configuration flow should be in below:
1. Returns environment variable if it's available
2. Otherwise returns configuration from kepler.config
3. Returns default value from argument if 2. is failed
> Respects configuration from environment variables

- cmd/exporter.go
- pkg/power/accelerator/source/gpu_nvml.go
As the platform power, the GPU also reports power but we need to convert it to energy.
The GPU operator takes longer time to initialize, we Kepler needs to retry to connect to the nvidia driver until it is ready.
> Fix GPU energy and driver connection problem

- Makefile
otherwise, bpfassets/libbpf/Makefile will be returned so bpfassets/libbpf will be basedir ..
Fixes: #818
> find first Makefile instead of last Makefile

- pkg/power/platform/source/redfish_util.go
I deployed Kepler on Dell PowerEdge R530 with enabling Redfish, then I saw following message on exporter log:
```
I0726 07:59:08.097432       1 redfish_util.go:114] Failed to get power: Get "https://idrac-redfish/redfish/v1/Chassis/System.Embedded.1/Power#/PowerControl": EOF
```
`curl` was succeeded at this endpoint. iDRAC seems to set keep-alive to response header.
```
< HTTP/1.1 200 OK
< OData-Version: 4.0
< Keep-Alive: timeout=60, max=199
< Content-Type: application/json;odata.metadata=minimal;charset=utf-8
```
In this case, we should read all of contents from request body, so we should discard other contents which are not needed to build the model.
> Discard request body in deferred function

- .github/workflows/integration_test.yml
- .github/workflows/integration_test_libbpf.yml
add version for local dev cluster to make a version control
points local dev cluster to a stable version as 0.0.3
> CI: add version for local dev cluster to make a version control

- .github/workflows/integration_test.yml
- .github/workflows/integration_test_libbpf.yml
- Makefile
We should use single image for different k8s cluster right?
in this pr, removed strategy in image build phase of integration test to save time.
> CI: Single image for integration test

- pkg/collector/metric/container_metric.go
fix #844 
I tested my local environment, the `node-exporter` container is not running frequently and always gets "0 active process". With this change, this is the new output
```
I0803 14:40:38.844820 4133674 metric_collector.go:126] energy from pod/container (2 of 12 active processes): name: node-exporter-27nsx/node-exporter namespace: monitoring 
I0803 14:40:41.844848 4133674 metric_collector.go:126] energy from pod/container (0 of 12 active processes): name: node-exporter-27nsx/node-exporter namespace: monitoring 
I0803 14:40:44.844257 4133674 metric_collector.go:126] energy from pod/container (0 of 12 active processes): name: node-exporter-27nsx/node-exporter namespace: monitoring 
I0803 14:40:47.857644 4133674 metric_collector.go:126] energy from pod/container (0 of 12 active …
```
> collector: print total processes

- pkg/model/process_power.go
When the configuration `ENABLE_PROCESS_METRICS` is set `true` in `release-0.5.4`, Kepler terminates with error. It is caused by using inappropriate power model at only one place. This PR fix it.
> use correct PowerModel to get process power

- pkg/collector/node_energy_collector.go
The commit 315b519a1d62831adca3298d694fa7d3dd0fec08 accidentally changed type of platform energy from `gauge` to `counter`.  It causes incorrect calculation of platform energy.  This PR fix the problem.
> fix type of platform energy obtained from systems

- pkg/collector/metric/node_metric.go
- pkg/collector/metric/node_metric_test.go
- pkg/collector/node_energy_collector.go
- pkg/collector/prometheus_collector_test.go
- pkg/model/benchmark_test.go
- pkg/model/container_energy_test.go
- pkg/model/estimator/local/ratio_model_test.go
This PR is to fix and handle issue https://github.com/sustainable-computing-io/kepler/issues/883.
As mentioned in the issue, the function `components.IsSystemCollectionSupported` is to check only RAPL support.
In some environment, RAPL is not there but the GPU power is bypassed. 
So, I separate a case in function `UpdateIdleEnergyWithMinValue`. 
Not sure that should we also separate the case for platform.IsSystemCollectionSupported or not in the future. 
Currently, I keep the assumption that if components is not supported, platform is also not supported. 
If we found the case that this assumption is not valid, we may have to also separate the condition. 
Also, to prevent the failure when the idle collection is not set, I add conditional check whether the id is set in the idle stat too. …
> handle unset idle collection

- pkg/model/estimator/local/ratio.go
According to https://github.com/sustainable-computing-io/kepler/issues/883#issuecomment-1691589435, this PR is to fix the follow-up bugs after fixing the previous bug in the previous PR https://github.com/sustainable-computing-io/kepler/pull/884. Confirmed the fixes. 
> correct GpuUsageMetric param in GetGPUPower

- pkg/bpfassets/attacher/bpf_perf.go
The settings of hardware counters between bcc and libbpf are swapped. This PR correct it.
> correct hardware counter settings

- cmd/exporter.go
- pkg/bpfassets/attacher/bpf_perf.go
According to the fix on previous merged PR https://github.com/sustainable-computing-io/kepler/pull/886, I found the reason the code worked before this vital fix is that the default value of UseLibBPFAttacher is false. It was changed to true after the getCounter function is called and detected that libbpf is built. 
To fix the setting order, I move the logic to auto detect libbpf built to the early point (at the same state that bcc built set the library) which is before getCounter is called. 
> move UseLibBPFAttacher config set to early point

- pkg/bpfassets/attacher/bpf_perf.go
There is another point to fix the issue in accordance to two previous merged PRs: https://github.com/sustainable-computing-io/kepler/pull/887, https://github.com/sustainable-computing-io/kepler/pull/886. 
The Counter variable is still called at the init point which is earlier than what we set value in https://github.com/sustainable-computing-io/kepler/pull/887. So, I moved the Counter variable set to right before we check the available hardware counter that is function `GetEnabledHWCounters `. 
> set counter in GetEnabledHWCounters

- manifests/config/exporter/openshift_scc.yaml
This PR updates the scc configuration post addition of secret volume to daemonset deployment. Identified while testing #877 on OpenShift
> fix scc post redfish secret addition

- hack/build-manifest.sh
- manifests/config/exporter/kustomization.yaml
This PR is related to the issue https://github.com/sustainable-computing-io/kepler/issues/888#issuecomment-1694990086.
The kustomization file needs to be fixed by replacing `kepler_model_server` image not `kepler-estimator` as the estimator has already merged to the model server repo. 
> remove kepler-estimator image and replace kepler_model_server

- bpfassets/perf_event/perf_event.c
- pkg/bpfassets/perf_event_bindata.go
- pkg/collector/node_energy_collector.go
this is to fix an error message in #897 
```
bcc_attacher.go:120] failed to attach perf event cpu_instructions_hc_reader: passed table has wrong size: key_size=0, leaf_size=0
```
@vimalk78 previously suggested it in #896
> bcc: update map names

- cmd/exporter.go
this should fix the issue mentioned https://github.com/sustainable-computing-io/kepler/issues/707#issuecomment-1686090366 and potentially #897
> model config: defer model config to after attacher finishes so to use the right component usage metric

- pkg/model/estimator/local/ratio_process.go
The issue #923 pointed out a bug in the GPU dynamic power estimation for containers.
There was a bug in the ratio formula using the wrong metrics to calculate the ratio.
> Fix GPU ratio bug to use GPU metrics

- Makefile
Sets a default value of `kepler` for `IMAGE_NAME` in the `Makefile`.
7f42672701bd8643507e0ab9ef5dd6da3f58ac76 replaced `kepler` with the environment variable `IMAGE_NAME`. Without a default value set, `make push-image` fails unless the environment variable is manually set.
> fix unset environment variable

- pkg/model/model.go
This PR is aimed to Address issue https://github.com/sustainable-computing-io/kepler-model-server/issues/141. The updated log is:
```
13 08:02:09.123144       1 model.go:120] Using Power Model AbsPower
I0913 08:02:09.123153       1 node_platform_energy.go:54] Using the LinearRegressor/AbsPower Power Model to estimate Node Platform Power
I0913 08:02:09.123167       1 model.go:176] Model Config NODE_COMPONENTS: {ModelType:EstimatorSidecar ModelOutputType:AbsPower TrainerName: EnergySource:rapl SelectFilter: InitModelURL:https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-db/main/models/v0.6/nx12/std_v0.6/rapl/DynPower/WorkloadOnly/LinearRegressionTrainer_1.zip InitModelFilepath: IsNodePowerModel:false ContainerFeatureNames:[] NodeFeatureNames:[] …
```
> Print model config after its change in kepler log

- pkg/collector/container_hc_collector.go
- pkg/collector/metric/vm_metric.go
- pkg/collector/metric/vm_metric_test.go
- pkg/collector/metric_collector.go
- pkg/collector/metric_collector_test.go
- pkg/collector/prometheus_collector.go
- pkg/collector/prometheus_collector_test.go
- pkg/collector/prometheus_process_collector.go
- pkg/collector/prometheus_vm_collector.go
- pkg/collector/utils.go
- pkg/collector/vm_energy_collector.go
- pkg/libvirt/resolve_vm.go
- pkg/libvirt/resolve_vm_test.go
- pkg/manager/manager.go
- pkg/model/vm_power.go
Kepler is able to track all Process Metrics and thus theoretically all KVM/QEMU Virtual Machines (VM) metrics. 
However, when multiple VM are running on the same machine, we have the following problem: 
All "command" are the same and the user can't distinguish the different VM. This is especially a problem for OpenStack user where multiple VM are running on the node. 
In order to solve this issue, this commit adds a new category of metrics dedicated to VM. All the metrics are coming from the Process Metrics. The difference is that the "command" is replaced by the "name" of the VM given by libvirt. 
During the update phase, the processes are filter by Process ID and all PID/TID that belongs to the same VM is inheriting the same "name". The addition of all metrics belonging to the same …
> collector: add kepler_vm metrics

- Makefile
- pkg/config/config.go
- pkg/manager/manager.go
- pkg/model/node_platform_energy.go
- pkg/power/accelerator/gpu/source/gpu_nvml.go
- pkg/power/platform/source/acpi.go
Create a config to be able to set the hard-coded sample rate.
Related to https://github.com/sustainable-computing-io/kepler/issues/539
Also fix an issue with the build_container PATH that is broken on non-standard OS (NixOS here).
> Add a Sample Rate config

- pkg/collector/node_energy_collector.go
- pkg/model/node_component_energy.go
- pkg/model/node_platform_energy.go
This PR is to fix the issue as mentioned in https://github.com/sustainable-computing-io/kepler/issues/944.
I move the logic to get idle powers for both platform and component to new function and call it at `updateNodeIdleEnergy`.
The following graph show changes after the fix in this PR. 
> fix non-zero power on zero usage by estimation

- grafana-dashboards/Kepler-Exporter.json
- manifests/config/dashboard/04-grafana-dashboard-topk.yaml
As pointed by @sthaha in the discussion #946, the Prometheus query (defined in the PR #291) that calculates the `kWh` has a problem in the logic.
The query was only considering the first `1h` interval to extrapolate the results, but it should use the `24h` interval.
The problem is if in the last 1h, the power consumption is high, the extrapolation will show a very high value, even if the early values are low.
Fortunately, the `increase` function actually does what we need. It takes the average value from the entire range and multiply by the available sample interval.
Giving that, I update all the queries that calculate the `kWh` to be as:
```
sum by (container_name, pod_name) (
increase(
(kepler_container_package_joules_total{}[24h:30m])
)
) * $watt_per_second_to_kWh
```
remembering that …
> grafana: update kWh query

- pkg/model/estimator/local/lr.go
- pkg/model/estimator/local/lr_test.go
We fixed in the model server the data normalization to divide a given metric by the max value, because the previous normalization was resulting in negative values.
This PR fix the issue #952.
> Update LR data normalization to divide by the max value (scale)

- cmd/exporter/exporter.go
The manager needs node and container models to update the metrics. So the models should be created before the manager starts.
> exporter: create model before manager starts

- pkg/collector/prometheus_collector.go
As described in the issue #956, as container is group of processes, Kepler randomly associates a command of one process to the container. Consequently, the GPU power will be exposed intermittently with different commands.
This PR disable the command exported in the Prometheus container metrics.
We will optionally enable it back after fixing the code duplication from issue https://github.com/sustainable-computing-io/kepler/issues/663.
> Fix GPU power double counting by removing the container command

- pkg/model/estimator/local/ratio.go
- pkg/model/estimator/local/ratio_process.go
The previous code refactoring incorrectly defined the idle power due to a copy-and-paste error.
According to the GHG protocol, we are supposed to divide the idle power based on the application's size, which should align with the container's resource request. However, as there are containers without requests, implementing this can be challenging.
As a quick solution, this PR reverts to the previous logic of evenly distributing the idle power across all containers.
> Update idle power model

- .gitignore
Ignoring tmp dir is useful to keep all temporary project related files under the tmp directory.
> git: ignore root tmp dir

- build/Dockerfile.bcc.kepler
fix #973 
Using mismatched kernel source causes ebpf unable to get cpu time correctly
> build: drop ubi 8 kernel source to fix issue #973

- cmd/exporter/exporter.go
- pkg/collector/prometheus_collector.go
- pkg/config/config.go
The PR https://github.com/sustainable-computing-io/kepler/pull/955 only fixed the `IsEstimatedIdlePowerEnabled` function, but we need to also fix the `SetEnabledEstimatedIdlePower`...
This PR fixes the `SetEnabledEstimatedIdlePower`
> config: fix expose idle power for BMs

- cmd/exporter/exporter.go
- pkg/collector/metric_collector.go
- pkg/model/container_energy.go
- pkg/model/process_power.go
This PR is for fixing an issue we discovered after PR https://github.com/sustainable-computing-io/kepler/pull/950 merged. 
On VM, container power has not related to CPU time as expected.
The reason is that it is using the hardware counter for the ratio power model.
Confirming that by printing out the container feature names as below (recommend to keep this line print).
After debugging session with @marceloamaral, we found that the root cause is the attacher.HardwareCountersEnabled set after BPF attachment inside the manager start.
```
I1010 09:05:00.775838 3114275 container_energy.go:109] Using the Ratio/DynPower Power Model to estimate Container Platform Power
I1010 09:05:00.775881 3114275 container_energy.go:110] Container feature names: [cpu_instructions]
I1010 09:05:00.775909 3114275 …
```
> move model initialization after BPF attach

- pkg/cgroup/resolve_container.go
The issue #923 identified a bug in resolving the container ID, where it was getting the Docker container ID instead of the Kubernetes container ID.
The CRI-O container ID is always located at the end of the cgroup path. Therefore, this PR fix the issue by removing the unnecessary portion of the string to prevent such a bug.
> Fix resolve container id for new systems

- .github/dependabot.yml
try to enable depend bot for kepler repo
I am not sure if depend bot able to support go vendor folder or not....
but let's try?
> add depend bot setting

- .github/workflows/platform-validation.yml
1. Fix #962 
2. Change the port forwarding destination port of kepler-exporter and prometheus-k8s-0 from well-known port to avoid conflict when the test runner also joined other Kubernetes cluster where Kepler/Prometheus also deployed.
> Add ebpfprovider to align with kepler-action

- pkg/collector/prometheus_process_collector.go
> prometheus: remove not utf-8 encoding cmd

- manifests/config/exporter/exporter.yaml
- pkg/libvirt/resolve_vm.go
- pkg/libvirt/resolve_vm_test.go
Link #1008 
1. mount hostpath /var/run for manifests deployment.
2. fix path join error.
> vm_metrics: fix libvirt path join error

- Makefile
- hack/build-manifest.sh
- hack/tools.sh
- hack/utils.bash
kubectl version --short has been deprecated since 1.23. In the latest kubectl, the flag is removed and causes `build-manifest` to fail when checking for the version.
This fixes the version check by using --client -o json options and using jq to validate if the version is higher than expected - 1.21
> fix(build): support newer version of kubectl

- Makefile
This commit enables local build of kepler with libbpf.
Additional packages required to build (for fedora): `libbpf-devel` `libbpf-static`
usage: `ATTACHER_TAG=libbpf make build`
> fix(Makefile): enable `libbpf` based local build

- manifests/config/exporter/exporter.yaml
- manifests/config/exporter/openshift_scc.yaml
- manifests/config/exporter/patch/patch-openshift.yaml
fixes #771 
- feat: reduce privileges granted through SCC for OpenShift
- feat: set mounted volumes as read only as much as possible
- feat: set pod hostPID to true to avoid collisions/unwanted behavior in host PID namespace
- feat: remove unnecessary mount of /sys/kernel/debug
Same improvements were already merged in the kepler-operator: https://github.com/sustainable-computing-io/kepler-operator/pull/185
And the removal of the /sys/kernel/debug was discussed here: https://github.com/sustainable-computing-io/kepler-model-server/pull/158#discussion_r1323177090
> Feat: 771 remove unnecessary security concerns

- pkg/bpfassets/attacher/bpf_perf.go
seeing this which makes me confusing , add logs should be helpful for such scenario
```
Nov 01 10:10:36 jitest51.novalocal kepler[25539]: I1101 10:10:36.989443   25539 bpf_perf.go:132] failed to attach bpf with libbpf: failed to load module: stat /bpfassets/libbpf/bpf.o/amd64_kepler.bpf.o: no such file or directory
Nov 01 10:10:36 jitest51.novalocal kepler[25539]: I1101 10:10:36.989486   25539 exporter.go:240] failed to start : failed to attach bpf assets: no bcc build tag
```
> Add log to make logic clearer

- build/Dockerfile.bcc.kepler
I made some improvements to the Dockerfile:
-  Added GOCACHE environment variable for caching. 
-  Implemented caching and downloading of Go dependencies, triggered only if go.mod or go.sum changes.
-  Introduced a cache layer in the build process to enhance overall build speed.
To verify these changes, run the build process twice:
1. The first build will download and save dependencies in the cache.
2. The second build will utilize the cache layer for a faster image build.
> feat: Improve Dockerfile caching for faster builds (#913)

- pkg/bpfassets/attacher/libbpf_attacher.go
This PR is to fix the bug described in https://github.com/sustainable-computing-io/kepler/issues/1057. 
> fix bug failed to get metric after first collection

- Makefile
- build/Dockerfile
- build/Dockerfile.bcc.kepler
- build/Dockerfile.libbpf.kepler
As we have dep bot looks after our dependence , hence we don't need go mod tidy to update our dependence before our build. We can make the go build relays on our vendor to save time for image build.
> CI: try to set GO111MODULE to off and use vendor folder for build(#913)

- build/Dockerfile.bcc.base
- build/Dockerfile.bcc.base.amd64
- build/Dockerfile.bcc.base.arm64
- build/Dockerfile.bcc.base.s390x
- build/Dockerfile.libbpf.base
- build/Dockerfile.libbpf.base.amd64
The UBI image doesn't have `/usr/local/lib64` in ld conf. Need to add it explicitly to pick up xgboost library.
> add xgboost to ld cache

- pkg/power/accelerator/gpu/source/gpu_nvml.go
Avoid calling `nvml` package function is `nvml.Init()` fails. 
In the current version of nvml (`0.11`) , if the shared lib `libnvidia-ml.so` is not present, it `panic`s, and we use `recover()` to handle this and report error.  But in the new version of nvml (`0.12.0`) if  `libnvidia-ml.so` is not available, the nvml handles the situation and returns an error. And expectation is we should not use `nvml` function after this.
This PR fixes it, and should help in passing PR https://github.com/sustainable-computing-io/kepler/pull/988 tests
> fix(gpu): dont use nvml symbol if lib not found

- .github/workflows/image.yml
- .github/workflows/image_pr.yml
- .github/workflows/integration_test.yml
- .github/workflows/integration_test_bcc.yml
- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- .github/workflows/unit_test.yml
- Makefile
- build/Dockerfile
- doc/dev/prepare_dev_env.sh
- packaging/rpm/kepler.spec
- tag existing 'latest' image as 'latest-bcc'
- tag existing 'latest-libbpf' as 'latest'
- make libbpf image as default released image
- use libbpf as attacher for PR image
- make unit_test run with libbpf attacher
- build kepler with libbpf attacher for rpm build
- rename integration_test to integration_test_bcc
- rename integration_test_libbpf to integration_test
> chore(ci): make libbpf as the default attacher

- hack/cluster-deploy.sh
This PR updates the `cluster-deploy.sh` manifests to point to the local devel Kepler image.
> fix: allow manifest to use devel kepler image

- .github/workflows/unit_test.yml
Update CI to use `libbpf` as provided by kepler-action
Follow-up PR for https://github.com/sustainable-computing-io/kepler-action/pull/90
> chore(ci): Update unit_test to use libbpf from kepler action

- .github/workflows/image_base.yml
- Dockerfile.builder
- Adds Dockerfile.builder which installs everything required to build kepler code 
- Updated github workflow to build and push the builder image
> chore(build): Add base image Dockerfile for building kepler with libbpf

- Makefile
- build/Dockerfile.builder
- Added build/Dockerfile.builder, somehow got removed in earlier PRs.
- Removed hardcoded `GOROOT` in Makefile
- Fixed timestamp in rpm build
With these changes to the builder image, the rpm can be built.
/cc: @rootfs
> fix(rpm): Fix rpm builds in new build process

- cmd/validator/validator.go
- pkg/metrics/node/metrics.go
- pkg/sensors/accelerator/gpu/power.go
- pkg/sensors/accelerator/gpu/source/gpu_dummy.go
- pkg/sensors/accelerator/gpu/source/gpu_nvml.go
- pkg/sensors/accelerator/qat/source/qat_telemetry.go
- pkg/sensors/components/power.go
- pkg/sensors/components/source/apm_xgene_sysfs.go
- pkg/sensors/components/source/dummy.go
- pkg/sensors/components/source/estimate.go
- pkg/sensors/components/source/rapl_msr.go
- pkg/sensors/components/source/rapl_sysfs.go
- pkg/sensors/platform/power.go
- pkg/sensors/platform/source/acpi.go
- pkg/sensors/platform/source/hmc.go
- pkg/sensors/platform/source/redfish.go
This commit adds `platform_power_source` and `components_power_source`
to `kepler_node_info`. This allows users to filter metrics by a particular
power source by using [joins on labels](https://www.robustperception.io/left-joins-in-promql/).
Produces 
```
kepler_node_info{components_power_source="rapl-sysfs",cpu_architecture="Skylake",platform_power_source="none",source="os"} 1
````
Signed-off-by: Sunil Thaha <sthaha@redhat.com>
> feat(metrics): expose power source information in kepler_node_info

- Makefile
currently libbpf module is not auto built. We need to have a fresh rebuild in each container build.
> force build libbpf module before building kepler

- .github/workflows/image.yml
- .github/workflows/image_base.yml
- .github/workflows/unit_test.yml
in recently our daily build fails, and I further checked our commit history found out that ... after #1118 been merged
1. As the 1118 depends on some branch as `base`(for historical reason we keep the base image build steps at branch base but not main.). One of the make script/make rule which only available on branch base is lost, thus cause we fails with daily build.
2. Meanwhile, 1118 removed arch support as cross platforms build for arm64 linux/arm64
3. A security update by depends bot suggestion.
> [tbd][CI] security update, daily job fix, try to recover arm64 support from base.

- .github/workflows/release.yml
- .github/workflows/rpm.yml
ref https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> [CI] update set output to github output

- .github/workflows/image.yml
- .github/workflows/image_pr.yml
- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- Makefile
after we have base image support with arm64, we can add arm64 in image build process.
and fix bug as base image removed epel support.
> [CI] enable arm64 support and fix bug for epel

- pkg/metrics/metricfactory/metric_factory.go
After the code refactoring, the metric showing the platform energy is missing the configuration to set the energy source as `acpi`.
This PR is fixing this.
> Fix platform source label with acpi

- .github/workflows/image.yml
- .github/workflows/image_pr.yml
- .github/workflows/release.yml
temporarily disable arm64 build. Will enable it after resolving libbpf module build issue in https://github.com/sustainable-computing-io/kepler/actions/runs/7659192488/job/20873789773
> image: don't build for arm64 for now due to an issue in libbpf build

- doc/dev/role.yaml
- e2e/integration-test/e2e_metric_test.go
- e2e/integration-test/e2e_stress_test.go
- e2e/integration-test/e2e_suite_test.go
Ensure some (i.e. uncore) metrics can be ignored while useful metrics should always be valid.
> separate metric checking into non zero and can-be-zero metrics

- pkg/collector/stats/stats.go
- pkg/metrics/metricfactory/metric_factory.go
- pkg/metrics/utils/utils.go
Currently the dynamic GPU power is not shown in the metrics, this is because the metric is not yet.
In `UpdateDynEnergy()`, the initial GPU dyn stats is empty, so we need to use `AbsEnergyInGPU` stat to enumerate all the GPU IDs.
> gpu: expose both idle and dyn gpu power

- .github/workflows/image_base.yml
- build/Dockerfile.builder
from daily build job, it seems we have some issue for now with arm64 base image build. remove the arm64 base image for now. 
meanwhile, add cpuid into base image for rpm build.
> fix daily build issue for arm64 and rpm build

- pkg/collector/metric_collector.go
- pkg/collector/resourceutilization/accelerator/process_gpu_collector.go
fixing #1233
This PR is:
- refactoring the code fixing the function name that is updating process metrics not node metrics
- fixing process resource usage map to use GPU ID as the map key
> fix process resource usage map to use GPU ID as the map key

- .github/workflows/image.yml
- .github/workflows/image_base.yml
- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- .github/workflows/rpm.yml
- build/Dockerfile.kepler-validator
changes in this PR:
- make validation image use same base image file as kepler itself.
- make image build support validation image.
- make image daily build CI with input tag as parameter.
- remove latest tag from release as it already used in daily job.
- enhance release CI to reuse same action with daily job.
- update SBOM file logic in release process accordingly.
- enhance rpm daily build with same parameter as release build, enhance rpm build in release process will in another PR.
- CI check for image and base image in PR steps.
> [CI] Enhance CI to reduce duplicate code

- pkg/sensors/accelerator/gpu/source/gpu_dcgm.go
There are too many steps converting the collected DCGM metric, such as converting it to float, to string and then to uint32.
We should convert the float metric directly to uint32 for performance reasons.
> dcgm: improve the uint32 conversion performance

- .github/workflows/image_base.yml
some refactoring, so we can use manual github action and bot credentials to build builder images.
> base image build refactoring

- .github/workflows/baseimage_dispatch.yml
- .github/workflows/image_base.yml
Reverts https://github.com/sustainable-computing-io/kepler/pull/1262, as it makes a wrong implementation.
Just replaced workflow call by workflow_dispatch, which breaks everything in automation, either PR check or daily build.
To support workflow_dispatch, which this PR contains a temporary solution as an example.
Pre previously CI consideration/supporting for base image as https://github.com/sustainable-computing-io/kepler/issues/1047 which base image should up to date and maintained by CI.
Hence, considering the PR may breaks nightly build. Our CI for base image supports feature for:
- Nightly to fix CVEs for dependency.
- Pre PR, to validate if changes breaks CI.
> [CI] revert #1262

- .github/workflows/image.yml
- .github/workflows/image_pr.yml
Local build for S390 works, but there is issue in github CI. So disable CI for now.
```
> [linux/s390x builder 4/4] RUN ATTACHER_TAG=libbpf make build:
6.066 rm -rf _output/bin
6.401 clang \
6.401 	-I /usr/include/s390x-linux-gnu \
6.401 	-D __TARGET_ARCH_s390 \
6.401 	-O2 -g -c -target bpf \
6.401 	-o bpfassets/libbpf/bpf.o/s390x_kepler.bpf.o bpfassets/libbpf/src/kepler.bpf.c
7.080 clang-16: error: unknown argument: '-g'
7.081 clang-16: error: unknown argument: '-c'
7.082 clang-16: error: unknown argument: '-o'
7.172 make: *** [bpfassets/libbpf/Makefile:11: kepler.bpf.o] Error 1
------
WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load …
```
> ignore CI for s390

- .github/workflows/baseimage_dispatch.yml
- .github/workflows/image.yml
- .github/workflows/image_base.yml
- .github/workflows/integration_test.yml
- .github/workflows/rpm.yml
update qemu version to support s390x libbpf compile.
fix null value for github version in daily rpm build job.
removed libbpf in integration build process as no needed.
add condition for sbom artifactory upload.
validation image is x86 only for now.
> [CI] update QEMU version to support s390 libbpf compile and nitfixs

- .github/workflows/image.yml
- Makefile
- build/Dockerfile
- hack/cluster-deploy.sh
This PR fixes issue #1264 where the wrong version of Kepler was reported in logs. 
* Updates the image workflow to accept the version as `imageTag` value.
* Update Makefile to make use of VERSION when building images.
* Update dockerfile to accept VERSION arg while running `make build` command
* Some minor updates to local `cluster-deploy` script
> fix: update dockerfile to respect the kepler version

- data/cpus.yaml
Adding AMD Siena to the list of processors.
This is the lscpu for this AMD Siena processor :
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              96
On-line CPU(s) list: 0-95
Thread(s) per core:  2
Core(s) per socket:  48
Socket(s):           1
NUMA node(s):        8
Vendor ID:           AuthenticAMD
BIOS Vendor ID:      AMD
CPU family:          25
Model:               160
Model name:          AMD EPYC 8434P 48-Core Processor
BIOS Model name:     AMD EPYC 8434P 48-Core Processor
Stepping:            2
CPU MHz:             2500.000
CPU max MHz:         3107.9099
CPU min MHz:         1500.0000
BogoMIPS:            4992.78
Virtualization:      AMD-V
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K …
> data/cpus: Adding AMD Siena

- Makefile
`container_build` target should not need host network or be root to build kepler
> fix(makefile): container_build target builds as current user

- Makefile
This PR updates Makefile to check for podman or docker availability and paths conditionally. In the situation where podman and docker both are installed and docker is up and running but podman is not up then any make target that makes use of `CTR_CMD` uses podman
> chore: update Makefile to conditionally check for podman or docker availability and paths

- pkg/sensors/components/source/apm_xgene_sysfs.go
I saw following logs in twice by 3 seconds on Arm baremetal server. We should control them with verbosity level.
```
I0401 06:55:09.789155       1 apm_xgene_sysfs.go:61] Found power input file: /sys/class/hwmon/hwmon0/power1_input
```
See discussion in https://github.com/sustainable-computing-io/kepler/issues/1156#issuecomment-2029323519
> Change log level about power input file

- manifests/config/exporter/patch/patch-estimator-sidecar.yaml
Regarding the issue reported in https://github.com/sustainable-computing-io/kepler/issues/1306, now we have the new power model for v0.7 available on kepler-model-db according to the merge https://github.com/sustainable-computing-io/kepler-model-db/pull/22.
This PR updates the ConfigMap manifest and adds disclaimer and recommendation for the configuration. 
> update model URLs to v0.7

- .github/workflows/daily.yml
This PR is for #1326.
I added `github.repository == 'sustainable-computing-io/kepler'` to prevent to run daily.yml on forked repo. Similar code works fine on [Carbon Aware SDK by Green Software Foundation](https://github.com/Green-Software-Foundation/carbon-aware-sdk).
https://github.com/Green-Software-Foundation/carbon-aware-sdk/commit/06c5577397815f2e867a349da7c74be06a9423d1
> Restrict repository to run daily.yml

- pkg/config/config.go
- pkg/model/model.go
With the current code, for the deployment with only server-api (component of kepler-model-server), kepler exporter must specify trainer name to the power model weight request to the server-api. 
If no trainer name defined, linear regression will be applied. 
https://github.com/sustainable-computing-io/kepler/blob/6b7b15939810680f7603363ab3ce4bd5995de3ff/pkg/model/estimator/local/regressor/regressor.go#L228-L229
However, on the server-api side, if the trainer_name is not defined, it will return the best power model which is not limited to linear regression. So, we should set the default value of the trainer in configuration at the exporter.
> set default trainer name

- .github/workflows/release.yml
- .github/workflows/rpm.yml
- packaging/rpm/container-kepler.spec
The kepler rpm is to be replaced by the podman rpm. Don't build it during release.
> update container-kepler spec; don't build kepler rpm during release

- build/Dockerfile
This commit reduces container image size by
1. Removing `yum update` resulting in more reproducible builds. Updates to the packages are best obtained by pulling a newer base image (which is tested) than running `yum update`
2. fixing installation of dcgm only when it is enabled
```
❯ make build_containerized IMAGE_REPO=quay.io/sthaha CTR_CMD=docker
...
❯ docker images | head -n 5
REPOSITORY                                             TAG                             IMAGE ID       CREATED          SIZE
quay.io/sthaha/kepler                                  latest-dcgm                     ec386bae9d62   8 seconds ago    1.96GB
quay.io/sthaha/kepler                                  v0.7.9-dirty-linux-amd64-dcgm   ec386bae9d62   8 seconds ago    1.96GB
quay.io/sthaha/kepler …
```
> fix(build): reduce container image size

- build/Dockerfile
This commit squashes multiple RUN which results in separate layers into a single layer by combining install and cleanup into a single RUN. Additionally, the default SHELL is replaced with bash instead of sh so that `[[ ]]` etc are supported better.
```
❯ docker images | head -n 5
REPOSITORY                                TAG                                        IMAGE ID       CREATED          SIZE
quay.io/sthaha/kepler                     latest-dcgm                                c24bc6eb9191   20 seconds ago   1.88GB
quay.io/sthaha/kepler                     v0.7.9-2-g6807777e7e821-linux-amd64-dcgm   c24bc6eb9191   20 seconds ago   1.88GB
quay.io/sthaha/kepler                     latest                                     5e7ec39af2c1   2 minutes ago    308MB
quay.io/sthaha/kepler …
```
> fix(build): reduce image size by squashing install and clean steps

- hack/compose.yaml
- hack/compose/grafana/dashboards/kepler/dashboard.json
This PR updates the docker-compose grafana dashboard to include a panel for visualizing `core_joules_total`
Dashboard screenshot for reference:
> fix: update dashboard for docker-compose

- .github/workflows/image.yml
This PR corrects the name of the image tag for dcgm in the image workflow. 
Due to the incorrect name, the dcgm image of Kepler wasn't updating on quay.
> fix: correct the name dcgm in the image tag

- .github/workflows/image.yml
- Makefile
- build/Dockerfile
This PR updates GH workflow to respect build args while building Kepler images and also updates the Makefile accordingly.
Fixes the issue where `latest-dcgm` images were not built correctly
> fix: image workflow to pass build args correctly

- Makefile
- build/Dockerfile
- hack/cluster-clean.sh
- hack/cluster-deploy.sh
- hack/cluster.sh
Add a single command (`make run-on-kind`) to spin-up a kind cluster with prometheus and grafana also deployed in the cluster. This commit also moves the go source formatting and mod updates inside the pod context, when images are built.
> Makefile: add make run-on-docker

- build/Dockerfile
- build/Dockerfile.builder
I had checked image tags and software inside the image and https://quay.io/repository/sustainable_computing_io/kepler/manifest/sha256:b1a7c4d0faf65221667ec67b5da5c15fc75eeda21e018270873a5c0562e180a2?tab=vulnerabilities
The latest image is registry.access.redhat.com/ubi9:9.3 but personally I would like registry.access.redhat.com/ubi9:latest tag, as I don't know how to trace a new tag for registry.access.redhat.com/ubi9 hence keep it with latest tag. Once they have registry.access.redhat.com/ubi9:9.4, we can benefit without a PR.
further compare via
https://catalog.redhat.com/software/containers/ubi9/618326f8c0d15aff4912fe0b?architecture=amd64&image=65e093e60a21b531a96f93ca
https://quay.io/repository/sustainable_computing_io/kepler/manifest/sha256:b1a7c4d0faf65221667ec67b5da5c15fc75eeda21e01 …
> [CI] update ubi image for CVE fix

- cmd/exporter/exporter.go
verified by running `go tool pprof http://localhost:8888/debug/pprof/heap`.
> feat(kepler): enable pprof

- pkg/collector/metric_collector.go
Update `NodeStat` 's `ResourceUsage` when updating `"avg_cpu_freq"` metric
Fixed Segmentation fault when collecting node avg cpu freq
> Fix cpu freq collection in nodeStat

- Makefile
- hack/tools.sh
Add `yq` to the tools script - it's needed for Kepler Grafana dashboard installation automation 
> Note:  if `yq` isn't available on the platform the grafana deployment script simply skips the step that adds the grafana dashboard to grafana and deploys grafana with all the preconfigured dashboards
> tools: add install_yq

- manifests/compose/validation/metal/grafana/dashboards/validation/dashboard.json
Fix includes:
* showing process and its PID for easier identification
* use right promql for metal process package metrics
* Use same color code for metal (idle, dyn), vm, scaphandre
> fix(dashboard): show metal and VM metrics correctly

- manifests/compose/mock-acpi/compose.yaml
- manifests/compose/mock-acpi/grafana/dashboards/mock-acpi/dashboard.json
- manifests/compose/mock-acpi/intel-pcm/intel-pcm.yaml
- manifests/compose/mock-acpi/mock-acpi/Dockerfile
- manifests/compose/mock-acpi/prometheus/scrape-configs/mock-acpi.yaml
- manifests/compose/mock-acpi/turbostat/Dockerfile
- manifests/compose/mock-acpi/turbostat/run_turbostat.py
- manifests/compose/mock-acpi/turbostat/turbostat.yaml
- manifests/compose/monitoring/grafana/Dockerfile
- manifests/compose/monitoring/prometheus/Dockerfile
- Added [turbostat](https://www.linux.org/docs/man8/turbostat.html) to the manifest/compose, a tool to report cpu frequency among other things (power) 
- changed compose Dockerfiles to not use docker.io base images as these get throttled. used similar images from quay
- some refactoring for intel-pcm
cpu freq reported by turbostat with low load on machine
cpu freq reported by turbostat with heavy load on machine
> Added turbostat to compose files, and some refectoring

- build/Dockerfile.builder
updating libbpf + elfutils package versions to align with local-dev-cluster as these were causing build failures in the local-dev-cluster unit tests (as old packages didn't exist)
https://github.com/sustainable-computing-io/local-dev-cluster/pull/80/files#r1588896032
> Dockerfile.builder: update libbpf + elfutils pkgs

- build/Dockerfile.builder
Go 1.20 is not supported since Go 1.22 was released in February 2024.
> chore: Bump Go Version

- manifests/compose/mock-acpi/intel-pcm/intel-pcm.yaml
intel-pcm dashboard now shows all panels
> use `$__rate_interval` in intel-pcm dashboard

- build/Dockerfile
update the linux version to match the changes in https://github.com/sustainable-computing-io/kepler/commit/f1a8267b6dea1795124bb4d9827d507f5d3f6ec9 
It seems this was missed in the checks for https://github.com/sustainable-computing-io/kepler/pull/1408 - only found it today when running `make build_image`
> Dockerfile: update libbpf-source linux version

- manifests/compose/dev/grafana/dashboards/dev/dashboard.json
This commit:
* Adds panels to highlight the degree of regression between dev and latest version.
* Adds panel for visualizing more info related to Node and process like Core, Package, Dram, Other, CPU cycles, CPU miss and BPF CPU time.
Sample screenshot of dashboard:
> dashboard(dev-compose): improve dev dashboard

- bpfassets/libbpf/src/kepler.bpf.c
- bpfassets/libbpf/src/kepler.bpf.h
- pkg/bpfassets/attacher/attacher.go
This fixes a few issues identified with the bpf code format and refactor.
1. Zero initialize all variables
2. Use the bpf_perf_event_read_value helper exlusively
3. Cherry-pick of PR #1410 - reported by @vimalk78 - which correctly sizes the `processes` and `pid_time` maps. Without this patch entries won't be created in the `processes` map for pids that are > `number of cpu cores` which fundamentally breaks power reporting.
In addition, add some logging around eBPF array resizing.
Fixes: #1402 #1411
> fix(bpf): Fix issue(s) introduced with bpf refactor

- pkg/bpfassets/attacher/attacher.go
For local development the instructions suggest running:
./_output/bin/linux_amd64/kepler
This checks for the bytecode in /var/lib/kepler/bpfassets However, for local development this directory doesn't exist.
The fallback was to look in ../../../bpfassets/libbpf/bpf.o Running the recommended command was causing kepler to look in strange locations (i.e /bpfassets) for bytecode.
This PR fixes the lookup for local development to use a glob pattern starting at the current directory. This works well for local development, with the added bonus of making it easier to test kepler builds on remote systems since you can also copy the binary and bytecode files together, without having to place the bytecode in a special path.
> fix(bpfassets): Fix object file lookup

- manifests/compose/dev/grafana/dashboards/dev/dashboard.json
Add process filter which also shows `pid`  as below
> dev(dashboard): show both process and pid in filter

- manifests/compose/dev/grafana/dashboards/dev/dashboard.json
Update dashboard to show both dev and latest values as follows
> dev(dashboard): show values of dev and latest in ratio panel

- manifests/compose/dev/grafana/dashboards/dev/dashboard.json
This commit makes the following changes to the dev vs latest dashboard.
Summary: 
* compares idle and dynamic separately
* clearly defines acceptable range within 20% of the latest. Below you can find that the idle ratio (dev/ latest) is close to 1.0 while dynamic (in red) seems way off. 
* shows both dynamic and idle actual values close to ratio panels
* allows latest to be overlayed on dev to panel (disabled by default)
* Uses uniform colour codes to diffrentiate `dev` (lighter) and `latest` (darker) , `dynamic` (orange) and `idle` (blue)
Signed-off-by: Sunil Thaha <sthaha@redhat.com>
> dev(dashboard): compare dynamic and idle separately

- .github/workflows/image_base.yml
- build/Dockerfile
- build/Dockerfile.kepler-validator
Requires: https://github.com/sustainable-computing-io/kepler/pull/1432 and a [new builder image to be published](https://github.com/sustainable-computing-io/kepler/actions/runs/9096525945)
> chore(build): use latest builder image - ubi-9-libbpf-1.3.0

- .github/workflows/release.yml
Per [this doc](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#example-configurations), we can add changelogs in release page.
> update release changelogs

- bpfassets/libbpf/src/kepler.bpf.c
This commit changes all declarae and then initialise code of form below
```
struct foobar x; x.a = a; x.b = b;
```
to
```
struct foobar x = { .a = a, .b = b, };
```
The difference in the code produced is as follows
```
;  new_pid_key.pid = cur_pid;                             | pid_time_t new_pid_key = {.pid = cur_pid };
0: 63 6a fc ff 00 00 00 00	*(u32 *)(r10 - 0x4) = r6  |  0:	79 a1 68 ff 00 00 00 00	r1 = *(u64 *)(r10 - 0x98)
1: bf a2 00 00 00 00 00 00	r2 = r10                  |  1:	63 1a fc ff 00 00 00 00	*(u32 *)(r10 - 0x4) = r1
2: 07 02 00 00 fc ff ff ff	r2 += -0x4                |  2:	bf a2 00 00 00 00 00 00	r2 = r10
3: bf a3 00 00 00 00 00 00	r3 = r10                  |  3:	07 02 00 00 f0 ff ff ff	r2 += -0x10
4: 07 03 00 00 70 ff ff ff	r3 += -0x90
```
Modifies calc_delta to remove …
> fix(bpf): cleanup initialising structs and nested ifs

- e2e/tools/validator/src/validator/cases/__init__.py
- e2e/tools/validator/src/validator/cli/__init__.py
New Grafana Cases include the following metrics: kepler_process_platform_joules_total, kepler_process_package_joules_total, kepler_process_bpf_cpu_time_ms_total, kepler_process_bpf_page_cache_hit_total. These have been included in the Cases module.
> Include Grafana Cases into the Case Module

- pkg/model/node_component_energy.go
Use `NodeComponentPowerModel` instead of `NodePlatformPowerModel`
This fixes https://github.com/sustainable-computing-io/kepler/issues/1459
> fix(model): Use correct variable in `IsNodeComponentPowerModelEnabled()`

- pkg/metrics/utils/utils.go
removes debugging logging from GPU metrics
> fix: remove logging while collecting GPU metrics

- manifests/compose/dev/grafana/dashboards/dev/dashboard.json
This PR:
* Corrects the query for `bpf_cpu_time_ms_total` metric
* Fixes the display issue for panels showing CPU time, cache miss, CPU cycles and instructions
Before:
After:
> fix(dev-dashboard): update and correct metrics in dev dashboard

- pkg/collector/stats/stats.go
- pkg/metrics/consts/conts.go
- pkg/metrics/container/metrics.go
- pkg/metrics/utils/utils.go
- pkg/model/estimator/local/ratio.go
- pkg/model/estimator/local/regressor/exponential_test.go
- pkg/model/estimator/local/regressor/linear_test.go
- pkg/model/estimator/local/regressor/logarithm_test.go
- pkg/model/estimator/local/regressor/logistic_test.go
- pkg/model/estimator/local/regressor/regressor.go
- pkg/model/estimator/local/regressor/regressor_test.go
- pkg/model/estimator/local/regressor/suite_test.go
- pkg/model/estimator/sidecar/estimate.go
- pkg/model/estimator/sidecar/estimate_test.go
- pkg/model/model.go
- pkg/model/node_component_energy.go
- pkg/model/node_platform_energy.go
- pkg/model/process_energy.go
- pkg/model/utils/utils.go
This PR is to fix the issue regarding platform power reported in the [slack channel](https://cloud-native.slack.com/archives/C05QK3KN3HT/p1716227365364569) as well as my direct experience in https://github.com/sustainable-computing-io/kepler/issues/1466.
I have found the different handling between component power and platform power in the model package.
Power model return power in joule unit in float. However, we handle the power in millijoule in Kepler. 
Component power has been converted correctly by GetComponentPower in utils module. On the other hand, platform power is used as-is.
After fix:
As seen in the above validation, there are still more points to investigate or fix. 
I have stressed 70% of CPU in a single CPU (it supposes to use 700ms). 
The most critical part is the BPF CPU …
> fix platform power return unit

- e2e/tools/validator/.gitignore
- e2e/tools/validator/README.md
- e2e/tools/validator/pyproject.toml
- e2e/tools/validator/src/validator/cases/__init__.py
- e2e/tools/validator/src/validator/cli/__init__.py
- e2e/tools/validator/validator.yaml.sample
RHEL 9 doesn't have python 3.12. So we need to use the latest i.e. 3.11
> chore(validator)update validator usage; remove job from prom query

- e2e/tools/validator/query.json
- e2e/tools/validator/src/validator/cases/__init__.py
- e2e/tools/validator/src/validator/cli/__init__.py
- e2e/tools/validator/src/validator/config/__init__.py
- e2e/tools/validator/validator.yaml.sample
Adding vm name option allows [this](https://github.com/sustainable-computing-io/ci-playground/actions/runs/9228340618/job/25392244148) CI pipeline to use this option to automate the validation test
> add vm name option to validator

- pkg/bpf/exporter.go
Previously only a `MapSize` (lesser than size of processes) of entries used to be copied from processes bpf map. The right use of a batch size less than the size of map is as follows:
Ref: https://lwn.net/Articles/797808/
```
p_key = NULL;
p_next_key = &key;
while (true) {
err = bpf_map_lookup_batch(fd, p_key, &p_next_key, keys, values,
&batch_size, elem_flags, flags);
if (err) ...
if (p_next_key) break; // done
if (!p_key) p_key = p_next_key;
}
```
This PR fixes the issue by creating a entries byte array with the same size as the `processes` map.
Additionally, this commit makes use of `bytes.Reader` instead of bytes.Buffer to avoid unnecessary copy of ephemeral byte array.
> fix: ensure all entries from bpf map are copied

- pkg/bpf/types.go
fix the process parameter order to match the c and go code
> bpf: fix the process parameter order to match the c and go code

- e2e/tools/validator/src/validator/cases/__init__.py
- e2e/tools/validator/src/validator/cli/__init__.py
- e2e/tools/validator/tests/validator/cases/test_cases.py
- e2e/tools/validator/tests/validator/prometheus/test_prometheus.py
- e2e/tools/validator/tests/validator/stresser/test_stresser.py
I included basic pytest test cases for pure methods used for producing error metrics from prometheus response data, cleaning data from prometheus response data, and generating prom queries for validation. I will also include basic test cases for stresser related methods like for connecting to vm, copying files to vm, and running the scripts for vm.
The purpose of these test cases are to ensure the code made during PRs do not break the functionality of the validator.
> Add Test Cases for Prometheus, Config, Stresser for Validator

- pkg/collector/stats/stats.go
update the verbosity of annoying key error message due to missing gpu metrics
> stats: update the verbosity of anoying key error message

- manifests/compose/compose.yaml
- manifests/compose/dev/compose.yaml
- manifests/compose/mock-acpi/compose.yaml
- manifests/compose/validation/metal/compose.yaml
- manifests/compose/validation/vm/compose.yaml
This disables usage of cgroups while running Kepler using compose
> chore(compose): disable cgroup in compose

- e2e/tools/validator/query.json
- e2e/tools/validator/src/validator/cases/__init__.py
- e2e/tools/validator/src/validator/cli/__init__.py
- e2e/tools/validator/src/validator/prometheus/__init__.py
Instead of using two separate queries which the validator will use to calculate the error metrics, replace with a single promql query which will calculate and return the error metric to the validator. Please give this a try @rootfs. Note if an error occurs, it's most likely because the "/" symbol in the promql query results in an empty query.
> Replace expected and actual query with single query

- e2e/tools/validator/README.md
- e2e/tools/validator/query.json
- e2e/tools/validator/src/validator/cases/__init__.py
- e2e/tools/validator/src/validator/cli/__init__.py
- e2e/tools/validator/src/validator/config/__init__.py
- e2e/tools/validator/src/validator/specs/__init__.py
- e2e/tools/validator/validator.yaml
- e2e/tools/validator/validator.yaml.sample
This is the sample report
| Model | Cores | Threads | Sockets | Flags |
|-----------|-----------|-------------|-------------|-----------|
| Intel(R) Xeon(R) E-2278G CPU @ 3.40GHz | 16 | 2 | 1 | ```fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed …
```
> chore(validator) report validator results

- .github/workflows/integration_test.yml
- bpfassets/libbpf/src/kepler.bpf.c
- bpfassets/libbpf/src/kepler.bpf.h
- pkg/bpf/bpf_suite_test.go
- pkg/bpf/exporter.go
- pkg/bpf/test_utils.go
- pkg/bpf/types.go
- pkg/collector/resourceutilization/bpf/process_bpf_collector.go
- pkg/config/types.go
- pkg/metrics/utils/utils.go
As stated in PR #1468, the ebpf metric collection is not correct.
This PR is fixing multiple problems:
- Fixed incorrect padding in some structures to ensure it is 8 bytes (unsigned long long).
- Updated the schedule switch to collect only on-CPU time and ignore idle time. As detailed [here](https://litux.nl/mirror/kerneldevelopment/0672327201/ch03lev1sec1.html), during a schedule switch, the previous task might not have been in the running state. Inspired by the libbpf-tools [cpudist](https://github.com/iovisor/bcc/blob/c93a19aaf3f7eae9d6c9070309cc785c18575767/libbpf-tools/cpudist.bpf.c#L100), I modified the code to save data only if the task was previously running, thereby excluding idle or blocked times. Collecting data from a non-running task could lead to gathering hardware counters …
> Fix bug in the ebpf metric collection

- cmd/exporter/exporter.go
- cmd/validator/validator.go
- pkg/collector/energy/node_energy_collector.go
- pkg/collector/metric_collector.go
Some small fixes while investigating #1467:
- In `cmd/validator` adds to the `wg` before it's passed into another function. `updateNodePower` is then run as `go updateNodePower`
- Consistently initilize wg's as `wg := &sync.WaitGroup{}`
- Call `go c.updateNodeResourceUtilizationMetrics(wg)` and `go c.updateProcessResourceUtilizationMetrics(wg)` in their own goroutines. Otherwise the use of a wg is pointless since they would be run sequentially
- Allows for Kepler to gracefully shutdown when a SIGINT or SIGTERM is received
> Fix use of goroutines and implement graceful shutdown

- bpfassets/libbpf/src/kepler.bpf.h
Process metrics was missing `command` label (command="") because of the `pad` that got added to the bpf process_metrics_t in #1481. The command label was empty because the go `ProcessBPFMetrics` struct is 
missing `Pad` 
Fixes #1519
> fix(bpf): restore command label in process metrics

- .github/workflows/unit_test.yml
- README.md
This removes the current infra for updating the code coverage badge which calculates a percentage and checks in a commit to update the README.
It's replaced with CodeCov, a web service that will provide an always-up-to-date link to a coverage badge, as well as allowing users to dig into coverage reports through a web UI.
This avoids flooding the git history with commits that update the coverage badge. For example, the SHA of the latest git commit and the SHA used to build the `latest` container image aren't the same because of the coverage commit.
Similary, we miss seeing information about the last merge commit (and a CI status indicator) on the front page on GitHub.
> chore: Use Codecov

- .github/workflows/image.yml
Before this change, the `kepler_exporter_build_info` metric would report that the current version is `latest`. This makes it difficult to understand precisely which version of Kepler is running.
If we don't override this at image build time, then the version will be reported as something like v0.7.10-91-g95dce23a
This more accurately identifies which version of kepler is in use.
> ci: Don't override binary version in image builds

- .github/workflows/push.yml
- .github/workflows/unit_test.yml
It looks like secrets don't propagate automatically when using workflow_call so we have to explicitly set them.
Hopefully this should fix codecov uploads from main.
> ci: Fix codecov secret propagation

- .github/dependabot.yml
This ignore dependabot updates for dependencies that should only be manually bumped.
> ci: Ignore dependabot updates for some deps

- bpfassets/libbpf/src/kepler.bpf.c
The processes map keys are kernel tgids.
This corrects the code in the softirq and pache cache functions to lookup using the tgid.
> fix(bpf): Fix map lookup for IRQ/Page Cache

- Makefile
Cleanup includes:
* using ubi-9-libbpf-1.3.0 image instead of old 1.2.0 image
* break long commands into multiple lines
* remove unused vars - DEBUG, GO_LD_FLAGS, GC_FLAGS
> chore: cleanup Makefile

- .github/dependabot.yml
K8s client-go, apimachinery and api updates to 1.30 require a Go bump to version 1.22. We can't do this yet since we're blocked on needing a Go 1.22 toolset in UBI. Ignore major/minor semver bumps to these packages for now. We can revert this when we're on Go 1.22
> ci: Ignore K8s major/minor dep updates

- bpfassets/libbpf/include/bpf/bpf_core_read.h
- bpfassets/libbpf/src/kepler.bpf.c
- bpfassets/libbpf/src/kepler.bpf.h
- hack/libbpf-headers.sh
In older kernels prev_state isn't passed as part of the context of the
function. Therefore it's better to access prev_task-->_state directly.
The field was renamed from state to __state in Kernel 5.14.
Given that we need to support Kernel 5.12+ we include the
bpf_core_read.h file such that we can use the bpf_core_field_exists
function that allows us to see which field is present in task struct
and return the correct value.
> fix(bpf): Access __state from task_struct

- bpfassets/libbpf/src/kepler.bpf.c
- pkg/bpf/exporter.go
We need to use a standard tracepoint for kepler_write_page_cache to
avoid BTF relocation errors on systems where the writeback_dirty_folio
tracepoint doesn't exist.
This is due to the rename of writeback_dirty_page to
writeback_dirty_folio that happened in Kernel 5.16.
This patch adjust the attach logic to fall back to the old name if the
writeback_dirty_folio tracepoint does not exist.
> fix(bpf): Fix kepler_write_page_cache attach

- hack/build-manifest.sh
- manifests/k8s/config/base/kustomization.yaml
- manifests/k8s/config/exporter/kustomization.yaml
- manifests/k8s/config/model-server/kustomization.yaml
- manifests/k8s/config/rbac/kustomization.yaml
When we formatted the code with yamllint it was not immediately clear that we had a shell script that was performing uncommenting of lines.
When done by a human, their IDE (or eyes) would see that the indentation didn't align and would adjust. This is not clear to machines, for example when performing `make build-manifests`
This commit adds spaces to commented YAML lines in any kustomization.yaml to ensure that once the leading '#` has been removed that they are correctly indented.
In addition the uncomment() function in hack/build-manifests.sh has been adjusted to preserve any spaces that occur after the leading `#`
> fix: Fix uncomment of YAML in hack/build-manifests.sh

- .github/workflows/image.yml
- Makefile
- build/Dockerfile
This PR:
* fixes the issue the VERSION variable assignment
from `?=` to `:=` to ensure immediate evaluation of `$(GIT_VERSION)`
* Use `fetch_depth` to fetch the tag info for computing the `GIT_VERSION`
correctly while building Kepler images
* Removes the `VERSION` argument from the Dockerfile
* Removes the redundant bpftool COPY statement in build/Dockerfile
* Addresses issue #1540
> fix: update the VERSION variable assignment method

- manifests/compose/dev/compose.yaml
- manifests/compose/mock-acpi/compose.yaml
- manifests/compose/validation/metal/compose.yaml
Removes the `VERSION` build-arg from the docker compose files as it was removed in #1552
> chore: remove version from docker-compose

- manifests/k8s/config/exporter/kustomization.yaml
This fixes the broken `make build-manifest OPTS="OPENSHIFT_DEPLOY"` which does not correctly uncomment openshift_scc.yaml
> fix(manifest): uncomment openshift SCC

- e2e/tools/validator/pyproject.toml
- e2e/tools/validator/src/validator/prometheus/__init__.py
- e2e/tools/validator/src/validator/specs/__init__.py
- e2e/tools/validator/tests/validator/prometheus/test_prometheus.py
This pr fixes most of the issue raised by `hatch run types:check` 
It also 
* improves the coverage of both mse and mape functions which are modifies as a result of typings fix.
* sets python version to 3.11
> chore(validator): fix typings and python version

- pkg/collector/stats/utils.go
This commit fixes the issue of having to copy cpus.yaml to /var/lib/kepler (the hardcoded path for the cpus.yaml) by reading the cpus.yaml file relative to the project root.
Thus the following now works fine.
```
make build
sudo ./_output/bin/kepler
```
> fix: fallback to reading cpus.yaml relative to current dir

- Makefile
This PR removes an unnecessary `build-arg` from the Makefile targets used in building Kepler images
> chore(makefile): remove unused build-arg from Makefile for Kepler images

- bpfassets/libbpf/src/kepler.bpf.c
With the new task structure in the tracepoint in the code, we can now directly get the previous running task tgid, so that we can remove the map to track and translate the pid to tgid.
> Remove tgid map

- manifests/compose/README.md
Adds `README.md` inside `manifests/compose` explaining different compose environments are and how to set them up
> feat(compose): add README for compose

- .github/workflows/pull_request.yml
- .github/workflows/validator.yml
- e2e/tools/validator/Makefile
This PR introduces a workflow to execute validator tests on CI Additionally, it includes a Makefile within `e2e/tools/validator`, enabling the execution of targets such as `make fmt` and `make test` for local testing
> feat(validator): Add workflow for validator tests

- e2e/tools/validator/src/validator/cli/__init__.py
- e2e/tools/validator/src/validator/prometheus/__init__.py
- e2e/tools/validator/tests/validator/prometheus/test_prometheus.py
Previously, the validator script would crash and not generate a report if an expection was thrown during validation. This commit fixes it by catching all exceptions and reporting it.
See: https://github.com/sustainable-computing-io/kepler-metal-ci/actions/runs/9768844108/job/26967214547 for failure
> chore(validator): handle exceptions raised during validation

- bpfassets/libbpf/src/kepler.bpf.c
- bpfassets/libbpf/src/kepler.bpf.h
The process state can have multiple states, running state is one of them, yet most of the user space processes are spending CPU on interruptible state. 
The process can voluntarily changes its state fro running to interruptible, so by the time the sched_switch tracepoint enters, the state may not be in running.
> chore(bpf): account all running state processes

- pkg/collector/resourceutilization/bpf/process_bpf_collector.go
- pkg/metrics/utils/utils.go
The bad MAPE results in latest code (as in contrast to 0.7.8) is related to the inconsistent usage of cpu time. The models trained using early 0.7 code uses [microsecond cpu time ](https://github.com/sustainable-computing-io/kepler/blob/release-0.7.8/bpfassets/libbpf/src/kepler.bpf.c#L68). #1481  [changed it](https://github.com/sustainable-computing-io/kepler/pull/1481/files#diff-0916c401e16b7d26ca96720a88f24fe4fa5117113d56e05b85b515c9b23cea73R109) and compensated the delta at metrics reporting time. This causes the model to use wrong CPU time.
I tested the fix on my env:
After the change:
```
kepler_node_core_joules_total{instance="rhel",mode="dynamic",package="0",source="trained_power_model"} 87.354
kepler_node_core_joules_total{instance="rhel",mode="idle",package="0",source="trained_pow …
```
> chore(collector): convert cpu time in collection time instead of metrics reporting time to avoid inconsistent use of cpu time in models

- .github/workflows/pull_request.yml
- .github/workflows/validator.yml
- e2e/tools/validator/Makefile
This commit changes the validator workflow to trigger when changes are made inside `e2e/tools/validator` directory. Additionally, `make test` target is updated to use `hatch run test -v -s`
Also address #1544
> feat(validator): trigger validator workflow on changes

- pkg/config/config.go
- pkg/metrics/container/metrics.go
- pkg/metrics/process/metrics.go
- pkg/metrics/utils/utils.go
- vendor/github.com/jaypipes/ghw/Dockerfile
fix #1486 
When disabling component power and bpf metrics (i.e. `EXPOSE_COMPONENT_POWER="false" EXPOSE_BPF_METRICS="false" `), the number of metrics is reduced to 5% of what is before.
> feat(metrics): selectively expose prom metrics to reduce overhead

- .github/workflows/commitMsg.yml
This commit updates the existing `commitMsg.yml` workflow to enforce the use of conventional commit messages. It makes use of the [webiny/action-conventional-commits](https://github.com/webiny/action-conventional-commits) action to check the commit message and fail the workflow if it does not adhere to the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0-beta.2/) message format.
Address #1502
> feat(ci): update workflow to enforce conventional commit message

- .golangci.yml
- pkg/collector/metric_collector.go
- pkg/collector/stats/node_stats.go
- pkg/collector/stats/node_stats_test.go
- pkg/collector/stats/stats.go
- pkg/collector/stats/types/benchmark_test.go
- pkg/collector/stats/types/types.go
- pkg/collector/stats/types/types_test.go
- pkg/kubernetes/watcher.go
- pkg/manager/manager.go
- pkg/metrics/prometheus_collector.go
- pkg/metrics/utils/utils.go
- pkg/model/estimator/local/ratio_model_test.go
- pkg/model/process_energy_test.go
This commit fixes a couple of small issues.
Firstly, in Go maps are reference types (like pointers) so
using *map[string]any for example isn't required.
Secondly, this removes the structure that backs
Uint64StatCollection and replaces it with a map.
Doing so make the code much easier to read (IMHO).
Finally, operations in Uint64Stat have been made
atomic to ensure correct operation if methods are
called from different threads. A test has been added
to verify this behaviour - this test fails when
run against the main branch.
There are some additional small fixes to address lint issues
that appear to have eluded our CI. Firstly the `dupl` threshold
has been moved to 150 to stop it complaining about Gingko-style
tests (which are very similar). Secondly the YAML for the `shadow`
has been …
> chore: Flatten Uint64StatCollection

- .golangci.yml
This fixes the configuration to enable the go vet shadowing checks. It deliberately ignores the shadowing of err or ctx variables given this is a pattern that is widely used in Go code.
> ci: Fix go lint config

- .github/dependabot.yml
This is supposed to check for updates weekly on a monday, not every day.
> ci: Set gomod dependabot to weekly

- manifests/compose/dev/compose.yaml
- manifests/compose/dev/grafana/dashboards/dev/dashboard.json
- manifests/compose/dev/override.yaml
- manifests/compose/dev/prometheus/scrape-configs/dev.yaml
This commit adds scaphandre to the dev compose so that power predication can be compared against it. Additionally grafana dashboards is updated to compare `process_package` power against scaphandre's process power consumption.
> chore(compose): add scaphandre to dev compose

- .github/workflows/developer_local.yml
- .github/workflows/integration_test.yml
- .github/workflows/platform-validation.yml
- Makefile
A few fixes to more easily run Kepler in a KIND cluster when running make on a macOS system:
- Consistently indent using tabs
- Check for the presence of ldconfig to avoid errors
- export variables required by the cluster-* scripts
- deploy the serivcemonitors for prometheus by default
> fix: Makefile for running on macOS

- manifests/compose/monitoring/compose.yaml
This commit allows grafana to be accessed without logging in as admin user. It also solves the nagging change password issue.
> chore(compose/grafana): allow anonymous login with admin role

- e2e/tools/validator/acpi_validations.yaml
- e2e/tools/validator/src/validator/cli/__init__.py
- e2e/tools/validator/src/validator/cli/options.py
- e2e/tools/validator/src/validator/specs/__init__.py
- e2e/tools/validator/validator.mock-acpi.yaml
- manifests/compose/mock-acpi/grafana/dashboards/mock-acpi/dashboard.json
Updated validator to validate mock-acpi
Added MSE/MAPE for mock-acpi dashboard
Sample report:
```
* Generating validate acpi report file and dir
report: /tmp/report-v0.7.10-192-ge30ed57c.md
results dir: /tmp/validator-v0.7.10-192-ge30ed57c
* Build Info
- kepler_exporter_build_info{goarch="amd64", goos="linux", goversion="go1.20.12", instance="kepler-latest:8888", job="latest", revision="unknown", tags="include_gcs,include_oss,containers_image_openpgp,gssapi,providerless,netgo,osusergo,libbpf,linux,gpu"}
- kepler_exporter_build_info{arch="amd64", branch="validate-mock-acpi", instance="kepler-dev:8888", job="dev", os="linux", revision="4b426d675ecb300c2e5cd1d220c419d22532e34f", version="v0.7.10-191-g4b426d67-dirty"}
* Generating spec report ...
* Generating validation report
- started at: …
```
> feat: Add mock-acpi validation to validator

- .github/workflows/image.yml
Added image signing to workflow using cosign.  Signs images with GitHub OIDC token, and permissions updated and restricted to reflect this.
This is a re-created PR due to previous difficulty with rebasing changes on main.  I hope this fixes the issue!
> ci: sign image builds (fixing security issue)

- cmd/exporter/exporter.go
- pkg/config/config.go
- pkg/manager/manager.go
Do some tidy up to `cmd/exporter` so that related sections are kept together and the configuration is uniform for all config args.
> chore: tidy Exporter startup

- manifests/compose/validation/metal/grafana/dashboards/scaphandre/scaphandre-dashboard.json
This commit fixes the formatting of the scaphandre dashboard json in order to make grafana render the dashboard correctly
> fix(compose): correct formatting for scaphandre dashboard json

- build/Dockerfile
- build/Dockerfile.builder
- build/Dockerfile.kepler-validator
This commit ensures that the FROM instruction in the Dockerfile is correctly formatted with consistent casing.
The casing is now consistent with the standard `FROM AS` syntax
> chore(Dockerfile): fix From instruction casing in Dockerfile

- Makefile
Fill in missing Makefile help entries with brief descriptions, so all available make options are obvious.  Also created 'testing' section so users can run single testing tools if desired.
> add missing info to Makefile help

- e2e/tools/validator/src/validator/cli/__init__.py
This commit corrected the issue where the validator was causing an unbound error while reporting the results.
> fix(validator): resolve the unbound error

- pkg/comm/resolve_comm.go
The resolves pid 0 to system_processes without (throwing) any error since there is no command associated with it. This commit fixes the following log
```
I0802 03:24:03.647656  733341 process_bpf_collector.go:100] failed to resolve comm for PID 0: process not running: stat /proc/0: no such file or directory, set comm=system_processes
I0802 03:24:03.648079  733341 process_bpf_collector.go:100] failed to resolve comm for PID 0: process not running, set comm=system_processes
I0802 03:24:03.648108  733341 process_bpf_collector.go:100] failed to resolve comm for PID 0: process not running, set comm=system_processes
```
> fix: resolve pid 0 to system_processes

- cmd/exporter/exporter.go
- pkg/bpf/exporter.go
- pkg/bpf/test_utils.go
- pkg/bpf/types.go
Processing events in the same goroutine as the ring buffer reader requires acquiring a mutex, which blocks ringbuf event processing causing a backlog. To avoid this, send events via a buffered channel to a dedicated event processing goroutine to ensure that the ringbuf remains unblocked. This has decreased CPU load from 1-3% on my machine to 0-1% CPU load.
Additionally adds some metrics to track events read, events processed and the current depth of the events channel.
Updates: #1670, #1660
> fix(pkg/bpf): Use channel to process events

- bpf/kepler.bpf.h
In release 7.11 `bpf_get_current_pid_tgid()` was used to get the `tgid` to register new process, which refers to the task being switched out. reverting it back to same behavior using `prev_tgid`.
> fix(bpf): use prev_tgid to register process

- bpf/kepler.bpf.h
Update the register counters one step before metrics sample is taken
instead of updating registers every time which is increasing overhead
- with `EXPERIMENTAL_BPF_SAMPLE_RATE = 0`
```
[root@vimalkum-thinkpadp1gen4i ~]# bpftool prog show name kepler_sched_switch_trace | head -n 1 | awk '{print "rt_ns:", $(NF-2), "count: ", $NF, "avg: ", $(NF-2)/$NF } '
rt_ns: 301913885 count:  95144 avg:  3173.23
[root@vimalkum-thinkpadp1gen4i ~]# bpftool prog show name kepler_sched_switch_trace | head -n 1 | awk '{print "rt_ns:", $(NF-2), "count: ", $NF, "avg: ", $(NF-2)/$NF } '
rt_ns: 212656178 count:  68417 avg:  3108.24
```
- with `EXPERIMENTAL_BPF_SAMPLE_RATE = 1000`
```
[root@vimalkum-thinkpadp1gen4i ~]# bpftool prog show name kepler_sched_switch_trace | head -n 1 | awk '{print "rt_ns:", $(NF-2), …
```
> fix(bpf): Fix overhead when sampling

- pkg/model/estimator/local/regressor/model_weights.go
- pkg/model/estimator/local/regressor/regressor.go
- pkg/model/estimator/local/regressor/regressor_test.go
- pkg/sensors/platform/source/redfish.go
For updating model selection logic, I would like to add more information on the model weight file started with the model_name in PR https://github.com/sustainable-computing-io/kepler-model-server/pull/370. 
This PR update the ComponentModelWeights in Kepler in order to unmarshal the new weight file. 
The new structure is also support the old version of weight file.
> feat: add model_name attribute to ComponentModelWeights

- pkg/model/estimator/local/regressor/model_weights.go
Fix formatting for previous PR.
Due to the change in https://github.com/sustainable-computing-io/kepler/pull/1699, the print format is replaced with object reference. 
```
I0819 06:05:57.796020    2574 regressor.go:91] Regression Model (AbsPower): getWeightFromServer: &{ <nil> 0xc0021fe060 0xc0021fe210 0xc0021fe180 0xc0021fe0f0} (error: <nil>)
```
This also affects the CI in kepler-model-server that checks for `core` word inside the weight log.
> fix: format ComponentModelWeights

- build/Dockerfile
- doc/dev/prepare_dev_env.sh
- manifests/compose/dev/compose.yaml
- manifests/compose/mock-acpi/compose.yaml
- manifests/compose/validation/metal/compose.yaml
- manifests/compose/validation/vm/compose.yaml
- packaging/rpm/kepler.spec
- pkg/config/config.go
This commit moves model_weights from/var/lib/kepler/data/ to its own directory - var/lib/kepler/data/model_weights/ this allows additional data like machine-spec to be stored its own directory.
Additionally this change fixes the blank cpu.yaml that gets created when running compose files. Previously the VM compose  used to blank `cpu.yaml` file instead of the one in `data/`
> chore: move model_weights to its own directory

- Makefile
- cmd/exporter/exporter.go
- pkg/build/build.go
Cleanup global variables in cmd/exporter
> chore: cleanup globals in exporter

- pkg/model/model.go
This PR removes the fixed default trainer name unexpectedly applied to also estimator. 
For local regressor, we need the default trainer name pointed to linear function. 
https://github.com/sustainable-computing-io/kepler/blob/d143b6731fad3f0a44e7b4277cf8aa66a9ebeb84/pkg/model/estimator/local/regressor/regressor.go#L249-L263
However, we shouldn't pass this default trainer to sidecar estimator. 
This causes the mismatch issue in https://github.com/sustainable-computing-io/kepler-model-server/pull/383.
This PR moves the logic to set default trainer to the point before creating the local regressor estimator.
> fix: set default trainer only for local regressor

- .github/workflows/mock_acpi.yml
This commit resolves two key issues with the mock-acpi workflow:
- Checkout correct branch: The workflow previously checkout out the default branch when triggered by a pull request. This fix ensures that the correct pull request branch is checked out during CI run.
- Attach workflow to pull request checks: The workflow was not being reflected under pull request checks. With this fix, the workflow will be correctly attached, ensuring its status visible and reported under pull request checks.
Also addresses: #1709
> fix(ci): ensure proper status reporting for mock-acpi workflow

- cmd/exporter/exporter.go
This PR adds an option to set power support to false to forcefully use estimator to estimate the node power regardless of power meter installation.
> feat: add --disable-power-meter option

- .github/workflows/mock_acpi.yml
This commit addresses an issue where the `cleanup` and `final status` jobs were incorrectly dependent on the `create-runner` job, leading to their premature execution. This fix ensures that both `cleanup` and `final status` job run independently and only after all necessary preceding jobs have finished
> fix(ci): ensure independent execution of cleanup and status jobs

- .github/workflows/mock_acpi.yml
This commit addresses the issue of multiple jobs defined in the `mock-acpi` workflow, which were unintentionally executing in parallel due to sequence constraints. By consolidating the workflow into a single job, we ensure that the tasks are executed sequentially
> fix(ci): consolidate mock-acpi workflow into single job

- manifests/compose/validation/vm/compose.yaml
- manifests/compose/validation/vm/kepler/etc/kepler/kepler.config/MODEL_CONFIG
- manifests/compose/validation/vm/kepler/etc/kepler/kepler.config/MODEL_SERVER_ENABLE
Updates:
* kepler_model_server to 0.7.11-2.
* Models to 0.7.11 SGDRegressor
* Adds DISABLE_POWER_METER env to disable power meters when running vm compose on a BM (just in case)
* sets MODEL_SERVER_ENABLE to false to force using estimator
> chore(compose): bumpup model-server to v0.7.11-2

- .github/workflows/image.yml
- .github/workflows/image_base.yml
- .github/workflows/image_pr.yml
This builds on previous commit `9d567e5` to add cryptographic signing to two additional workflows: `image_pr.yml` and `image_base.yml`.  This resolves the issue with images only being intermittently signed.  It also reduces the scope of privileges on `image.yml` to only what is necessary for the OIDC token to be used.
> ci: sign all image builds

- manifests/compose/default/override.yaml
- manifests/compose/dev/compose.yaml
- manifests/compose/dev/prometheus/scrape-configs/dev.yaml
node-exporter provides rapl power metrics
- node_rapl_core_joules_total
- node_rapl_uncore_joules_total
- node_rapl_package_joules_total
- node_rapl_psys_joules_total
removed unwanted dependency on kepler-latest in default override.yaml
> feat(compose): add node-exporter for rapl metrics

- .github/workflows/mock_acpi.yml
This commit bumps the metal runner action version to v0.3.0 It now supports the [self-hosted runners at organization level](https://github.com/equinix-labs/metal-runner-action/releases/tag/v0.3.0)
> chore(ci): bump metal runner action version

- .github/workflows/mock_acpi.yml
This commit addresses an issue where the codebase was not being checked out before initiating the runner and setting up the test environment
> fix(ci): checkout code base earlier

- e2e/tools/validator/scripts/stressor.sh
This commit enhances the stress-ng command by adding the `ackermann` method for CPU stress testing
> chore(validator): add cpu method to stress-ng

- .github/workflows/mock_acpi.yml
This commit addresses a checkout action failure occurring in the pull request from forked repos. The issue stemmed from the use of `ref`. Switching to `sha` resolves this
Ref: https://github.com/sustainable-computing-io/kepler/actions/runs/10558274696/job/29247409471#step:5:59
> fix(ci): use SHA for checkout

- .github/workflows/mock_acpi.yml
This commit updates the mock-acpi workflow to use the custom `metal-runner-action` instead of the `equinix-labs`. This change is necessary because the workflow does not expose the `github.organization` value when triggered by the `issue_comment` event
Ref: https://github.com/sustainable-computing-io/kepler/actions/runs/10572316346/job/29289799353#step:6:14
> fix(ci): switch to custom metal-runner-action in mock-acpi workflow

- pkg/model/model_test.go
- pkg/model/utils/utils.go
This is a fix to avoid core ratio > 1 (trained machine is smaller than the target machine itself). 
Idle power should not affect DynEnergy.
https://github.com/sustainable-computing-io/kepler/blob/777c733dfc4a696c17d06494fa7d783e4b3af6e5/pkg/collector/stats/stats.go#L140
> fix: limit max core ratio to 1

- pkg/model/model.go
- pkg/model/node_component_energy.go
- pkg/model/node_platform_energy.go
This PR includes 
* fixing the typo `Powe` -> `Power`
* reorganise the functions to exit early and log errors and info
Tested locally using dev compose files 
---
> chore: fix model creation functions

- pkg/config/config_test.go
- pkg/config/spec.go
- pkg/model/estimator/local/regressor/model_weights.go
- pkg/model/estimator/local/regressor/regressor.go
- pkg/model/estimator/local/regressor/regressor_test.go
- pkg/model/model.go
This PR implement TODO addressed in https://github.com/sustainable-computing-io/kepler/pull/1732 by computing core ratio based on model machine spec and discovered spec (e.g., VM cores).
> feat: compute core ratio for local regressor

- pkg/model/estimator/local/regressor/exponential.go
- pkg/model/estimator/local/regressor/linear.go
- pkg/model/estimator/local/regressor/logarithm.go
- pkg/model/estimator/local/regressor/logistic.go
- pkg/model/estimator/local/regressor/regressor.go
The PR modifies the models/regressor 
* to add a `name` method to predictor so the name of of the predictor can be used in logs or elsewhere
* adds predictor name to the error returned
> fix(models): log name of regressor

- data/model_weight/acpi_AbsPowerModel.json
- data/model_weight/acpi_DynPowerModel.json
- data/model_weight/intel_rapl_AbsPowerModel.json
- data/model_weight/intel_rapl_DynPowerModel.json
- pkg/model/node_component_energy.go
- pkg/model/node_platform_energy.go
- pkg/model/types/types.go
- pkg/sensors/components/power.go
- pkg/sensors/platform/power.go
NOTE: `intel_rapl_DynPower` has not been updated since 
SGDRegressor for Dynamic Power Node Type 0 is missing  https://github.com/sustainable-computing-io/kepler-model-db/tree/main/models/v0.7/ec2-0.7.11/rapl-sysfs/DynPower/BPFOnly 
After updating the models to the latest, here are the changes on **my** machine 
```
kepler_node_info{components_power_source="rapl-sysfs", cpu_architecture="Skylake", instance="kepler-latest:8888", job="latest", platform_power_source="none", source="os"} | 1
-- | --
kepler_node_info{components_power_source="estimator", cpu_architecture="Skylake", instance="kepler-dev:8888", job="dev", platform_power_source="none", source="os"}
```
NOTE: `kepler-latest` reports power_sources incorrectly (fixed in this pr; see "dev") 
* seems like an improvement 
* Idle power …
> feat: update static models to use 0.7.11 models

- e2e/tools/validator/src/validator/cli/__init__.py
Saves all json dumps under `artifacts` and `images` under images dir.
> chore(validator): save artifacts and images in separate dirs

- build/Dockerfile
This commit resolves an issue where the habanalabs installation step was unnecessary repeated multiple times in the Dockerfile.
> fix(dockerfile): remove redundant habanalabs installation steps

- data/model_weight/intel_rapl_DynPowerModel.json
As mentioned in https://github.com/sustainable-computing-io/kepler/issues/1748#issuecomment-2319703608, this PR adds the default power model for DynPower for rapl-sysfs but with the remark of high training MAE against linear regressor.
> chore: update intel_rapl_DynPowerModel from ec2-0.7.11

- .github/workflows/mock_acpi.yml
This commit restructures the Mock ACPI workflow by splitting into multiple jobs. New workflow structure:
- Initilize workflow: Fetches the PR branch, sets the initial job status to pending.
- Test Mock ACPI: Check out the PR code base, uses Mock ACPI compose to setup Kepler, and runs validator.
- Cleanup: Removes the Equinix runner and update the final job status based on the outcomes of the previous jobs.
> fix(ci): Split Mock ACPI workflow into multiple jobs

- .github/workflows/mock_acpi.yml
This commit moves the creation of runner to a different job so that the follow-up job can use the self-hosted runner
> fix(ci): move creation of runner into a different job

- build/Dockerfile
This commit removes the ARG `INSTALL_HABANA` from the builder stage of the Dockerfile as it is already defined in the final image stage
> chore(dockerfile): remove the arg from the builder stage

- e2e/tools/validator/src/validator/cli/__init__.py
This fixes the graphs that were flipped leading to confusion in how MAPE is calculated!
See: https://github.com/sustainable-computing-io/kepler-metal-ci/blob/main/docs/train-validate-e2e/2024-09-05_02-22-45/AbsPower/BPFOnly/SGDRegressorTrainer/report-v0.7.11-196-g6a76bc35.md#platform---dynamic 
The graph should have caused MAPE to be 100% where as the MAPE is `inf`  as the [dynamic data](https://github.com/sustainable-computing-io/kepler-metal-ci/blob/main/docs/train-validate-e2e/2024-09-05_02-22-45/AbsPower/BPFOnly/SGDRegressorTrainer/artifacts/kepler_vm_platform_joules_total--dynamic.json) is all 0
> chore(validator): fix graphs rendered incorrectly

- .github/workflows/mock_acpi.yml
This commit updates the equinix metal actions used in the workflow to point to use the forked version maintained under `sustainable-computing-io` organization.
Addresses #1739
> chore(ci): update equinix metal actions to point to org fork

- e2e/tools/validator/acpi_validations.yaml
- e2e/tools/validator/src/validator/cli/__init__.py
- e2e/tools/validator/src/validator/prometheus/__init__.py
- e2e/tools/validator/src/validator/validations/__init__.py
- e2e/tools/validator/tests/validator/prometheus/test_prometheus.py
- e2e/tools/validator/validations.yaml
This PR introduces the following changes to validator 
* Use `predicted` instead of `expected` terminology to align with MAPE and MSE teminology
* Add ability map `actual` and `predicted` in validations. This allwos for 
```
config:
mapping:
actual: metal
predicted: vm
validations:
- metal: <metal-query>
vm: <vm-query>
```
* Generated reports and artifacts now make use of these label
* Add support for Units
> chore(validator): support validation config to map actual and predicted

- e2e/tools/validator/src/validator/cli/__init__.py
- e2e/tools/validator/src/validator/validations/__init__.py
- e2e/tools/validator/validations.yaml
This commit includes the following changes:
* adds the ability to override global config in validations with local mapping.
* adds kepler-package vs node-rapl comparison
* modifies MD report to now include clickable links to the json files
See sample run here - https://github.com/sthaha/kepler-validation-reports/blob/main/validator-v0.7.11-213-gc75a4e2f/report-v0.7.11-213-gc75a4e2f.md
> chore(validator): compare node-rapl and kepler-package

- e2e/tools/validator/validations.yaml
This commit updates the bpf cpu time query to use `level` as identifier instead of `vm` in case of metal and `process` in case of vm.
> fix(validator): update the bpf cpu time query

- .github/workflows/mock_acpi.yml
This commit fixes the issue where the cleanup job from the mock_acpi workflow was running on any comment to issue or PR. Ideally, it should only run how other jobs in the workflow gets triggered.
> fix(ci): run cleanup only on pull requests

- .dockerignore
This commit removes e2e from dockerignore file as it is required while building the test image for running the e2e tests downstream Ref: https://github.com/openshift-power-monitoring/kepler/blob/main/e2e/Dockerfile
> chore(git): remove e2e from dockerignore

- build/Dockerfile
- pkg/config/config.go
- pkg/sensors/accelerator/device/sources/dcgm.go
https://github.com/sustainable-computing-io/kepler/commit/aa66ada360ba6d8348f231a458040b60a69733a2 broke the habana-latest Kepler image. 
I also noticed that the dcgm-latest wouldn't work from the builder stage: https://github.com/sustainable-computing-io/kepler/actions/runs/10880954177/job/30191354022#step:7:1066
As Kepler relies on build tags for the gpu code the libraries need to be installed at the builder stage as well as the final image stage
This fixes issue https://github.com/sustainable-computing-io/kepler/issues/1783 . However I will remove the dcgm/nvml tag dependency in: https://github.com/sustainable-computing-io/kepler/pull/1704 as I added building in all the dcgm/nvml gpu code into kepler by default there. Habana is problematic and can't follow the same solution (re …
> fixes: aa66ada adding the needed libraries to the builder stage

- pkg/collector/resourceutilization/bpf/process_bpf_collector.go
- Removed check for mandatory `CacheMiss` and `PageCacheHit` before creating bpf metric
- Added `ProcessRunTime` in the bpf collector log
In a VM where `hostPassThrough` is disabled, we will not get `cpu_cycles`, `cpu_instructions`, `cache_miss`, these values are always 0.
So as per the resource usage check, only when there is a page cache hit, bpf metrics will be created.
we can see the same in the logs.
I executed stress-ng in the VM, and checked for `docker compose logs kepler | grep process_bpf_ | grep -i stress`
we can see that every so often there is a page cache hit n stress-ng, perhaps it tries to read something, and we get a bpf cpu time metric.
```sh
kepler-1  | I0919 23:35:46.597731    2844 process_bpf_collector.go:93] process stress-ng-cpu (pid=4023, cgroup=8982) has 873929 …
```
> fix(metrics): Remove resource usage check for skipping bpf metrics

- manifests/compose/dev/compose.yaml
- manifests/compose/dev/override.yaml
- manifests/compose/dev/prometheus/scrape-configs/dev.yaml
- manifests/compose/validation/metal/compose.yaml
- manifests/compose/validation/metal/override.yaml
- manifests/compose/validation/metal/prometheus/scrape-configs/metal.yaml
Added a prometheus exporter for libvirt to `metal` and `dev` compose
```
sum(rate(libvirt_domain_vcpu_time_seconds_total{domain="fedora40"}[20s]))
```
```
rate(libvirt_domain_vcpu_delay_seconds_total{domain="fedora40"}[20s])
```
```
libvirt_domain_vcpu_wait_seconds_total{domain="fedora40"}
```
> chore(compose): Add libvirt-exporter

- .github/workflows/gosec.yml
Reverts sustainable-computing-io/kepler#1794
Submitted issue to: https://github.com/securego/gosec/issues/1234
> Revert "build(deps): bump securego/gosec from 2.20.0 to 2.21.3 in the github-actions group across 1 directory"

- bpf/kepler.bpf.h
currently `sched_switch_trace` takes timestamp at entry, and uses the same timestamp as prev timestamp for the next task. this makes process_run_time for next process to include the bpf processing time of prev process also.
to avoid this take another timestamp at the end of `sched_switch_trace` and save that as the starting timestamp for the next process.
> fix(bpf): exclude bpf overhead in bpf_cpu_time

- pkg/collector/resourceutilization/bpf/process_bpf_collector.go
-  fix command name in case of kernel processes
if the cgroupID for the pid is 1, it is considered as kernel process
and bpf cpu time for each such process is aggregated under the same  ProcessStat
But the command which shows up in metric is from the first pid which  created the entry in ProcessStats. It could be a `kworker`, or  `rcu_preempt`, or some other kernel process. Which is misleading because it shows that process consuming most of bpf cpu time.
This commit:
- uses "kernel_processes" as the command for pid 1 kernel processes
- sets the pid as 1 instead of the pid of the process that created the  entry
after change:
> fix(bpf_collector): fix command for kernel processes

- manifests/compose/monitoring/compose.yaml
This commit introduces the `--web.enable-admin-api` flag, allowing the Prometheus admin API to be enabled for capturing snapshots.
> feat(compose): enable admin API for prometheus snapshot

- .dockerignore
This commit removes the `.dockerignore` file from the repository. The current build process relies on `git describe` to compute the Kepler version. However, the `.dockerignore` file was causing certain Git-tracked files to be excluded from the Docker build context, leading to `dirty` version state. By removing the `.dockerignore` file, we ensure that all files are included, allowing Git to recognize a clean working directory during the image build process
Address: #1808
> fix: remove .dockerignore to ensure clean version computation

- cmd/exporter/exporter.go
- pkg/collector/energy/node_energy_collector.go
- pkg/collector/stats/stats.go
As discussed in the Oct 15 meeting, we make the idle power classification optional, until we have an idle power regression model that can predict idle power by system utilization.
> feat(metrics): refactor idle power exposure

- pkg/bpf/exporter.go
- pkg/bpf/test_utils.go
- pkg/collector/metric_collector.go
- pkg/collector/metric_collector_test.go
- pkg/collector/resourceutilization/accelerator/process_gpu_collector.go
- pkg/collector/resourceutilization/bpf/process_bpf_collector.go
- pkg/collector/stats/benchmark_test.go
- pkg/collector/stats/container_stats.go
- pkg/collector/stats/container_stats_test.go
- pkg/collector/stats/node_stats.go
- pkg/collector/stats/process_stats.go
- pkg/collector/stats/stats.go
- pkg/collector/stats/stats_test.go
- pkg/collector/stats/test_utils.go
- pkg/collector/stats/utils.go
- pkg/collector/stats/vm_stats.go
- pkg/collector/stats/vm_stats_test.go
- pkg/collector/utils.go
- pkg/config/config.go
- pkg/kubernetes/watcher.go
- pkg/metrics/prometheus_collector_test.go
- pkg/model/benchmark_test.go
- pkg/model/model.go
- pkg/model/process_energy.go
- pkg/model/process_energy_test.go
Tidy up the universal passing around of bpfSupportedMetrics for NewStats()
> chore: tidy use of bpfSupportedMetrics for NewStats()

- .pre-commit-config.yaml
- manifests/compose/validation/vm/kepler/etc/kepler/kepler.config/EXPOSE_ESTIMATED_IDLE_POWER_METRICS
This patch disables the idle power metrics produced when Kepler is run
on the VM
Additionally this, patch also updates the version of golangci-lint in pre-commit-config.yaml to fix the failing pre-commit check https://github.com/sustainable-computing-io/kepler/actions/runs/11435710050/job/31811844512
> chore(compose): Disable idle power metrics in VM

- .github/workflows/image.yml
Add in-toto attestation to all image-building ci workflows, for both SBOMs (image.yml) and images themselves (all 3 workflows). Allow necessary permissions to attest (attestations, packages).
> ci: add attestation to container images and SBOMs

- manifests/compose/dev/compose.yaml
- manifests/compose/validation/metal/compose.yaml
Enables measuring per cpu context switches.
example:
Note: In case of isolated CPUs, if we dont specify `--collector.perf.cpus` config parameter, node-exporter will use the range from `0` to `runtime.NumCPU()` which does not include isolated CPUs. if this range includes isolated cpus those cpus will be considered, whereas the last few CPUs will be dropped.
e,.g. if there are 20 CPUs, and cpus 2,3,12,13 are isolated, not configuring `--collector.perf.cpus` means 0-15 will be shown, which includes the isolated cpus. which is counter intuitive.
sp pls mention the complete cpu range  `--collector.perf.cpus=0-19`
> fix(compose): Enable measuring ContextSwitches in node-exporter

- e2e/tools/validator/src/validator/cli/__init__.py
- e2e/tools/validator/src/validator/prometheus/__init__.py
- e2e/tools/validator/src/validator/report/__init__.py
- e2e/tools/validator/tests/validator/prometheus/test_prometheus.py
This commit fixes MAPE calculation and its tests.
Additionally, the json generation is cleaned and added to `gen-report` as well.
> chore(validator): MAPE and json generation

- manifests/compose/monitoring/prometheus/Dockerfile
This commit updates the compose config to use a stable Prometheus version instead of the main development version.
Additionally, it resolves an issue where Prometheus could not scrape metrics from Scaphandre, which was failing due to an invalid `Content-Type` header in Scaphandre's response.
> chore(compose): switch to stable Prometheus version

- pkg/collector/resourceutilization/bpf/process_bpf_collector.go
- pkg/config/config.go
- pkg/config/types.go
when cpu is idle, swapper process is scheduled, and kepler adds its bpf_cpu_time to kernel processes
adding a configuration to exclude swapper process
with-swapper
without-swapper
> fix(bpf): exclude swapper process bpf_cpu_time

- build/Dockerfile
This PR should close https://github.com/sustainable-computing-io/kepler/issues/1826.
Using a smaller base image has several benefits:
- Reducing the storage footprint. Quicker deployments (less and/or smaller layers to pull).
- Reducing the potential attack surface.
- Reducing the amount of vulnerabilities that will arise between one `kepler` release and another, simply because there are less items installed.
A picture is worth a thousand words:
The vulnerabilities we see above (as of 2024/10/24, in `kepler:release-0.7.12`) are inherited from the base image. They are in the python namespace, which is not needed at all in the `kepler` image, and which is why https://github.com/sustainable-computing-io/kepler/pull/1361 cannot get rid of them.
Thank you.
> feat: move from ubi to ubi-minimal

- e2e/tools/validator/src/validator/cli/__init__.py
> docs: add new line after host/vm/summary table

- manifests/compose/default/kepler/etc/kepler/kepler.config/EXPOSE_ESTIMATED_IDLE_POWER_METRICS
- manifests/compose/dev/kepler/etc/kepler/kepler.config/EXPOSE_ESTIMATED_IDLE_POWER_METRICS
This commit disables the idle power metrics in case of dev compose.
> chore(compose): disable idle power in case of dev

- e2e/tools/validator/scripts/stressor.sh
- e2e/tools/validator/src/validator/config/__init__.py
- e2e/tools/validator/src/validator/stresser/__init__.py
- e2e/tools/validator/tests/validator/config/test_config.py
- e2e/tools/validator/validations.yaml
Setting max runtime so that we can reduce runtime on AWS instances.
> chore: make validator stressor configuration on runtime and load

- e2e/tools/validator/src/validator/cli/__init__.py
- e2e/tools/validator/src/validator/stresser/__init__.py
- e2e/tools/validator/validations.yaml
- e2e/tools/validator/validator.yaml.sample
this is to fix the previous PR that didn't get full tested. This change is verified with the following config:
```yaml
log_level: warn # Logging level, defaults is warn
remote:
host: my-vm
username: root
pkey: /tmp/vm_ssh_key
metal:
vm:
pid: 123456 # Process ID for the KVM process running on metal
prometheus:
job:
vm: vm  # Job name for virtual machine metrics, default is vm
metal: metal  # Job name for metal metrics, default is metal
url: http://localhost:9090 # Prometheus server URL
rate_interval: 20s  # Rate interval for Promql, default is 20s, typically 4 x $scrape_interval
steps: 3s  # Step duration for Prometheus range queries
stressor:
total_runtime_seconds: 600  # Total runtime in seconds for the stress test
curve_type: default  # Curve type for the stress test, default is linear …
```
> chore: fix wrong stressor init in validator

- README.md
The diagram preview can be found [here](https://github.com/sustainable-computing-io/kepler/blob/50b1dd6e1f1c02da8444b3151f57ac635a1605eb/README.md)
> chore(readme): update architecture diagram

- manifests/compose/monitoring/prometheus/Dockerfile
This commit fixes the issue where prometheus using `latest` is unable to scrape scaphandre metrics due to issue in scaphandre of having an invalid `Content-Type` header in Scaphandre's response.
> chore(compose): use fixed version of prometheus

- cmd/exporter/exporter.go
- pkg/collector/metric_collector_test.go
- pkg/collector/stats/benchmark_test.go
- pkg/collector/stats/container_stats_test.go
- pkg/collector/stats/node_stats_test.go
- pkg/collector/stats/process_stats_test.go
- pkg/collector/stats/stats_test.go
- pkg/collector/stats/test_utils.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/types.go
- pkg/libvirt/resolve_vm_test.go
- pkg/manager/manager_test.go
- pkg/model/benchmark_test.go
- pkg/model/estimator/local/ratio_model_test.go
- pkg/model/estimator/local/regressor/exponential_test.go
- pkg/model/estimator/local/regressor/linear_test.go
- pkg/model/estimator/local/regressor/logarithm_test.go
- pkg/model/estimator/local/regressor/logistic_test.go
- pkg/model/estimator/local/regressor/regressor_test.go
- pkg/model/process_energy_test.go
- pkg/sensors/accelerator/accelerator_test.go
- pkg/sensors/platform/source/redfish_test.go
- pkg/sensors/power_suite_test.go
This commit now allows default hard-coded config directory to be passed as an argument. This allow quickly changing between different configurations to be stored separately and to switch between them (especially during development).
The commit also
* simplifies global config initialization by ensuring  it is initialised at the time kepler's main function is executed and fail with error that step fails.
* It also cleans up use of config object to read CGroup info by creating a `realSystem` struct that handles this functionality.
> feat(config): allow config dir to be passed as argument

- Makefile
- pkg/collector/stats/vm_stats_test.go
try to fix warning as https://github.com/sustainable-computing-io/kepler/actions/runs/11903667506/job/33171074065#step:7:451
and a nil pointer in test code.
> [nit]: update ginkgo version in CI process keep same with go mod

- pkg/node/node.go
- pkg/node/node_test.go
- fixed reading cpus.yaml file
- added unit tests
> fix(cpu): fixed reading cpus.yaml

- .github/workflows/pull_request.yml
- build/Dockerfile.builder
ref https://github.com/sustainable-computing-io/kepler/actions/runs/11814219047/job/32912842046
it seems with elfutils version upgrade, our base image code need to be update accordingly.
> [fix]: base image elfutils version issue

- build/Dockerfile
ref https://github.com/sustainable-computing-io/kepler/actions/runs/11985980953/job/33419265828
fix libbpf build version in container image
> [fix]: fix image libbpf build version

- .github/workflows/commitMsg.yml
- .github/workflows/daily.yml
- .github/workflows/developer_local.yml
- .github/workflows/gosec.yml
- .github/workflows/pre-commit-auto-update.yml
- .github/workflows/pull_request.yml
- .github/workflows/unit_test.yml
- .github/workflows/yamllint.yml
try to update GHA workflow permission settings.
> [fix]: update gha permission settings

- .github/workflows/gosec.yml
- .github/workflows/pre-commit-auto-update.yml
fix CI permissions according to failed CI jobs
ref 
https://github.com/sustainable-computing-io/kepler/actions/runs/12104149942
https://github.com/sustainable-computing-io/kepler/actions/runs/12100596870
> [fix]: fix CI permissions according to failed CI jobs

- .github/workflows/pre-commit-auto-update.yml
Allow the pre-commit auto update job to also be triggered manually
> chore: pre-commit auto update enable manual trigger

- .github/workflows/daily.yml
ref to https://github.com/sustainable-computing-io/kepler/actions/runs/12116247835
I am not get the point for know, but it seems
- the upper pipeline as daily, should not have any permissions setting.
- when a pipeline been invoked, it will inherit from upper pipeline as permissions setting.
so, by this PR, set daily job's permission same as push pipeline, as push pipeline works.
https://github.com/sustainable-computing-io/kepler/actions?query=event%3Apush
The workflow is not valid. .github/workflows/daily.yml (Line: 14, Col: 3): Error calling workflow 'sustainable-computing-io/kepler/.github/workflows/gosec.yml@a447077ffd2e40f633f2aa200b1b8d61063573c4'. The workflow is requesting 'contents: read', but is only allowed 'contents: none'.
> [fix]: unset permissions to avoid CI issue

- pkg/config/config.go
> chore(config): if the config dir doesn't exist, create it

- .github/workflows/acpi-validation.yml
- .github/workflows/pull_request.yml
- e2e/tools/validator/acpi_validations.yaml
- e2e/tools/validator/src/validator/cli/__init__.py
- e2e/tools/validator/validator.mock-acpi.yaml
This commit migrates the mock-acpi workflow to use the GitHub runner instead of the Equinix self-hosted runner. Since the workflow is designed for testing ACPI functionality, using a mock, a self-hosted runner is not required.
Running the workflow on the GitHub runner, which operates as a VM, enables execution on every pull request, ensuring consistent validation of ACPI functionality for Kepler.
> chore(ci): migrate mock-acpi workflow to GH runner

- pkg/cgroup/resolve_container.go
- pkg/cgroup/resolve_container_test.go
add test case on package cgroup
remove duplicate function
fix a cache set logic when error happen on code logic
> [test]: add test case on package cgroup

- pkg/collector/stats/types/types.go
- pkg/config/config.go
- pkg/kubelet/kubelet_pod_lister.go
- pkg/model/types/types.go
- pkg/sensors/components/source/rapl_msr_util.go
- pkg/sensors/components/source/rapl_sysfs.go
https://github.com/sustainable-computing-io/kepler/actions/runs/12177539929/job/33966954289
seems we have many nits can be improved to reduce our memory escapes to heap case.
in this PR, try to improve parts of them.
> [fix]: try to reduce escapes to heap

- pkg/kubelet/kubelet_pod_lister.go
- pkg/kubelet/kubelet_pod_lister_test.go
keep kubelet token in memory to reduce os.file read for each time to get auth token.
if token expired, try again.
refactor with var injection for test case impl.
> [fix]: enhance kubelet package impl

- .github/workflows/unit_test.yml
This commit updates the `GITHUB_TOKEN` permission for the unit test workflow.
Addresses #1880
> chore(ci): update permissions for unit test workflow

- packaging/rpm/container-kepler.service
This commit updates the rpm volume mounts to match to specific requirements of Kepler
Addresses #1885
> chore: align rpm volume mounts with Kepler requirements

- .github/workflows/unit_test.yml
This commit fixes an issue where the Codecov could not generate a coverage report. The command `go tool cover -func=coverage.out -o=coverage.out` outputs a human readable function coverage summary, but Codecov requires raw coverage data in a compatible format.
> fix(ci): resolve Codecov report generation failure

- manifests/compose/dev/override.yaml
- manifests/compose/dev/prometheus/scrape-configs/dev.yaml
This change allows running kepler on host and scrape it, making it easier during
development to test changes quickly without building an image.
> chore(compose): allow scraping from kepler on host

- manifests/compose/dev/compose.yaml
- manifests/compose/dev/kepler/etc/kepler/kepler.config/PROC_DIR
- manifests/compose/dev/kepler/etc/kepler/kepler.config/SYS_DIR
- pkg/bpf/exporter.go
- pkg/bpf/fake_mac.go
- pkg/cgroup/resolve_container.go
- pkg/collector/metric_collector.go
- pkg/collector/resourceutilization/accelerator/process_gpu_collector.go
- pkg/config/config.go
- pkg/config/types.go
- pkg/libvirt/resolve_vm.go
- pkg/node/node.go
- pkg/sensors/accelerator/devices/grace_acpi.go
- pkg/sensors/components/source/apm_xgene_sysfs.go
- pkg/sensors/components/source/grace_acpi.go
- pkg/sensors/components/source/rapl_sysfs.go
- pkg/sensors/components/source/rapl_sysfs_util.go
- pkg/sensors/platform/source/acpi.go
This patch replaces hardcoded /proc and /sys paths just like in other exporters like node-exporter with configurable ones using the config package. E.g., config.ProcDir() and config.SysDir().
These paths can now be set via SYS_DIR and PROC_DIR config variables, defaulting to "/proc" and "/sys" if unspecified.
Mounting host /proc and /sys into containers is discouraged because it compromises security and isolation.
> feat(config): Make /proc and /sys paths configurable

- .github/workflows/unit_test.yml
This commit will allow Codecov to run on every PR so that we can get a better code coverage report at the time of PR review.
Ref: 
https://app.codecov.io/gh/sustainable-computing-io/kepler/commit/e9855ddbcbc41c482d033f3573fd2d44637c7936
> chore(ci): enable Codecov for PRs

- manifests/compose/compose.yaml
- manifests/compose/default/kepler/etc/kepler/kepler.config/PROC_DIR
- manifests/compose/default/kepler/etc/kepler/kepler.config/SYS_DIR
This commit adds the `PROC_DIR` and `SYS_DIR` config for the latest and also updates the `compose.yaml` to use the appropriate `target` path when mounting the volumes
> chore(compose): add proc and sys dir config for latest

- manifests/k8s/config/exporter/patch/patch-estimator-sidecar.yaml
- manifests/k8s/config/model-server/patch/patch-openshift.yaml
For performance testing we need all the 4 deployment models of kepler to work: https://sustainable-computing.io/kepler_model_server/power_estimation/
So inorder for all of them to work, we need the patches in this PR to go in.
Tested and verified them in local openshift cluster
1. Kepler minimal deployment
```
GOFLAGS="" make build-manifest OPTS="OPENSHIFT_DEPLOY PROMETHEUS_DEPLOY"
```
2. Deployment with estimator sidecar
```
GOFLAGS="" make build-manifest OPTS="OPENSHIFT_DEPLOY PROMETHEUS_DEPLOY ESTIMATOR_SIDECAR_DEPLOY"
```
3. Deployment with model server
```
GOFLAGS="" make build-manifest OPTS="OPENSHIFT_DEPLOY PROMETHEUS_DEPLOY MODEL_SERVER_DEPLOY"
```
4. Full kepler deployment with estimator and model server
```
GOFLAGS="" make build-manifest OPTS="OPENSHIFT_DEPLOY PROMETHEUS_DEPLOY …
```
> fix(openshift): patch deployment issue

- manifests/compose/dev/prometheus/scrape-configs/dev.yaml
- manifests/compose/validation/metal/prometheus/scrape-configs/metal.yaml
This PR removes the fallback scrape protocol config from the Scaphandre scrape config as the latest prometheus doesn't recoganize the field as part of Scrape config structure
> fix(compose): remove fallback scrape protocol config

- cmd/kepler/main.go
This commit adds the missing copyright notice to the source code
> chore: add Apache License copyright

- cmd/kepler/main.go
- go.mod
- go.sum
This commit provide a skeleton to run multiple services in separate go threads and orchestrate clean up if any of these services exit with an error during its startup phase.
NOTE: interrupting (SIGINT) kepler does not result in exit code 0 rather it initiates the shutdown process.
> chore(main): use run.Group to run multiple services

- Makefile
- cmd/kepler/logger.go
- cmd/kepler/logger_test.go
- cmd/kepler/main.go
- go.mod
- go.sum
- internal/version/version.go
This commits adds version information to kepler. This infomation get
logged in the startup as follows
```
time=2025-04-01T10:21:52.529-04:00 level=INFO source=cmd/kepler/main.go:82 \
msg="Kepler version information"
version=074c9fe5 \
buildTime=2025-04-01_14:21:52 \
gitBranch=reboot \
gitCommit=074c9fe5 \
goVersion=go1.22.12 \
goOS=linux \
goArch=amd64
```
NOTE: output above is broken into multiple lines for better readability.
Signed-off-by: Sunil Thaha <sthaha@redhat.com>
> feat(version): add version information to build

- cmd/kepler/logger.go
- cmd/kepler/logger_test.go
- cmd/kepler/main.go
- go.mod
- go.sum
This PR sets up slog to use logger instead of `fmt.Println` to log all information.
> feat(logger): use slog for logging

- .github/publish-image/action.yaml
- .github/workflows/publish-image.yaml
This commit adds a basic workflow which builds and pushes Kepler image to quay.io registry on push to `reboot` branch
It will push the image to `kepler-reboot` repo under sustainable_computing_io org. The tag will be pointing to current commit SHA
**Note: BOT_NAME and BOT_TOKEN secrets must be defined under repo's settings**
Ref: https://github.com/sustainable-computing-io/kepler/blob/85d017bc23bb6be33adf471414870d874357f532/.github/workflows/push.yml#L16
Signed-off-by: vprashar2929 <vibhu.sharma2929@gmail.com>
> feat(ci): add workflow to build, push image to quay

- .github/publish-image/action.yaml
- .github/workflows/pr-checks.yaml
- Makefile
This commit adds basic workflow to run PR checks on kepler reboot Currently it performs the following checks:
* Runs `make fmt` to check if the code is formatted correctly
* Runs `make test` to check if the code is unit tested
* Runs `golangci-lint` to check if the code is linted correctly
* Runs `build-image` to check if the image can be built successfully
> feat(ci): add workflow to pr checks

- .github/publish-image/action.yaml
- .github/workflows/publish-image.yaml
- Makefile
This commit adds additional tags to the image when pushing to quay.io. Now we will have tags like `latest`, `SHA` and `SHA-timestamp` pushed to quay.io.
> feat(ci): add additional tags when pushing image

- internal/config/config.go
- internal/config/config_test.go
This commit adds missing tests for config.String and config.Load functions.
> chore: improve test coverage of config

- .codespellignore
- .commitlintrc.yaml
- .github/publish-image/action.yaml
- .github/workflows/codecov-upload.yaml
- .github/workflows/pr-checks.yaml
- .github/workflows/push.yaml
- .markdownlint.yaml
- .pre-commit-config.yaml
- .yamllint.yaml
- Makefile
- code-of-conduct.md
- compose/dev/config/process-exporter.yaml
- compose/dev/override.yaml
- docs/developer/pre-commit.md
- internal/device/cpu_power_meter.go
This commit adds the pre-commit hooks to the project. The hooks are run automatically when a commit is made to the project. The pre-commit hooks include:
- trailing-whitespace: Trims trailing whitespace from lines
- end-of-file-fixer: Ensures files end with a newline
- check-added-large-files: Prevents large files from being committed
- check-merge-conflict: Prevents files with merge conflicts from being committed
- yamllint: Validates YAML files
- markdownlint: Validates Markdown files
- codespell: Checks for common misspellings
- golangci-lint: Runs Go linters
- commitlint: Validates commit messages against Conventional Commits format
Commit adds the appropriate configuration files for each hook and also adds the necessary steps to pr-checks workflow to run this on every PR.
> feat(ci): add pre-commit hooks

- .gitignore
- Makefile
This commit omits the `cmd/` folder from the test coverage.
> chore(makefile): omit main from test coverage

- cmd/kepler/main.go
- internal/logger/logger.go
- internal/logger/logger_test.go
This commit moves logger to internal package.
Follow up to #1977
> chore(logger): move logger to internal

- cmd/kepler/main.go
- go.mod
- go.sum
- internal/device/cpu_power_meter.go
- internal/device/cpu_power_meter_test.go
- internal/device/energy.go
- internal/device/energy_test.go
- internal/device/power_meter.go
- internal/monitor/mock_cpu_meter_test.go
- internal/monitor/monitor.go
- internal/monitor/monitor_test.go
- internal/monitor/types.go
- internal/service/service.go
This commit introduces the following changes:
* Adds a service interfaces that all services (currently monitor)
implements
* Refactors application startup to use services and starts them up,
terminating if any of the service fails to start.
* Adds monitor service (with unit-tests)
* Modifies Device startup to accept a context so that the startup can be
aborted if context is canceled.
Signed-off-by: Sunil Thaha <sthaha@redhat.com>
> feat(stubs) stubs for all services

- .pre-commit-config.yaml
- internal/monitor/mock_cpu_meter_test.go
- internal/monitor/monitor.go
- internal/monitor/monitor_test.go
- internal/monitor/types.go
This commit runs reuse tool as pre-commit hook to verify licenses in source code files
> feat(ci): add reuse tool as pre-commit hook for license check

- .github/release.yml
- .github/workflows/release.yaml
This commit updates the release workflow to use the new release action as the previous one is deprecated.
It also addresses the following:
- Removes the changelog generation step from the release job as it is not required anymore.
- The release created will contain `(reboot)` in the title. For eg: `release-v0.2.0 (reboot)`
- The release created will not be marked as `latest`
Also adds a changelog config file that will be used by GH at the time of generating the changelog.
Addreses: #1989
> ci: update the release workflow

- .github/pr-labeler.yml
- .github/workflows/pr-checks.yaml
This commit adds a labeler job to PR workflow to label PRs based on commit messages. Following labels are added:
- feat
- fix
- chore
- docs
- ci
- refactor
- perf
- test
- revert
Partially addresses #1989 
Ref: https://github.com/grafana/pr-labeler-action?tab=readme-ov-file#default-config
Relevant labels are already added to project: https://github.com/sustainable-computing-io/kepler/labels
> ci: label PR based on commit messages

- internal/exporter/prometheus/collectors/build_info.go
- internal/exporter/prometheus/collectors/build_info_test.go
- internal/exporter/prometheus/prometheus.go
This commit adds the build info collector that exposes build related information(architecture,branch, commit, version, goversion) as a `kepler_build_info` metric.
> feat: add build info collector

- internal/exporter/prometheus/collectors/build_info_test.go
This commit adds a new test case to verify that the collector behaves correctly under multiple collection requests without race conditions.
> test: add concurrency test for build info collector

- .github/workflows/golang.yml
- .golangci.yml
- .pre-commit-config.yaml
- pkg/model/estimator/local/regressor/exponential.go
- pkg/model/estimator/local/regressor/linear.go
- pkg/model/estimator/local/regressor/logarithm.go
- pkg/model/estimator/local/regressor/logistic.go
- pkg/node/node.go
- pkg/sensors/accelerator/devices/device.go
- pkg/sensors/platform/source/redfish_test.go
- Downgrade the clang-format version to 19.1.7 for config compatibility.
- Migrate golangci-lint config to latest
- Fix linting issues inside `pkg`
- Updates the golang workflow to now use v7 action and golangci-lint v2.1.1
> chore: fix and update precommit hooks

- .github/pr-labeler.yml
This commit adds a PR labeler config to the default branch of the repo i.e `main`. Since `grafana/pr-labeler-action` expects the config to be available in the default branch, adding this to reboot branch will not work
> ci: add pr-labeler config

- compose/dev/compose.yaml
- hack/config.yaml
This commit uses desired config when bringing kepler-dev service up. It also updates the sample config file with newly host related config
> chore(compose): expose config when bringing service up

- cmd/kepler/main.go
- config/config.go
- hack/config.yaml
- internal/device/fake_cpu_power_meter.go
- internal/device/fake_cpu_power_meter_test.go
Adds a new `FakeCPUMeter` implementation in the `device` package to simulate CPU power metrics for testing purposes. The fake meter is not intended for production use and is for development / testing use only
Changes include:
- New with `fakeEnergyZone` and `fakeRaplMeter` types  that implement the `EnergyZone` and `CPUPowerMeter` interfaces.
- Configuration support for enabling the fake meter via `dev.fake-cpu-meter.enabled` in `config.yaml` ONLY and not through flags
- Refactored `main.go` to use a new `createCPUMeter` function that conditionally creates either a real or fake CPU power meter based on the configuration.
- Updated `config.go` to include `Dev` struct for development settings
- Added default configuration in `hack/config.yaml` with `fake-cpu-meter` disabled.
> chore(device): add fake CPU power meter for testing

- internal/device/rapl_sysfs_power_meter_test.go
This commit adds some negative tests for rapl_sysfs power meter Test include:
- Test that invalid sysfs path results in an error
- Test that error from reader are handled properly
- Test in case of no RAPL zones are found
- Test that Start returns error when no zones are found
> test: add negative tests for rapl power meter

- cmd/kepler/main.go
- internal/exporter/prometheus/collectors/build_info.go
- internal/exporter/prometheus/collectors/cpuinfo.go
- internal/exporter/prometheus/collectors/cpuinfo_test.go
- internal/exporter/prometheus/prometheus.go
- internal/exporter/prometheus/prometheus_test.go
Added a collector for cpu info built on prometheus procfs
> feat(cpuinfo): Added cpu info collector

- internal/exporter/prometheus/collector/build_info.go
- internal/exporter/prometheus/collector/build_info_test.go
- internal/exporter/prometheus/collector/cpuinfo.go
- internal/exporter/prometheus/collector/cpuinfo_test.go
- internal/exporter/prometheus/collector/power_collector.go
- internal/exporter/prometheus/collector/power_collector_test.go
- internal/exporter/prometheus/collector/utils.go
- internal/exporter/prometheus/prometheus.go
This commit renames the collectors with collector for singular naming consistency. It also updates `BuildInfoCollector` to `KeplerBuildInfoCollector` to avoid conflicts with Prometheus `BuildInfoCollector`.
> chore: rename collectors to collector

- internal/exporter/prometheus/collector/power_collector.go
- internal/exporter/prometheus/collector/power_collector_concurrency_test.go
- internal/monitor/monitor.go
This PR checks thread-safety of Power Collector and thereby also the Monitor indirectly using `fakeCPUMeter`. The PowerCollector was prone to race conditions when Describe and Collect were called concurrently (without any waits in between) before metric descriptors were initialized, potentially causing panics or incomplete metrics.
Additionally, the PowerMonitor's ZoneNames method used an unnecessary mutex, impacting performance.
This commit also introduces a `ready` flag to ensure Describe and Collect only execute after descriptor initialization, protected by a mutex. 
The PowerMonitor's zones mutex is removed, as zones are immutable post-initialization.
The test suite (`power_collector_concurrency_test.go`) validates thread safety under concurrent Describe, Collect, registration, and …
> fix(collector): prevent race conditions in PowerCollector with ready flag and tests

- compose/dev/compose.yaml
- compose/dev/config/process-exporter.yaml
- compose/dev/override.yaml
- compose/dev/prometheus/scrape-configs/dev.yaml
This commit removes the process-exporter from the compose manifests.
> chore(compose): remove process-exporter

- internal/exporter/prometheus/collector/cpuinfo.go
- internal/exporter/prometheus/collector/cpuinfo_test.go
change metric fqdn name to "kepler_node_cpu_info"
> fix(cpu_info): change metric name to kepler_node_cpu_info

- cmd/kepler/main.go
- internal/device/fake_cpu_power_meter.go
- internal/device/fake_cpu_power_meter_test.go
- internal/device/power_meter.go
- internal/device/rapl_sysfs_power_meter.go
- internal/device/rapl_sysfs_power_meter_test.go
- internal/exporter/prometheus/collector/power_collector_concurrency_test.go
- internal/exporter/prometheus/prometheus.go
- internal/exporter/prometheus/prometheus_test.go
- internal/monitor/mock_cpu_meter_test.go
- internal/monitor/monitor.go
- internal/monitor/monitor_test.go
- internal/server/server.go
- internal/server/server_test.go
- internal/service/service.go
This commit modifies the start up behavior. It refactors the service lifecycle management, replacing the Start and Stop methods with
* `Init`: used to initiliaze a service and can assume it isn't called from go routines and must be called before `Run`. 
* `Run`: Runs the service and blocks until context is cancelled or an error is encountered
* `Shutdown`:  method is the cleanup and indicates that you can't call `Run` after `Shutdown`.
This change aims to separate initialization which is run serially and allows services to initialize without worrying about thread-safety. I.E. Its okay for an Init() to call another Init().
Thus, this change separates initialization, runtime, and cleanup phases for better clarity and control. All Methods are optional and main calls the methods if they are …
> refactor: service lifecycle into optional Init Run Shutdown

- .github/workflows/pr-checks.yaml
This commit adds job to run go vet on PR checks. It also refactor workflow to run fmt, lint and vet jobs respectively.
> ci: add go vet job

- internal/monitor/monitor.go
- internal/monitor/monitor_concurrency_test.go
- internal/monitor/monitor_test.go
- internal/monitor/node.go
- internal/monitor/node_test.go
This commit replaces sync.RWMutex with atomic.Pointer for thread-safe snapshot
access in PowerMonitor.
* Move zone initialization to initZones method and defer snapshot creation.
* Update calculateNodePower to accept previous node data, decoupling it from snapshot locking.
* update tests to reflect new logic.
> refactor(monitor): replace RWMutex with atomic.Pointer for snapshot management

- cmd/kepler/main.go
- config/config.go
- config/config_test.go
- internal/server/pprof.go
- internal/server/pprof_test.go
- internal/server/server.go
> feat(pprof): Added pprof

- cmd/kepler/main.go
- internal/device/fake_cpu_power_meter.go
- internal/device/fake_cpu_power_meter_test.go
- internal/device/power_meter.go
- internal/device/rapl_sysfs_power_meter.go
- internal/device/rapl_sysfs_power_meter_test.go
- internal/exporter/prometheus/collector/power_collector_concurrency_test.go
- internal/exporter/prometheus/prometheus.go
- internal/exporter/prometheus/prometheus_test.go
- internal/monitor/mock_cpu_meter_test.go
- internal/monitor/monitor.go
- internal/monitor/monitor_concurrency_test.go
- internal/monitor/monitor_test.go
- internal/server/pprof.go
- internal/server/pprof_test.go
- internal/server/server.go
- internal/server/server_test.go
- internal/service/initializer.go
- internal/service/initializer_test.go
- internal/service/mock_service_test.go
- internal/service/run.go
- internal/service/run_test.go
- internal/service/service.go
- internal/service/signal_handler.go
- internal/service/signal_handler_test.go
This commit addresses comments on https://github.com/sustainable-computing-io/kepler/pull/2021
Simplify service lifecycle management by:
- Removing context.Context from Initializer.Init() method
- Renaming Shutdown to Shutdowner for clarity
- Removing Init, Run, and Stop methods from powerMeter interface
- Removing Shutdown from PowerMonitor and Stop from power meters
- Refactoring createPowerMonitor into createServices
- Introduce service.NewSignalHandler for SIGINT and SIGTERM, replacing custom signal handling.
- Replace runServices and initServices with service.Run and service.Init for testable lifecycle management.
- Simplify powerMeter interface by removing Init, Run, and Stop methods.
- Rename Shutdown to Shutdowner and remove context from Initializer.Init.
- Inline …
> refactor(service): simplify service lifecycle

- .github/workflows/pr-checks.yaml
This commit ensures that the PR checks specifically related to the go files are run only when the go files are changed.
> ci: run jobs based on file changes

- cmd/kepler/main.go
- config/config.go
- config/config_rapl_test.go
- hack/config.yaml
- internal/device/rapl_sysfs_power_meter.go
- internal/device/rapl_zone_filtering_test.go
Changes include:
* Add RAPL zone filtering option in config (rapl/zones).
* Add zone filtering in raplPowerMeter and log excluded and included zones
* Update createCPUMeter to use RAPL config and filter zones.
* Test for RAPL config and zone filtering.
> feat: add RAPL zone filtering support through configuration

- config/config.go
- config/config_test.go
This commit adds the logic to skip validations for the config from the operator. With this we can skip certain configs that we don't want Kepler to validate.
> chore(config): add skip validation logic from operator

- internal/monitor/monitor.go
- internal/monitor/monitor_collection_test.go
- internal/monitor/monitor_concurrency_test.go
- internal/monitor/monitor_test.go
- internal/monitor/options.go
This refactor enhances the monitor as follows:
- Replace mutex-based synchronization with atomic operations for thread safety
- Implement dynamic collection scheduling with configurable intervals
- Add option to disable automatic collection (interval=0) for on-demand only mode
- Pass previous snapshot explicitly to calculateNodePower
- Simplify zone name handling by removing unnecessary synchronization
- Use a context for clean cancellation of collection goroutines
- Ensure freshness checks always return recent data
> feat(monitor): improve power monitor with dynamic collection based on interval

- internal/monitor/monitor.go
- internal/monitor/monitor_test.go
- internal/monitor/node.go
- internal/monitor/node_test.go
Split the refreshSnapshot logic to handle initial and subsequent power readings separately. This commit adds firstReading and calculatePower methods to improve clarity and maintainability.
Also
* Update calculateNodePower to remove initial reading logic.
* Adjust tests to reflect the new method signatures and behavior.
fixes: #2025
> refactor(monitor): split  snapshot refresh into initial and subsequent readings

- docs/configuration/configuration.md
This commit adds a guide to the supported configuration parameters for running Kepler.
> docs: add initial guide for supported config params

- docs/configuration/configuration.md
This commit adds the monitor and web related configurations to the documentation.
> docs: add monitor and web related config

- .github/workflows/developer_local.yml
- .markdownlint.json
This commit disables the markdown descriptive link text rule in the markdownlint configuration file allowing pre-commit hook to pass
NOTE: Disabling this rule for now since fixing this requires edits in multiple readme files
> ci: exclude markdown descriptive link text rule

- cmd/kepler/main.go
- internal/logger/logger.go
- internal/logger/logger_test.go
This commit modified logger to use stdout (buffered out) unless the stdout exporter is enabled. On enabling stdout exporter, the logger is configured to write to stderr.
> chore(logger): prefer buffered stdout over stderr

- .github/publish-image/action.yaml
- go.mod
This commit ensures that the diff is taken after running make deps and fails if the diff is not empty.
It also fixes the issue where the go.mod file contains the diff due to which VERSION being computed has `-dirty` suffix.
> ci: capture diff after running make deps

- GOVERNANCE.md
`Contributors.md` is no longer existing. `CONTRIBUTORS.md` also does not contain the list. The maintainer list is in [MAINTAINERS.md](https://github.com/sustainable-computing-io/kepler/blob/main/MAINTAINERS.md)  
> chore: fix missing maintainer link

- Makefile
- README.md
- hack/cluster.sh
- hack/utils.bash
- manifests/k8s/configmap.yaml
- manifests/k8s/daemonset.yaml
- manifests/k8s/kustomization.yaml
- manifests/k8s/namespace.yaml
- manifests/k8s/prometheus-rbac.yaml
- manifests/k8s/rbac.yaml
- manifests/k8s/service.yaml
- manifests/k8s/servicemonitor.yaml
This commit adds setup for Kind cluster and Kepler deployment. Changes include:
- `cluster.sh`: Sets up Kind cluster using `local-dev-cluster` repo.
- `manifests/k8s/`: Kubernetes manifests for Kepler deployment.
- `namespace.yaml`: Creates namespace.
- `configmap.yaml`: Configures Kepler.
- `rbac.yaml`: Grants Kepler cluster access.
- `prometheus-rbac.yaml`: Grants Prometheus access to Kepler.
- `daemonset.yaml`: Deploys Kepler.
- `service.yaml`: Exposes Kepler service.
- `servicemonitor.yaml`: Exposes Kepler service monitor.
- New Makefile targets:
- `cluster-up`: Starts Kind cluster.
- `cluster-down`: Tears down Kind cluster.
- `cluster-restart`: Restarts Kind cluster.
- `deploy`: Deploys Kepler on Kind cluster.
- `undeploy`: Deletes Kepler from Kind cluster.
- README update with …
> ci: enable Kepler deployment on Kind cluster

- manifests/k8s/configmap.yaml
- manifests/k8s/daemonset.yaml
This commit renames the config file for kepler from kepler-config.yaml to config.yaml
> chore(k8s): rename config file for kepler

- .github/workflows/mock_acpi.yml
This commit switches the Equinix Metal CI to use Ubuntu 22.04 instead of Ubuntu 20.04
> ci: switch to using ubuntu 22.04

- .pre-commit-config.yaml
This commit ensures that the required precommit hook types are installed at the time of initial precommit setup.
> chore: ensure that required precommit hook types are installed

- hack/experiments/kube-rbac-proxy-setup/README.md
- hack/experiments/kube-rbac-proxy-setup/kube-rbac-proxy-secret.yaml
- hack/experiments/kube-rbac-proxy-setup/power-monitor-ca.yaml
- hack/experiments/kube-rbac-proxy-setup/power-monitor-clusterrole.yaml
- hack/experiments/kube-rbac-proxy-setup/power-monitor-clusterrolebinding.yaml
- hack/experiments/kube-rbac-proxy-setup/power-monitor-cm.yaml
- hack/experiments/kube-rbac-proxy-setup/power-monitor-daemonset.yaml
- hack/experiments/kube-rbac-proxy-setup/power-monitor-namespace.yaml
- hack/experiments/kube-rbac-proxy-setup/power-monitor-sa.yaml
- hack/experiments/kube-rbac-proxy-setup/power-monitor-scc.yaml
- hack/experiments/kube-rbac-proxy-setup/power-monitor-service.yaml
- hack/experiments/kube-rbac-proxy-setup/power-monitor-sm.yaml
- hack/experiments/kube-rbac-proxy-setup/test-ca-default.yaml
- hack/experiments/kube-rbac-proxy-setup/test-ca.yaml
- hack/experiments/kube-rbac-proxy-setup/test-correct-job.yaml
- hack/experiments/kube-rbac-proxy-setup/test-sa.yaml
- hack/experiments/kube-rbac-proxy-setup/test-wrong-job.yaml
This experiment tests implementing kube-rbac-proxy into the kepler daemonset as a sidecar and proving that it can protect kepler's /metrics endpoint from certain service accounts. The experiment also demonstrates that prometheus instances like user workload monitoring through the ServiceMonitor can be granted or denied access to kepler's /metrics endpoint.
> feat(experiments): added kube-rbac-proxy to kepler openshift deployment

- compose/dev/grafana/dashboards/dev/node-dashboard.json
Implemented dashboard which illustrates node level power metrics for energy zones and instances. The dashboard shows historical power consumption of node zones, total power consumption of zones in cluster, average power consumption, and current power consumption. All power consumption metrics are represented in Watts.
> chore(dashboard): test dashboard for node power metrics

- .pre-commit-config.yaml
This commit adds the support for running shell check and shfmt as pre-commit hooks.
> ci: add shellcheck and shfmt as precommit hooks

- .github/release.yml
- .github/workflows/assign-labels.yaml
This commit adds a new label for any breaking change PRs. It also updates the release config to include the breaking change label.
> ci: add breaking change label

- .github/check-x-crypto/action.yaml
- hack/reports/print-xcrypto-report.sh
This commit updates the x-crypto detection script to use git archive for checking out two different versions of source instead of using worktrees
It also fixes the issue where on CI the script fails when creating worktree for base branch as it already exists.
> ci: use git archive for source version checkout

- compose/dev/grafana/dashboards/dev/dashboard.json
With the recent zone changes to include zone+index in the name the current dashboard fails to render the queries that don't follow the new zone name format. This commit updates the dashboard to include a `zone_clean` variable that filters out the zone index and then use that variable where zone+index is not supported.
> chore(compose): update dashboard to support recent zone changes

- hack/experiments/kube-rbac-proxy-setup/power-monitor-sm.yaml
openshift.io/user-monitoring: true is not meant to be included in the service monitor deployment for hack/experiments/kube-rbac-proxy-setup/power-monitor-sm.yaml as it will result in an error.
> chore: remove user-monitoring label from service monitor

- .github/workflows/check-x-crypto-deps.yaml
This commit disables the x-crypto workflow temporarily to run on pull requests until the workflow and script are fixed
> ci: make the x-crypto workflow temporarily disable

- internal/resource/container.go
- internal/resource/container_test.go
This PR improves container ID detection using deepest cgroup path match for nested containerIDs in cgroup path, typical in kind cluster.
If multiple container IDs are found within a single cgroup path, the changed function prioritizes the one appearing furthest to the right or "deepest" in the path string.
e.g. for a pod created in kind cluster, the cgroup path for the process running in pod is typically like below:
```
0::/system.slice/docker-fd9d0ea06257a9780827cbc7fd92e3812a54fca26d63e191b73610d5d48b9cbd.scope/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-podeab5a334_93fe_48a8_b139_9e8079c1f163.slice/cri-containerd-99f3a16ea25b7724cb56a4f0c0df1113ad9474fbf5545bead97fd5c7f61c13f4.scope
```
the first container (docker) refers to the …
> fix(container): Improve container ID detection using deepest cgroup path match for nested containerIDs in cgroup path

- Makefile
by merging this PR we would:
* be able to set `PRODUCTION` to strip the exporter and validator binaries;
* avoid adding [DWARF](https://dwarfstd.org/doc/DWARF5.pdf) debug information to newer releases;
* reduce the size/footprint of the built binaries;
* still be able to find/follow debug symbols using [Delve](https://github.com/go-delve/delve), should necessary;
* promote the usage of less energy/power consumption.
example using `PRODUCTION` to enable/disable stripped build for the exporter locally:
```bash
$ PRODUCTION=1 make _build_local
$ file _output/bin/linux_amd64/kepler 
_output/bin/linux_amd64/kepler: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=45a457a614ec12d4f18e983f7f28c9bfd3dfc9f3, for …
```
> Introduce PRODUCTION flag to enable/disable stripping binaries after build

- compose/dev/grafana/dashboards/dev/dashboard.json
This commit updates the dashboard to now use the kepler_node_cpu_active metric instead of the kepler_node_cpu when comparing against process level metrics
> chore: update dashboard to use active node cpu metric

- .github/workflows/k8s-equinix.yaml
This commit ensures that the check changes job in the equinix workflow only look for the changes in the actual source code. i.e excluding any go code present in `hack/` folder
> ci: trigger equinix workflow only on source code changes

- .github/k8s/action.yaml
- .github/workflows/k8s-equinix.yaml
- manifests/k8s/daemonset.yaml
This commit ensures that pod level metrics are exported when Kepler is deployed on Kind cluster.
> ci: ensure pod level metrics are exported

- .github/k8s/action.yaml
- .github/workflows/k8s-equinix.yaml
- manifests/k8s/configmap.yaml
This commit ensures that must-gather runs irrespective of failure. It also adds the kube related config to the k8s configmap which was missing in #2153
> ci: ensure must-gather runs irrespective of failure

- .github/workflows/pr-checks.yaml
This commit ensures that the commit-msg precommit runs as part of pre-commit hooks on CI.
Since pre-commit only runs stage hooks by default, we have to explicitly run the commit-msg hook.
> ci: ensure commit-msg precommit runs pr checks

- internal/k8s/pod/pod.go
- internal/k8s/pod/pod_test.go
- internal/resource/informer.go
- internal/resource/mock_procfs_test.go
- internal/resource/procfs_reader_test.go
- use pod cache in pod informer to get container name as in kubernetes cluster
- added tests
> feat(pod): retrieve real container name from pod cache

- cmd/kepler/main.go
- config/config_test.go
I just checked the code in config/config_test.go and internal/server/server_tls_test.go I found that for kepler itself, we enabled TLS config in config structure but not add the invoke for supporting enable TLS in server creation. With this PR, patch this missing part of code.
> chore: Enable TLS in server creation process

- internal/k8s/pod/pod.go
- internal/k8s/pod/pod_test.go
- internal/resource/informer.go
- internal/resource/mock_procfs_test.go
- internal/resource/procfs_reader_test.go
This refactoring improves the API by:
1. Making the "not found" case explicit with a boolean rather than a special error
2. Consolidating related information into a single ContainerInfo struct
Changes:
- modify LookupByContainerID to return (ContainerInfo, bool, error) instead of (PodInfo, string, error)
- Replace PodInfo struct with ContainerInfo that includes container name
- Remove ErrNoPod error, use boolean flag to indicate found/not found
--- 
For more context ... returning found/not-found follows the go idiom of returning bool if an item ins't found instead of returning `error` 
E.g. from docs .. 
```
os.LookupEnv -  func LookupEnv(key string) (value string, ok bool)
sync.Map.Load - func (m *Map) Load(key any) (value any, ok bool)
strings.Cut - string splitting: -   func Cut(s, sep …
```
> refactor(pod): simplify Lookup returning Container Name

- Makefile
This commit updates the make target for building Kepler to remove hardcoded CGO_ENABLED value, enabling downstream builds to configure it for FIPS-compliant build
> chore: allow CGO_ENABLED to be set during build

- cmd/kepler/main.go
- compose/dev/kepler-dev/etc/kepler/config.yaml
- config/config.go
- config/config_test.go
- hack/gen-metric-docs/main.go
- internal/exporter/prometheus/collector/power_collector.go
- internal/exporter/prometheus/collector/power_collector_concurrency_test.go
- internal/exporter/prometheus/collector/power_collector_test.go
- internal/exporter/prometheus/metrics/level.go
- internal/exporter/prometheus/metrics/level_test.go
- internal/exporter/prometheus/prometheus.go
- Add configurable metrics level filtering to control which metric types are exported by the Prometheus exporter
- Implement metrics level configuration via command line flags and YAML config
- Add support for granular control over node, process, container, VM, and pod metrics
- Added tests
Supported metric levels: `node, process, container, vm, pod, all, none`
Usage: 
```
sudo ./bin/kepler  --metrics=node --metrics=pod --kube.enable --kube.node-name="kind-worker2" --kube.config=/home/vimalkum/.kube/config
```
> feat(metrics): add configurable metrics level filtering for Prometheus exporter

- docs/metrics/metrics.md
- internal/exporter/prometheus/collector/power_collector.go
- internal/exporter/prometheus/collector/power_collector_test.go
- internal/monitor/container.go
- internal/monitor/container_power_test.go
- internal/monitor/monitor_test.go
- internal/monitor/pod.go
- internal/monitor/pod_power_test.go
- internal/monitor/process.go
- internal/monitor/process_power_test.go
- internal/monitor/types.go
- internal/monitor/vm.go
- internal/monitor/vm_test.go
This commit extends the functionality to track terminated process (5e91e0fe) to now track all workloads - Containers, Pods, VMs. Changes include:
- Add terminated process/container/VM/pod tracking to Snapshot struct
- Extend power collector to expose terminated workload metrics
- Update monitor components to track terminated workload energy accumulation
- Add comprehensive test coverage for terminated workload scenarios
>  feat(monitor): add terminated workload tracking and reporting

- .github/workflows/pr-checks.yaml
- .pre-commit-config.yaml
This commit adds a custom hook for linting PR commits. It takes commit range from the PR and uses commitlint to lint the commits.
It also removes the need to install commitlint tool separately using npm on CI
> ci: use custom hook for linting PR commits

- .github/workflows/config-change.yaml
This commit adds a new workflow that will check if the Kepler config/
directory has been changed in a PR. If it has, it will comment on the PR
to notify the author to make sure that the relevant changes are also
made to desired places like:
- docs/configuration/configuration.md
- compose/dev/kepler-dev/etc/kepler/config.yaml
- hack/config.yaml
- manifests/k8s/configmap.yaml
> ci: enable comment on PR in case of config change

- compose/dev/kepler-dev/etc/kepler/config.yaml
This commit expose the vm metrics in the config file which was left in https://github.com/sustainable-computing-io/kepler/pull/2187
> chore(compose): expose vm metrics in config

- internal/device/energy_zone.go
- internal/device/energy_zone_test.go
- internal/device/fake_cpu_power_meter.go
- internal/device/rapl_sysfs_power_meter.go
- internal/device/rapl_sysfs_power_meter_test.go
- internal/exporter/prometheus/collector/power_collector.go
- internal/exporter/prometheus/collector/power_collector_concurrency_test.go
- internal/exporter/prometheus/collector/power_collector_test.go
This commit implements `AggregatedZone` to consolidate multiple  EnergyZones with same name (e.g., package zones in multi-socket systems) into single zone. The aggregation also handles  counter wrapping and is transparent to the caller. This enables power attribution across multi-socket systems while maintaining compatibility with single-socket deployments.
Additionally it also solves the zone label which used to have the index suffix as a hack.
Key changes:
- New `AggregatedZone` type that sums energy from multiple zones of the same type
- Proper handling of counter wrapping at MaxEnergy
- Thread-safe energy aggregation with overflow protection
> feat(device/cpu): aggregate multi-socket zones into single zone

- cmd/kepler/main.go
- compose/dev/kepler-dev/etc/kepler/config.yaml
- config/config.go
- config/config_test.go
- docs/configuration/configuration.md
- hack/config.yaml
- internal/monitor/monitor.go
- internal/monitor/options.go
- manifests/k8s/configmap.yaml
Add new configuration option 'maxTerminated' to control the maximum number of terminated workloads (processes, containers, VMs, pods) kept in memory until exported. This prevents unbounded memory growth in high-churn environments.
Changes include:
- Add Monitor.MaxTerminated field with default value of 500
- Add --monitor.max-terminated CLI flag for runtime configuration
- Add YAML configuration support for maxTerminated setting
- Add validation to ensure maxTerminated is non-negative (0 = unlimited)
- Update documentation with usage examples and configuration details
- Pass maxTerminated parameter to PowerMonitor via WithMaxTerminated option
>  feat(monitor): add configurable limit for terminated workloads tracking

- cmd/kepler/main.go
- compose/dev/kepler-dev/etc/kepler/config.yaml
- config/config.go
- config/config_test.go
- docs/configuration/configuration.md
- hack/config.yaml
- manifests/k8s/configmap.yaml
Add support for configurable listen addresses for the web server through both CLI flags and YAML configuration, instead of the hardcoded :28282 default. This change is needed to support a reverse proxy (kube-rbac-proxy) setup where the listen-address will use 127.0.0.1:28282 instead of 0.0.0.0:28282
Changes include:
- Add Web.ListenAddresses []string field to config structure
- Add --web.listen-address CLI flag (repeatable for multiple addresses)
> feat(config): add configurable web server listen addresses

- config/config.go
- internal/device/cpu_power_meter.go
- internal/device/fake_cpu_power_meter.go
- internal/device/rapl_sysfs_power_meter.go
- internal/device/rapl_sysfs_power_meter_test.go
- internal/exporter/prometheus/collector/power_collector.go
- internal/exporter/prometheus/collector/power_collector_test.go
- internal/monitor/clone_test.go
- internal/monitor/container.go
- internal/monitor/container_power_test.go
- internal/monitor/mock_utils.go
- internal/monitor/monitor.go
- internal/monitor/monitor_collection_test.go
- internal/monitor/monitor_concurrency_test.go
- internal/monitor/monitor_snapshot_integration_test.go
- internal/monitor/monitor_test.go
- internal/monitor/node_test.go
- internal/monitor/options.go
- internal/monitor/options_test.go
- internal/monitor/pod.go
- internal/monitor/pod_power_test.go
- internal/monitor/process.go
- internal/monitor/process_power_test.go
- internal/monitor/terminated_resource_tracker.go
- internal/monitor/terminated_resource_tracker_test.go
- internal/monitor/types.go
- internal/monitor/vm.go
- internal/monitor/vm_test.go
Replace unbounded terminated workload maps with bounded, energy-prioritized
tracking system. Automatically retain the N highest energy consuming
terminated resources (processes, containers, VMs, pods) based on optimal
RAPL energy zone selection.
Key changes:
- Add TopEnergyZone() method to CPUPowerMeter interface
- Implement generic TerminatedResourceTracker with min-heap priority queue
- Add Resource interface to Process, Container, VM, and Pod types
- Replace map-based terminated fields with bounded slices in Snapshot
- Add maxTerminated configuration option (default: 500)
> feat: implement energy-based terminated workload tracking

- .github/workflows/config-change.yaml
This commit removes the reboot branch from the config-change workflow's pull request event trigger
> ci: remove reboot branch from config-change workflow

- .github/workflows/config-change.yaml
This commit ensures that config change workflow will only comment if any of the related config files are not updated as part of the PR
> ci: comment only if related config files are not updated

- .github/k8s/action.yaml
- .github/workflows/release.yaml
- .pre-commit-config.yaml
- README.md
- docs/user/installation.md
- manifests/helm/kepler/.helmignore
- manifests/helm/kepler/Chart.yaml
- manifests/helm/kepler/templates/_helpers.tpl
- manifests/helm/kepler/templates/configmap.yaml
- manifests/helm/kepler/templates/daemonset.yaml
- manifests/helm/kepler/templates/namespace.yaml
- manifests/helm/kepler/templates/rbac.yaml
- manifests/helm/kepler/templates/service.yaml
- manifests/helm/kepler/templates/servicemonitor.yaml
- manifests/helm/kepler/values.yaml
Enhancements include:
- Add complete Helm chart under manifests/helm/kepler/ with templates for all Kubernetes resources
- Integrate Helm chart packaging and release into GitHub Actions workflow
- Create comprehensive installation documentation with Helm, Docker Compose, and Kustomize methods
- Update README.md to highlight Helm as recommended Kubernetes deployment method
- Include ServiceMonitor, RBAC, ConfigMap, and DaemonSet templates with configurable values
- Add documentation links for installation, configuration, and metrics guides
- Automated chart versioning and GitHub release integration
> feat: add Helm chart for Kepler deployment

- Dockerfile
- Makefile
This commit modifies the Dockerfile to accept the following build args:
- VERSION
- GIT_BRANCH
- GIT_COMMIT
These args are defined in Makefile and are depend on Git to compute their values.
> chore: add build args to Dockerfile

- .github/ISSUE_TEMPLATE/maintainer_nominate.yaml
This PR updates issue template for maintainer nomination as followings:
- Add new label (nomination)
- Update title and description for nominee introduction, supporting contribution, and governance confirmation
- Add a new field to confirm approval from nominee in case of non-self-nomination
- Add a new field to input the PR link
> chore: update issue template for nomination for more details

- .github/k8s/action.yaml
This commit ensures that must-gather step runs for both K8s deployment methods
Addresses: https://github.com/sustainable-computing-io/kepler/issues/2224
> ci: ensure that must-gather runs for both K8s deployment

- CONTRIBUTING.md
- README.md
pre our discussion on community session, just start this PR for our Gen AI policy discussion.
IMO, I suppose as CNCF "under" LF, and kepler is CNCF project, hence we should follow LF Gen AI policy by default.
I am not been aware of any reason today(2025-07-16) we should have our own community Gen AI policy.
If there any good lesson and learn to build a detail, community specific Gen AI policy with case study, please free to add comments in this PR and I am happy to learn from the case study.
> [docs] Add Gen AI policy in readme and contributing file

- .pre-commit-config.yaml
Use https://github.com/gruntwork-io/pre-commit/blob/master/hooks/helmlint.sh to pre commit hook for helm lint so that developers don't need to install helm in their hosts for pre-commit.
https://github.com/sustainable-computing-io/kepler/issues/2225
> Use precommit hook for helm lint

- .github/compose/action.yaml
- .github/workflows/pr-checks.yaml
This commit updates the PR check workflow to now also run the compose setup and validate if all the services come up and are healthy.
> ci: add validation for compose setup

- GOVERNANCE.md
Add maintainer cycle in governance.md to clarify how to keep maintainer.md up-to-date.
Follow-up task for the issue:
- https://github.com/sustainable-computing-io/kepler/issues/2193
> chore: add maintainer cycle

- docs/user/installation.md
This commit updates the docker compose steps to use `docker compose` instead of `docker-compose` in the installation docs
> docs: update docker compose steps

- docs/user/installation.md
As also highlighted by the `--help` command, the `--config` option does not exist (anymore?) and `--config.file` should be use instead.
> docs: update start command

- internal/resource/vm.go
- internal/resource/vm_test.go
Update VM detection pattern to include libexec/qemu-kvm processes used by CentOS/RHEL systems. The previous pattern only matched qemu-system-* processes, causing VM metrics to be missing on OpenStack deployments using qemu-kvm.
Changes:
- Extend regex pattern to match both bin/qemu-system-* and libexec/qemu-kvm
- Add comprehensive test cases with realistic OpenStack qemu-kvm commands
- Test both UUID and guest name fallback scenarios
Fixes #2276
> fix(vm): add qemu-kvm detection for CentOS/RHEL systems

- docs/developer/proposal/EP-002-MSR-Fallback-Power-Meter.md
- docs/developer/proposal/index.md
Introduces enhancement proposal for adding MSR (Model Specific Register) support as a fallback mechanism when Intel RAPL powercap sysfs interface is unavailable. This improves Kepler's deployment flexibility in environments with restricted powercap access.
The proposal includes:
- Architecture design using powerReader abstraction
- Security considerations for MSR access (PLATYPUS mitigation)
- Phased implementation plan with backward compatibility
- Configuration for opt-in MSR fallback behavior
> docs(proposal): add EP-002 for MSR fallback power meter support

- .pre-commit-config.yaml
- GOVERNANCE.md
- MAINTAINERS.md
- docs/developer/design/architecture/concurrency.md
- docs/developer/design/architecture/data-flow.md
- docs/developer/design/architecture/index.md
- docs/developer/design/architecture/principles.md
- docs/developer/proposal/index.md
- docs/user/configuration.md
This commit adds a new precommit hook which runs the formatter on the tables in the markdown files. This ensures that the tables are formatted consistently.
> docs: keep the formatting for tables consistent

- .github/workflows/profiling.yaml
- hack/reports/profiling.sh
This commit adds a workflow and script to profile `kepler-dev` and `kepler-latest` using Docker compose
The script requires both services to be active, captures CPU/Memory profiles, compare then and generate top cumulative diff. The workflow uses this to comment on the PR.
Steps include:
1. Deploy kepler-dev and kepler-latest via Docker compose
2. Use fake CPU power meter (runs on VM; BM machine post-merge)
3. Run profiling script to collect profiling data
4. Compare CPU/Memory profiles and generate PR comment
> ci: add workflow to profile Kepler versions

- .github/workflows/assign-labels.yaml
- .github/workflows/check-x-crypto-deps.yaml
- .github/workflows/config-change.yaml
- .github/workflows/pr-comment.yaml
- .github/workflows/release.yaml
- .github/workflows/test-and-codecov.yaml
This commit fixes the issue where the config change message was ending with an EOF.
It also updates the rest of the workflows to include `yamllint disable rule` for `truly` values
> ci: remove EOF from the config change message

- docs/user/configuration.md
Update flag names in docs/user/configuration.md to match source code:
- experimental.platform.redfish.node-id → experimental.platform.redfish.node-name
- experimental.platform.redfish.config → experimental.platform.redfish.config-file
> docs: update redfish flag names
