grafana-dashboards/Kepler-Exporter-Dashboard.json
Added one sample Grafana dashboard to visualize the current and total pod energy consumption.
=> Add one sample grafana dashboard

grafana-dashboards/Kepler-Exporter-Dashboard-openshift.json, manifests/openshift/dashboard/04-grafana-dashboard.yaml
- Adding dashboard version formatted for Grafana Operator
- Updating dashboard manifest with matching labels for discovery by Grafana instance
=> Updating dashboard formated for Grafana operator

README.md
Signed-off-by: Parul <parsingh@redhat.com>
=> Edit README to update manifests dir

build/Dockerfile, build/Dockerfile.base, data/normalized_cpu_arch.csv, pkg/power/rapl/source/estimate.go
instead of home made regex, use `archspec` to get cpu model
=> fix estimate based power source

README.md
=> Add missing step to move directories

build/Dockerfile, data/power_model.csv, pkg/collector/reader.go, pkg/model/model.go
regression coefficients are from a linear regression model running on a cascade lake setup
=> plugin regression models

pkg/collector/collector.go, pkg/collector/collector_test.go
This PR is to fix the bug from the previous PR https://github.com/sustainable-computing-io/kepler/pull/98
**Bug:** When func (c *Collector) Describe(ch chan<- *prometheus.Desc) is called, there is no data in the map.
Consequently, no description available when Collect is called.
**Fix:** Generate descriptions by function and calls them at both calls.
=> fix issues in collector.go (including missing podEnergy stats) 

pkg/power/rapl/source/sysfs.go, pkg/power/rapl/source/sysfs_util.go
=> derive missing energy domain from pkg and other domain

Makefile
this is to enable build tags for conditional build
=> enable build tags

.github/workflows/unit_test.yml, .gitignore, Makefile, pkg/cgroup/slice_handler_test.go
Hi Kepler,
Try to add CI test for this repo to run go test with github action.
- one for unit test with bcc
- one for unit test without bcc
- one of unused import removed
Thanks and Regards
Sam
=> GitHub action unit test

Makefile
The PR #103 add the scripts to deploy kepler in a cluster.
This PR adds the support to run the cluster deployment scripts using make commands.
I forgot to include the update in the Makefile in the previous PR
=> Add support for cluster deployment via make command

pkg/pod_lister/suite_test.go
last commit forgot about this file, otherwise the test always success
=> Add test suite for unit test file

.github/workflows/unit_test.yml, Developer.md, Makefile, hack/integration_cluster.sh
add integration test after unit test and just test for deployment
=> add integration test after unit test and just test for deployment

pkg/pod_lister/resolve_container.go
Previous PR #138 has identified that different platforms might have different cgroup path.
Therefore, we need different regex to extract the container id from different cgroup paths.
My system has cgroup v1 and the OS is ubuntu, and after creating a kepler deployment, the cgroup path is as follows:
```
11:blkio:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod481c0ae9_7d40_46dd_b6ca_ba27cb64f87e.slice/docker-28a5e57257f81fcd6d592647dde27e06b53944d58af4fa546ad77a12ce8b41c2.scope
```
Another system, with RHEL and cgroup v1 has another path:
```
13:memory:/system.slice/containerd.service/kubepods-besteffort-pod0043435f_1854_4327_b76b_730f681a781d.slice:cri-containerd:01fd96f7ad292b02a8317cde4ecb8c7ef3cc06ffdd113f13410e0837eb2b2a20
```
This PR adds the logic of another regex …
=> Add support for getting container id from cgroup path of different platforms

pkg/pod_lister/resolve_container.go
Add containerd keyword for some case
updated a log to make error more clear
Related to https://github.com/sustainable-computing-io/kepler/issues/153
=> Add containerd keyword

pkg/config/config.go, pkg/config/config_test.go, pkg/config/suite_test.go
will wait for merge this then follow up with https://github.com/sustainable-computing-io/kepler/issues/179
=> Add UT for config:isCGroupV2

manifests/openshift/dashboard/00-servicemonitoring-kepler.yaml, manifests/openshift/dashboard/01-grafana-operator.yaml, manifests/openshift/dashboard/02-grafana-instance.yaml, manifests/openshift/dashboard/02-grafana-sa.yaml, manifests/openshift/dashboard/03-grafana-datasource-UPDATETHIS.yaml, manifests/openshift/dashboard/03-grafana-sa-token-secret.yaml, manifests/openshift/dashboard/04-grafana-dashboard.yaml, manifests/openshift/dashboard/deploy-grafana.sh
The dashboard manifests need to be updated to kepler ns since this merged: https://github.com/sustainable-computing-io/kepler/pull/174
=> update manifests/openshift dashboard w/ kepler ns

pkg/model/model.go
Retrieves model weights from the Kepler Model Server and uses the weights for energy prediction.
=> Model Server Energy Prediction

manifests/openshift/dashboard/deploy-grafana.sh
@rootfs I missed this one with the last PR, thanks!
With this, I'm finally getting a full healthy deployment in OCP.
=> update openshift dashboard deploy script

.github/workflows/unit_test.yml, README.md
Signed-off-by: Xiaopeng Zhang <zxpbj@cn.ibm.com>
=> docs: add badges in readme

README.md
Signed-off-by: Lu Ken <ken.lu@intel.com>
=> doc: Add a tip for importing pre-generated grafana dashboard

pkg/cgroup/path_handler.go, pkg/cgroup/path_handler_test.go, pkg/cgroup/stat_reader.go, pkg/podlister/cgroup_stats_test.go, pkg/podlister/pod_lister_test.go, pkg/utils/utils.go
=> Add UT for ReadUInt64

.github/workflows/unit_test.yml
Signed-off-by: Ryan Cook <rcook@redhat.com>
=> try to use bot with privs to bypass rules

pkg/cgroup/path_handler.go, pkg/cgroup/path_handler_test.go, pkg/cgroup/stat_reader.go
=> Add UT for ReadKV

Makefile
make test use same tag with build
=> make test use same tag with build

.github/workflows/unit_test.yml, pkg/collector/metrics_test.go
=> try to use docker for test

.github/workflows/unit_test_bcc.yml
=> CI: fix missing job key word in bcc unit test

manifests/kubernetes/keplerExporter-serviceMonitor.yaml
=> remove clusterrole definition prometheus-k8s in manifests

pkg/cgroup/path_handler.go, pkg/cgroup/path_handler_test.go, pkg/cgroup/stat_reader.go
=> Add UT for ReadLineKEqualToV

pkg/config/config.go, pkg/config/config_test.go
=> follow up getKernel version (e.g version 5.4.x.x.x)

.github/workflows/unit_test.yml
correct the typo
Signed-off-by: Huamin Chen <hchen@redhat.com>
=> bot: change name

dev/README.md, hack/build-images.sh
Signed-off-by: huoqifeng <huoqif@cn.ibm.com>
=> multi-arch: create build scripts for multi-arch

manifests/kubernetes/deployment.yaml, manifests/openshift/kepler/01-kepler-install.yaml
This PR updates requested cpu and memory resources in the Kepler daemonset.
Signed-off-by: Parul <parsingh@redhat.com>
=> Update cpu & memory resource in daemon set

pkg/attacher/bcc_attacher.go, pkg/attacher/bcc_attacher_stub.go, pkg/collector/collector.go, pkg/collector/metrics.go, pkg/collector/reader.go
=> add cpu instructions perf metrics

.github/workflows/gogc.yml, .github/workflows/govulnerability.yml, Makefile
=> CI:impl for escapes detect as github action

cmd/exporter.go, manifests/kubernetes/deployment.yaml
related https://github.com/sustainable-computing-io/kepler/issues/237
=> add healthy for exporter

.github/workflows/unit_test_mac.yml, Developer.md, Makefile, pkg/podlister/pod_lister_test.go, pkg/podlister/resolve_container.go, pkg/podlister/util_darwin.go, pkg/podlister/util_linux.go, pkg/power/gpu/gpu_dummy.go, pkg/power/gpu/gpu_nvml.go
By this pr, I try to make `go test ` working on Mac OS for development life easier.
=> Dev:make go test works on Mac

manifests/kubernetes/deployment.yaml, pkg/power/rapl/source/estimate.go
=> allow cpu arch override env var

pkg/collector/reader.go, pkg/podlister/resolve_container.go
=> user podID instead of podName to avoid duplicate

pkg/attacher/bcc_attacher.go
=> Add more log when load ebpf load failed

build/Dockerfile, build/Dockerfile.base, build/Dockerfile.builder
=> kepler base, build, and release images: upgrade to ubi 8.6, bcc 0.24.0, nvidia nvml 520

.github/stale.yml
=> CI: enable stale as a reminder or housekeeping

pkg/cgroup/cgroup_stats.go, pkg/cgroup/cgroup_stats_test.go, pkg/cgroup/path_handler_test.go, pkg/cgroup/resolve_container.go, pkg/collector/container_cgroup_collector.go, pkg/collector/container_hc_collector.go, pkg/collector/metric/stats.go, pkg/collector/metric_collector.go, pkg/config/types.go, pkg/kubelet/kubelet_pod_lister.go, pkg/kubelet/pod_lister_test.go, pkg/kubelet/suite_test.go, pkg/kubelet/util_darwin.go, pkg/kubelet/util_linux.go, pkg/utils/byte_order_test.go, pkg/utils/suite_test.go, pkg/utils/utils.go
=> refactory: refactory from podlister to cgroup

enhancements/README.md, enhancements/TEMPLATE.md
how about this template? it might be more than what's needed but not all sections have to be filled out - I followed [this template from openshift/enhancements](https://github.com/openshift/enhancements/blob/master/guidelines/enhancement_template.md)
/cc
@rootfs
@husky-parul 
@wangchen615
=> Enhancements-process: template and folder 

pkg/collector/container_cgroup_collector.go
=> Add one line log to make debug easier (why energy is 0)

pkg/cgroup/slice_handler.go
Add a log indicate the metrics might be 0 and error fast 
this is helpful for debug and know what happened ahead ..
=> Improve: Add important log to indicate missing file might lead to issue

Makefile
reference to latest CI error, update `go get -u` to `go get -d`
=> CI: fix go get error

Developer.md
=> Doc: update Developer.md

pkg/collector/prometheus_collector.go
**What is the problem?**
The issue #365 described the necessity of report a single metric with the sum of all energy consumption sources.
A big query introduce high overhead in prometheus.
The previous pod metric `pod_curr_energy_millijoule` was reporting the sum of all energy consumption sources, and we should also do that for containers.
**What does this PR do?**
This PR introduce a new metrics `kepler_container_joules_total` 
`kepler_container_joules_total = rapl_package + rapl_ucore + rapl_dram + gpu + other_components`
=> Add new container metric with the sum of all energy consumption sources

pkg/collector/metric_collector.go
=> nit: fit log format

pkg/cgroup/slice_handler.go, pkg/cgroup/slice_handler_test.go, pkg/utils/utils.go
=> fix: search scope file update for not found issue

pkg/cgroup/resolve_container.go, pkg/collector/metric_collector.go, pkg/kubelet/kubelet_pod_lister.go, pkg/utils/byte_order_test.go, pkg/utils/utils.go
=> Test: add test case for package utils

cmd/exporter.go
will use this to investigate performance and scalability issues
=> testing: enable cpu profiling

cmd/exporter.go
**What does this PR do**
The PR #381 introduced the support for CPU profiling, this PR enables MEM profiling.
**Additional Comments**
To get the profiling of kepler running in the k8s cluster, you should edit the manifest to enable it
```
command:
- /usr/bin/kepler
- -address
- 0.0.0.0:9102
- -enable-gpu=true
- -enable-cgroup-id=true
- -v=1
- -cpuprofile=cpu.prof
- -memprofile=mem.prof
```
By default, the profiling will execute for 60s, but you change it with `-profile-duration=seconds`.
To copy the files from the Kepler container:
```
pod=$(kubectl get pod -n kepler | grep kepler-exporter | awk '{print $1}')
kubectl cp -n kepler $pod:cpu.prof cpu.prof
kubectl cp -n kepler $pod:mem.prof mem.prof
```
Example of using the profile:
```
go tool pprof cpu.prof
go tool pprof -alloc_objects …
```
=> Add support to enable mem profiling

pkg/collector/node_energy_collector.go
=> log: add log for node components assignment

cmd/exporter.go, pkg/model/estimator/local/lr.go, pkg/model/model.go
=> use local model if no model server endpoint given

pkg/collector/metric/utils.go, pkg/collector/metric/utils_test.go
=> Test: Add test case

.github/workflows/unit_test.yml, pkg/collector/metric/container_metric.go, pkg/collector/metric/container_metric_test.go, pkg/collector/metric/node_metric.go, pkg/collector/metric/node_metric_test.go, pkg/model/estimator/local/ratio.go
It seems github agent removed bcc header files, hence I follow bcc official guide to install bcc headers.
ref to https://github.com/iovisor/gobpf we have to install bcc lib before use it.
=> Test: add test for metric package

pkg/power/components/source/rapl_msr_util.go
For #373 
feel free to close it.
=> Experimental code for weird case of physical_package_id

Makefile
potentially fix https://github.com/sustainable-computing-io/kepler/issues/348
@SamYuan1990 how to trigger github action locally? e.g I want to build image with my PR through github action..
=> fix: add --always to potentially fix git commit

.github/workflows/integration_test.yml, hack/build-manifest.sh, hack/cluster-deploy.sh, manifests/kubernetes/ci/kustomization.yaml, manifests/kubernetes/ci/patch-ci.yaml
part of #395
create kustomization for CI usage, adjust CI script accordingly.
=> CI: create CI version kustomization

pkg/collector/metric_collector.go
=> log: node energy report wrong info

pkg/bpfassets/attacher/attacher_suite_test.go, pkg/bpfassets/bpfassets_suite_test.go, pkg/manager/manager_suite_test.go, pkg/power/power_suite_test.go, pkg/version/version_suite_test.go
=> test: add ginkgo test suite for pkgs

pkg/collector/metric/container_metric.go
=> fix: update log to avoid confusion (0 process) ==> (0 active process)

pkg/kubelet/kubelet_pod_lister.go, pkg/kubelet/pod_lister_test.go
=> UT: add ut for listMetrics

pkg/collector/container_hc_collector_test.go
=> ut: add UT for container_hc_collector_test part I

Makefile, pkg/manager/manager_test.go
=> Test: add a sample test case for pkg manager

pkg/collector/container_hc_collector_test.go, pkg/collector/metric_collector_test.go
=> impl for some nit test cases

pkg/collector/container_hc_collector.go, pkg/collector/metric/node_metric.go, pkg/collector/metric_collector.go, pkg/collector/node_energy_collector.go, pkg/manager/manager.go
=> refactory: remove a TODO related to CPUFrequency

Contributors.md
@nikimanoledaki @jiangphcn
@sustainable-computing-io/reviewer
=> contributors: add Niki and Peng Hui

pkg/model/container_power_test.go, pkg/model/model_test.go
=> remove a TODO regarding energy consumption in UT

pkg/collector/metric/container_metric.go
=> fix: add disks handling processing

.github/workflows/release.yml
Signed-off-by: Parul <parsingh@redhat.com>
=> Create Release v0.4 GH Workflow

.github/workflows/release.yml
Signed-off-by: Parul <parsingh@redhat.com>
=> Release CI: Fix push image to registry

cmd/exporter.go, pkg/power/components/power.go
=> fix: show power model collection logs

README.md
This is the meeting info
```
Topic: Kepler biweekly meeting
Meeting note: [https://hackmd.io/MaTlO-5RQNShIsXGO8qyyg](https://www.google.com/url?q=https://hackmd.io/MaTlO-5RQNShIsXGO8qyyg&sa=D&source=calendar&ust=1673211239064682&usg=AOvVaw1giY2vDnbzOSBEMAJM3zXW)
Time: Jan 10, 2023 08:00 AM Eastern Time (US and Canada)
Every 2 weeks on Tue, until Apr 4, 2023, 7 occurrence(s)
Jan 10, 2023 08:00 AM
Jan 24, 2023 08:00 AM
Feb 7, 2023 08:00 AM
Feb 21, 2023 08:00 AM
Mar 7, 2023 08:00 AM
Mar 21, 2023 08:00 AM
Apr 4, 2023 08:00 AM
Please download and import the following iCalendar (.ics) files to your calendar system.
Weekly: [https://us06web.zoom.us/meeting/tZApfumrrzgpHdwUQbkSOj0zpoGveKMMvxaD/ics?icsToken=98tyKuGsqjIqGdWWsx6PRpwIBor4c-nzmHZegqdKqS7nCBN8aFPsJu1lJLdUPfXG](https://www.google.com/url …
```
=> community meeting: update with Q1 2023 meeting

Makefile, build/Dockerfile, build/Dockerfile.builder, hack/build-manifest.sh, manifests/config/exporter/kustomization.yaml, manifests/config/exporter/patch/patch-rootless.yaml, pkg/bpfassets/perf_event_bindata.go
=> feature: rootless deployment

e2e/e2e_metric_test.go, pkg/bpfassets/perf_event_bindata.go, pkg/collector/prometheus_collector.go
part of #495  (kubelet part)
just want to check whether it's ok to do so
=> metrics: add kubelet metrics for container

bpfassets/perf_event/perf_event.c, pkg/bpfassets/perf_event_bindata.go
=> ebpf: fix cpu time and HW stats for running processes

pkg/cgroup/resolve_container.go, pkg/utils/util_darwin.go, pkg/utils/util_linux.go
part of effort of https://github.com/sustainable-computing-io/kepler/issues/510
=> refactory: move util files from kubelet to utils

pkg/model/model.go
make logs from 
model.go:85] Model Config CONTAINER_TOTAL: {false}
to
model.go:85] Model Config CONTAINER_TOTAL: {UseEstimatorSidecar:false SelectedModel: SelectFilter: InitModelURL:}
=> nit: More logs to makre it readable

pkg/collector/metric/node_metric.go
=> fix: make log about node energy accurate

build/Dockerfile, data/README.md, doc/dev/prepare_dev_env.sh, pkg/bpfassets/perf_event_bindata.go, pkg/power/components/source/estimate.go
some discussion https://github.com/sustainable-computing-io/kepler/issues/530#issuecomment-1425102495
=> fix: remove power_data, power_model csv file usage

pkg/model/benchmark_test.go, pkg/model/container_power.go
add benchmark testing for UpdateContainerEnergyByTrainedPowerModel
hence by this pr we covered benchmark testing for updateContainerEnergy
=> add benchmark testing for UpdateContainerEnergyByTrainedPowerModel

pkg/collector/metric/benchmark_test.go
=> add benchamrk for AddNodeResUsageFromContainerResUsage

cmd/exporter.go, pkg/bpfassets/attacher/bcc_attacher.go, pkg/bpfassets/perf_event_bindata.go, pkg/config/config.go, pkg/power/accelerator/gpu.go, pkg/power/components/power.go, pkg/power/components/source/rapl_msr_util.go
=> enhance: add enable MSR flag to allow MSR model

Makefile, build/Dockerfile, pkg/bpfassets/perf_event_bindata.go, pkg/model/container_power.go, pkg/model/container_power_test.go, pkg/model/estimator/local/lr.go, pkg/model/model_test.go, pkg/model/node_component_power.go
=> fix: put json file into container image to avoid URL access

.github/rpmbuild.yml, .gitignore, packaging/rpm/kepler.spec
This PR will create Kepler stand-alone binary for  `arch x86_64`.
=> Kepler Stand-Alone Binary Packaging

.github/workflows/image.yml, .github/workflows/integration_test.yml, .github/workflows/release.yml, .gitignore, Makefile, build/Dockerfile, doc/dev/README.md, go.mod, hack/cluster-sync.sh
1. refine make for tidy.
1.a update lint and fmt same with CI
1.b update make script into ### env define ### ### Default ### ### build container ### ### build binary ### ### toolkit ### 5 parts.
2. refine docker to get ready with buildx.
3. use buildx in GHA to build multiple CPU arch images.
will use https://github.com/docker/build-push-action this GHA for image build and push
=> CI: try to refine build scripts in docker and make to get ready for buildx

pkg/model/estimator/local/ratio.go
this function used by container/process, use node key word is not helpful to understand the logic
=> refactory: update param as this function used by process as well

.github/workflows/integration_test.yml, Makefile, pkg/cgroup/cgroup_interface.go, pkg/cgroup/cgroup_stats_darwin.go, pkg/cgroup/cgroup_stats_linux.go, pkg/cgroup/cgroup_stats_test.go, pkg/collector/metric/container_metric.go, pkg/collector/metric/stats.go, pkg/collector/metric/stats_test.go
- remove unused tag in integration test
- enhance mac unit test
- convert CCgroupStatHandler to interface to avoid if else check on CPU stack
- remove GetAvailableCGroupMetrics
=> nit fixing after 609

pkg/collector/metric_collector_test.go, pkg/collector/prometheus_collector.go
=> enable: add container.ContainerID into prometheus metrics

pkg/power/components/source/rapl_msr_util.go
=> fix: avoid continue open file in MSR model

.github/workflows/unit_test.yml, .github/workflows/unit_test_bcc.yml
try to provide bcc and headers in CI for unit test on linux
=> try to provide bcc and headers in CI for unit test on linux

build/Dockerfile.base, build/Dockerfile.base.arm64, pkg/collector/metric/node_metric.go
The GPU dynamic power calculation is missing.
This PR is adding it.
=> Add the missing gpu dynamic power calculation

build/Dockerfile
=> dockerfile: bump up base image using cuda 12.1

cmd/exporter.go, pkg/bpfassets/attacher/bpf_perf.go, pkg/collector/container_hc_collector.go
=> bpf: filter ENOENT error in batch delete

pkg/collector/metric/node_metric.go, pkg/collector/metric/node_metric_test.go, pkg/model/estimator/local/ratio.go, pkg/model/estimator/local/ratio_process.go
=> fix: avoid use metrics if HW counter not open

.github/workflows/image_pr.yml
ref https://github.com/actions/checkout/tree/v3/#checkout-pull-request-head-commit-instead-of-merge-commit try to use github specific to check out code and meanwhile for container image tag.
=> CI add specific build job

pkg/collector/prometheus_collector.go
=> fix: typo lead to idle and dyn calc incorrect

pkg/cgroup/cgroup_stats_linux.go
during check other code, found this seems a typo
=> fix: V12 => V2

bpfassets/perf_event/perf_event.c, pkg/bpfassets/attacher/bcc_attacher.go, pkg/bpfassets/attacher/bcc_attacher_stub.go, pkg/bpfassets/attacher/bpf_perf.go, pkg/bpfassets/perf_event_bindata.go, pkg/collector/container_hc_collector.go, pkg/config/config.go
=> bpf: add batch table get

enhancements/CICDv1.md
related with https://github.com/sustainable-computing-io/kepler/pull/711
https://github.com/orgs/sustainable-computing-io/projects/2?pane=issue&itemId=28750581
=> CI/CD Pipeline enhancement and tag

Makefile, hack/cluster-up.sh
By this PR, we hope to check local-dev-cluster is there or not before checkout.
=> resolve #721

.github/workflows/integration_test.yml, .github/workflows/unit_test.yml
a part as pre-request of https://github.com/sustainable-computing-io/kepler-action/pull/46
=> enable version of customer action

Makefile, hack/common.sh, pkg/collector/metric/utils.go
See #740 , current fix could resolve the issue 1-3, issue 4 is waiting for community's comments.
=> Fix error/warning msg in integration test.

e2e/e2e_metric_test.go
fixing e2e failure, per @marceloamaral diagnosis
=> e2e: check nodeInfo -> info to match #694

manifests/config/exporter/exporter.yaml, pkg/bpfassets/perf_event_bindata.go, pkg/config/config.go, pkg/model/container_power.go, pkg/model/container_power_test.go, pkg/model/estimator/local/lr.go, pkg/model/model_test.go
=>  avoid set CONTAINER_COMPONENTS_INIT_URL by default

pkg/collector/metric/utils.go
1. The original fix (https://github.com/sustainable-computing-io/kepler/pull/741/files#diff-d4aa22f63afd6e12ec7a6c1c79d1764dfd15243edb4d631a3ae093e32dce387aL131) is not correct. 
The correct way should be: add cmd.Wait() to guarantee resource release.
2. Add more logs for debug use in this PR.
Signed-off-by: Jie Ren <jie.ren@intel.com>
=> Refix the second issue mentioned in #740

pkg/collector/container_hc_collector.go
this the error message from #767
=> bpf: ignore IsNotExist error when deleting from ebpf map

.github/workflows/gofmt.yml, .github/workflows/gogc.yml, .github/workflows/golangci-lint.yml, .github/workflows/govulnerability.yml, .github/workflows/image.yml, .github/workflows/integration_test.yml, .github/workflows/local_env.yml, .github/workflows/unit_test.yml, .github/workflows/unit_test_mac.yml
I hope by this PR fix #773 
as try to add readme file in ignore path to avoid bot update trigger a pipeline job.
=> extend ignore path

bpfassets/perf_event/perf_event.c, pkg/bpfassets/perf_event_bindata.go
this fix is to track processes on-cpu time, this is inspired by the usage in [this](https://github.com/iovisor/bcc/blob/master/tools/cpudist.py) bcc tool
=> ebpf: track process cpu time at tgid level on all CPUs

CONTRIBUTING.md, Makefile
- fix: remove non-printable character
- fix: set GOBIN even if GOPATH was set but not GOBIN
- fix: proper syntax for ENVTEST_ASSETS_DIR
=> fix: minor issues

.github/workflows/release.yml
=> release: release both bcc and libbpf images

pkg/collector/prometheus_collector.go
=> expose DynEnergyInOther to Prometheus

pkg/model/estimator/local/ratio.go
=> ratio power mode: add OTHER and UNCORE power

manifests/config/exporter/exporter.yaml, pkg/model/model.go, pkg/model/process_power.go
=> By default use Kepler built-in models

e2e/e2e_metric_test.go
=> Fix logic issue in e2e metric test, add console print for debuggability

.github/workflows/integration_test.yml, .github/workflows/integration_test_libbpf.yml, Makefile, hack/cluster-down.sh, hack/verify.sh
=> CI enhancement: Add cleanup job, add necessary wait for Kepler ready

pkg/bpfassets/attacher/bcc_attacher.go, pkg/bpfassets/perf_event_bindata.go
=> ignore error string directly

.github/workflows/integration_test.yml, .github/workflows/integration_test_libbpf.yml, hack/verify.sh
This PR improves logging for CI. Related [issue](https://github.com/sustainable-computing-io/kepler/issues/826)
=> Improve logging for CI

pkg/bpfassets/attacher/bcc_attacher.go
=> bcc: fix error parsing

pkg/config/config.go, pkg/model/container_power.go
=> Use configurable metric for UNCORE and OTHER in ratio model

pkg/bpfassets/attacher/bcc_attacher.go, pkg/bpfassets/attacher/common.go, pkg/bpfassets/attacher/libbpf_attacher.go
fix #825 #657
A test image is built [quay.io/sustainable_computing_io/kepler:pr_831](quay.io/sustainable_computing_io/kepler:pr_831)
=> libbpf: support batch get and delete values

build/Dockerfile, build/Dockerfile.bcc.kepler, build/Dockerfile.libbpf.kepler, doc/dev/prepare_dev_env.sh, manifests/config/exporter/patch/patch-estimator-sidecar.yaml, manifests/config/model-server/model-server.yaml, pkg/model/estimator/local/lr_test.go, pkg/model/model_test.go
=> image: retrieve pretrained models from test_models branch

.github/workflows/gosec.yml, .github/workflows/govet.yml, .github/workflows/scorecard.yml
Fixes #724
cc: @rootfs @SamYuan1990
=> adding github actions to implement gosec, govet and ossf scorecard checks in kepler

manifests/README.md
This PR updates the readme for deploying Kepler
=> update readme to deploy Kepler

ADOPTERS.md
Feat: add ADOPTERS.md 
fixes #845 
should not be merged before https://github.com/sustainable-computing-io/kepler-doc/pull/95
=> Feat: add ADOPTERS.md

pkg/bpfassets/attacher/bcc_attacher.go, pkg/bpfassets/attacher/libbpf_attacher.go
The issue #916 pointed that libbpf and bcc attach functions are reporting different logs.
This PR make their logs similar, include more explanation in the log and change the error message to warning message.
=> Change ebpf error logs to warnings

.github/workflows/image.yml
Try to fix image build CI with correct value settings.
=> try to rename secrets to correct name

.github/ISSUE_TEMPLATE/document.yaml
Same changes as were merged here https://github.com/sustainable-computing-io/kepler-model-server/pull/164
=> fixed typo/clarified doc issue template

pkg/config/config.go
Fix the bug in the function IsEstimatedIdlePowerEnabled
=> Fix IsEstimatedIdlePowerEnabled function

.github/workflows/daily.yml, .github/workflows/rpm.yml
@rootfs , I have an idea, that push a daily build for rpm package on artifact, could you please help review this PR and let's have a try?
=> try to enable daily rpm build and save on artifact

.github/workflows/rpm.yml
=> CI: update RPM build with arch info

.github/ISSUE_TEMPLATE/document.yaml
id conflict issue leads to preview failure and not available when submit issue.
=> Fix document issue template preview issue

build/Dockerfile.bcc.base, build/Dockerfile.bcc.base.amd64, build/Dockerfile.bcc.base.arm64, build/Dockerfile.bcc.base.s390x, build/Dockerfile.libbpf.base, build/Dockerfile.libbpf.base.amd64
this is pre-requisite for #1007
=> base: add xgboost library

packaging/rpm/kepler.spec
=> Add additional json files to build rpm

.github/workflows/golang.yml
=> CI check for vendor folder

packaging/rpm/kepler.spec
replacing bcc based rpms
here is the demo
[![asciicast](https://asciinema.org/a/623618.svg)](https://asciinema.org/a/623618)
=> build: update rpm build spec to build libbpf based rpm

.github/workflows/image_base.yml, Dockerfile.base
- Adds Dockerfile.base which installs everything required to build kepler code base
- Updated github workflow to build and push the base image
=> chore(build): Add base image Dockerfile for building kepler with libbpf

Makefile, e2e/integration-test/e2e_metric_test.go, e2e/integration-test/e2e_suite_test.go, e2e/integration-test/restapicheck_test.go, e2e/platform-validation/platform_validation_metric_test.go, hack/verify.sh
This PR updates e2e tests and `verify.sh` script
=> chore: update e2e tests

hack/cluster-deploy.sh
This PR adds the steps back that were removed in refactor PR: https://github.com/sustainable-computing-io/kepler/pull/1089/files#diff-be559fd8e5c86cd4bfb53d341659b318f4c5963a8da53ca413c19528590edd4b
=> fix: update steps

README.md
enable OpenSSF Scoredcard badge here is our OpenSSF Scordcard info https://securityscorecards.dev/viewer/?uri=github.com/sustainable-computing-io/kepler
=> enable OpenSSF Scoredcard badge

.github/workflows/developer_local.yml, Makefile
ref to #1128 add local container test in CI to avoid it break.
=> [CI] ref to #1128 add local container test in CI to avoid it break.

.github/workflows/image.yml, .github/workflows/image_base.yml, .github/workflows/unit_test.yml
Reverts sustainable-computing-io/kepler#1160
@SamYuan1990 @vimalk78 we need to have an arm64 kepler builder image too
=> Revert "[tbd][CI] security update, daily job fix, try to recover arm64 support from base."

Makefile, hack/build-manifest.sh, hack/tools.sh
This PR updates make tools to install kubectl
=> chore: update make tools to install kubectl

.github/workflows/image_base.yml
[CI] fix daily base image build by remove missing make rule
=> [CI] fix daily base image build by remove missing make rule

.github/workflows/unit_test.yml
[CI] fix tj actions cve by version bump up
=> [CI] fix tj actions cve by version bump up

pkg/metrics/process/metrics.go
=> fix context typo

.github/workflows/image_base.yml, .github/workflows/pull_request.yml, build/Dockerfile, build/Dockerfile.builder
tested with arm64 https://github.com/sustainable-computing-io/kepler/actions/runs/7422356767/job/20197478578?pr=1169
=> [CI][don't merge] base image multiple arch support

.github/workflows/image_base.yml, .github/workflows/pull_request.yml
ref https://github.com/sustainable-computing-io/kepler/pull/1169#issuecomment-1884883196 switch CI hook back to normal.
=> [CI] switch CI trigger back to normal

hack/build-manifest.sh
This PR updates the `build-manifest.sh`
=> fix: update build-manifest script

hack/build-manifest.sh
This PR: 
* exporting path first to avoid duplicate installing tools
* fixed Prometheus role deploy bug
=> fix: update manifest script

bpfassets/libbpf/Makefile
fix build error 
https://github.com/sustainable-computing-io/kepler/actions/runs/7642380579/job/20821864213
=> bpf: fix target arch for arm

build/Dockerfile.builder
fix https://github.com/sustainable-computing-io/kepler/actions/runs/7652344579/job/20851923853
=> rpm: add rpmautospec to auto generate changelog

build/Dockerfile.builder
this is previously missed 
cc @vimalk78
=> builder: add epel so to install rpmautospec

pkg/collector/energy/node_energy_collector.go, pkg/collector/stats/types/types.go
ACPI energy is delta value. Need to use SetDelta instead of SetAggr. Also, I add description in the function to separate between Set and Add Delta. 
=> fix acpi energy set to delta

pkg/metrics/container/metrics.go
=> metrics: change kepler_container_joules_total from mJ to J

pkg/model/model.go
fixing https://github.com/sustainable-computing-io/kepler/pull/1089#discussion_r1489503261
=> Remove duplicated function call

pkg/model/estimator/local/regressor/exponential_test.go, pkg/model/estimator/local/regressor/linear_test.go, pkg/model/estimator/local/regressor/logarithm_test.go, pkg/model/estimator/local/regressor/logistic_test.go, pkg/model/estimator/local/regressor/model_weights.go, pkg/model/estimator/local/regressor/regressor.go, pkg/model/estimator/local/regressor/regressor_test.go
To fix failed golangci from previous PR https://github.com/sustainable-computing-io/kepler/pull/1247
=> fix regressor golangci

pkg/sensors/accelerator/gpu/source/gpu_dcgm.go
K8s Clusters with GPUs typically has DCGM exporter installed, which will deploy dcgm daemon in each node.
However, only one  dcgm daemon can be running at the same time. In the case, the standalone version should be used to connect to the already running daemon. However, if dcgm daemon is not running, we can use the embedded, which will start an embedded daemon.
Fix issue #1243
=> Add support for both standalone and embedded starting mode

pkg/sensors/accelerator/gpu/source/gpu_dcgm.go
multiprocessorCountRatio should be float, otherwise it will 1 or 0
=> dcgm: use ratio as float

.github/workflows/image.yml, .github/workflows/rpm.yml, build/Dockerfile
1. Fix rpm daily build issue as CI value setting.
2. Refactor x86 related docker build process.
3. Refactor x86 image related CI.
=> [CI] refactor CI on dockerfile and image CI process

.github/workflows/image.yml, build/Dockerfile
make image build support with metric to make our life easier.
fix error in x86 build logic in docker.
=> [CI] Image refactor as build with metric

pkg/config/config.go
Currently a config file containing `true` (without \n at the end) is different to
```
true
```
This commit fixes the issue by trimming spaces (including newlines) when reading a config
=> fix(config): trim spaces and new lines in config

pkg/collector/resourceutilization/accelerator/process_gpu_collector.go, pkg/sensors/accelerator/gpu/power.go, pkg/sensors/accelerator/gpu/source/gpu_dcgm.go, pkg/sensors/accelerator/gpu/source/gpu_dummy.go, pkg/sensors/accelerator/gpu/source/gpu_nvml.go, pkg/sensors/accelerator/gpu/source/type.go
The current code is not listing and getting the process in the MIG device handler.
This code get the MIG device handler and store only the necessary data.
=> Fix listing and using the MIG device handler

pkg/sensors/accelerator/qat/power.go
Recently as review our logic at qat error and the package.
I found some logic change in #1316, hence this PR is to revert those logic part back.
=> update QAT logic process, revert logic change at #1316

hack/cluster.sh
update cluster up script to use latest local dev cluster when set up locally.
=> dev: bump up local dev cluster version

build/Dockerfile.builder
This is to allow #1371 to pass
=> add habana library into builder image

build/Dockerfile.builder
Docker build on CI failed. So i have to use a different method to just install habana tool
https://github.com/sustainable-computing-io/kepler/pull/1374#issuecomment-2072510717
=> fix habana installation

cmd/exporter/exporter.go
The commit - f5910e28d4f0b adds pprof HTTP endpoints to kepler thus removing the need to support -cpu-profile or -memory-profile explicitly.
See also: https://github.com/sustainable-computing-io/kepler/pull/1383
=> cleanup startup-profile replaced by pprof http endpoint

.github/workflows/image.yml, .github/workflows/integration_test.yml, Makefile, build/Dockerfile, go.mod, go.sum, hack/build-manifest.sh, manifests/k8s/config/exporter/exporter.yaml, manifests/k8s/config/exporter/kustomization.yaml, manifests/k8s/config/exporter/patch/patch-habana.yaml, pkg/metrics/metricfactory/metric_factory.go, pkg/sensors/accelerator/gpu/gpu.go, pkg/sensors/accelerator/gpu/power.go, pkg/sensors/accelerator/gpu/source/gpu_habana.go, pkg/sensors/accelerator/gpu/source/type.go, pkg/sensors/accelerator/gpu/variables.go, pkg/sensors/accelerator/gpu/variables_habana.go, vendor/github.com/HabanaAI/gohlml/CONTRIBUTING.md, vendor/github.com/HabanaAI/gohlml/LICENSE, vendor/github.com/HabanaAI/gohlml/README.md, vendor/github.com/HabanaAI/gohlml/hlml.go, vendor/github.com/HabanaAI/gohlml/hlml.h, vendor/modules.txt
Tested on a setup with Habana
```
kepler_node_gpu_joules_total{instance="",mode="dynamic",package="0",source="habana"} 206.895
kepler_node_gpu_joules_total{instance="",mode="dynamic",package="1",source="habana"} 345.609
kepler_node_gpu_joules_total{instance="",mode="dynamic",package="2",source="habana"} 128.661
kepler_node_gpu_joules_total{instance="",mode="dynamic",package="3",source="habana"} 362.46
kepler_node_gpu_joules_total{instance="",mode="dynamic",package="4",source="habana"} 157.596
kepler_node_gpu_joules_total{instance="",mode="dynamic",package="5",source="habana"} 327.219
kepler_node_gpu_joules_total{instance="",mode="dynamic",package="6",source="habana"} 299.94
kepler_node_gpu_joules_total{instance="",mode="idle",package="0",source="habana"} 1314.276 …
```
=> support Habana GPU

manifests/compose/dev/grafana/dashboards/dev/dashboard.json
=> dev(dashboard): reduce size of ratio panels

Makefile
fixes : #1428 
Cc: @dave-tucker
=> fix ginkgo version in Makefile

bpfassets/libbpf/include/bpf/bpf_helper_defs.h, bpfassets/libbpf/include/bpf/bpf_helpers.h, hack/libbpf-headers.sh
change the script to pull v1.3.0 libbpf headers
update the libbpf headers
Cc: @dave-tucker @rootfs
=> update hack/libbpf-headers.sh script to pull v1.3.0

.github/workflows/review_bot.yml
The secrets are added to the repo
=> add PR review bot

.github/ISSUE_TEMPLATE/maintainer_nominate.yaml
ref https://github.com/cncf/tag-env-sustainability/issues/367 and discussion on community meeting.
let's have github issue and template for new maintainer vote.
=> provide a simple template for maintainer nominate

pkg/collector/stats/utils.go
fix #1347 
we no longer package archspec.
=> chore(collector)use pmu name to get arm cpu id since archspec does not help here

manifests/compose/dev/compose.yaml, manifests/compose/mock-acpi/compose.yaml, manifests/compose/validation/metal/compose.yaml
This PR adds build arguments to the Kepler image in docker-compose
=> feat(compose): add build arguments for Kepler image

bpfassets/libbpf/src/kepler.bpf.c, pkg/bpf/exporter.go, pkg/bpf/exporter_stub.go, pkg/bpf/test_utils.go, pkg/bpf/types.go, pkg/collector/metric_collector.go, pkg/collector/stats/stats.go, pkg/config/config.go, pkg/config/types.go, pkg/metrics/metricfactory/metric_factory.go, pkg/metrics/node/metrics.go
Removes a number of unused maps from the eBPF code.
Removes unused functions and config options from the userland code.
Fixes: #1405
=> chore: Remove CPU Ref Cycles related code

e2e/tools/validator/query.json, e2e/tools/validator/src/validator/cases/__init__.py, e2e/tools/validator/src/validator/cli/__init__.py, e2e/tools/validator/src/validator/prometheus/__init__.py
Current script only keeps compound prom query. This PR makes the raw query results persisted so we can use them to replay the validation.
=> chore(validator): add raw queries

bpfassets/libbpf/src/kepler.bpf.c
It turns out that RHEL is carrying a patch that increases the size of the unreadable tracepoint-common area from 8 bytes to 12 bytes. This means that our reads into the context area are off, causing the probes to return invalid data.
To fix this we use BTF-Defined Raw Tracepoints that were added in Kernel 5.5 (less than our 5.12 minimum version). This type of tracepoint program uses BTF and CO-RE to access arguments from the tracepoint context.
Fixes: #1530
=> fix(bpf): Use BTF-Defined Raw Tracepoints

e2e/tools/validator/validator.yaml.sample
This PR improves the `validator.yaml.sample` by:
* Adding meaningful comments
* Formats and remove extra whitespaces
=> fix(validator): improve the validator config sample

manifests/compose/validation/metal/grafana/dashboards/validation/dashboard.json
Add mode variable to grafana dashboards in order to enable switch between dynamic and idle power comparison.
=> feat(validator): Add mode variable to Grafana Dashboards

.github/workflows/validator.yml, e2e/tools/validator/Makefile, e2e/tools/validator/src/validator/cli/__init__.py, e2e/tools/validator/src/validator/cli/options.py, e2e/tools/validator/src/validator/prometheus/__init__.py, e2e/tools/validator/src/validator/specs/__init__.py, e2e/tools/validator/src/validator/stresser/__init__.py, e2e/tools/validator/src/validator/validations/__init__.py, e2e/tools/validator/tests/validator/config/__init__.py, e2e/tools/validator/tests/validator/prometheus/__init__.py, e2e/tools/validator/tests/validator/prometheus/test_prometheus.py, e2e/tools/validator/tests/validator/stresser/__init__.py
This commit addresses and resolves various linting issues in the validator module Additionally, it includes the following improvements:
- Add a new make target to run the linter.
- Add `__init__.py` to the `tests/validator` directory to resolve the linting issue: implicit-namespace-package (INP001).
- Suppress certain linting issues that are intentional or not applicable in our context.
=> fix(validator): resolve linting issues

e2e/tools/validator/README.md, manifests/compose/validation/README.md
This commit improves the README with detailed instructions on how to set up and run the Docker Compose for VM validations. Additionally, it updates the steps required to launch the validator tool
=> docs(validator): update the documentation for running the validator

e2e/tools/validator/pyproject.toml, e2e/tools/validator/src/validator/cli/__init__.py, e2e/tools/validator/src/validator/prometheus/__init__.py, e2e/tools/validator/tests/validator/prometheus/test_prometheus.py
This commit captures node info and timestamp information so that MSE and MAPE can be recomputed from the json dump.
=> chore(validator): capture node info and series timestamp

pkg/model/process_energy.go
=> chore: remove unused variable in addEstimatedEnergy

pkg/kubernetes/watcher.go
This uses a workqueue as a layer of indirection between:
- Events coming in from the K8s ListWatcher
- The handlers that update ContainerStats
This is necessary for 2 reasons.
1. SharedIndexInformers do not deal well with large backlogs of events
2. ObjListWatcher.Mx is shared 😱 with the Collector.Mx. Meaning that we pause processing K8s events while preparing metrics... and similarly we pause preparing metrics when handling a K8s event.
We should revisit the design of the watcher to avoid sharing both `ContainerStats` and `Mx` as this is not a great design.
=> feat(kubernetes): Use workqueues

e2e/tools/validator/.gitignore, e2e/tools/validator/src/validator/cli/__init__.py, e2e/tools/validator/src/validator/prometheus/__init__.py, e2e/tools/validator/src/validator/specs/__init__.py, e2e/tools/validator/tests/validator/prometheus/test_prometheus.py, manifests/compose/validation/metal/grafana/dashboards/validation/dashboard.json
All test results are stored in a single TestResult object so that generation of 
various formats (e.g. json) can be done easily. 
Also Fixes: 
https://github.com/sustainable-computing-io/kepler/issues/1649
To verify values produced by Validator, now the Model Validation dashboard can be used. 
* Fixes Model Dashboard to correctly calculate MAPE and MSE for the selected time range
=> chore(validator): store test result in an object

.commitlintrc.js, .github/workflows/pre-commit.yml, .pre-commit-config.yaml, e2e/tools/validator/README.md, manifests/compose/validation/README.md, manifests/compose/validation/dockerfiles/Dockerfile.scaphandre
=> chore: pre-commit updates

hack/verify.sh
=> check metrics before and after e2e tests

.github/workflows/mock_acpi.yml, ansible/inventory.yaml, ansible/mock_acpi_playbook.yaml, ansible/setup.yaml
This commit introduces a workflow for testing ACPI functionality using Equinix self-hosted runners. The workflow deploys Kepler using mock-acpi compose setup and runs validator to ensure functionality.
Key-features:
- Workflow is triggered on pull requests that include a specific commit message `/test-acpi`.
- Environment setup is handled by ansible.
=> feat(ci): implement mock-ACPI workflow

manifests/compose/dev/compose.yaml, manifests/compose/dev/grafana/dashboards/dev/power-source-comparison.json, manifests/compose/dev/override.yaml
-  added power source comparison dashboard comparing core/uncore/package power reported by kepler and node-exporter
- fixed review comments from previous PR #1727
=> chore(compose): added power source comparison dashboard

e2e/tools/validator/pyproject.toml, e2e/tools/validator/src/validator/cli/__init__.py, e2e/tools/validator/src/validator/prometheus/__init__.py
=> chore(validator): add graphs to markdown report

pkg/sensors/accelerator/device/sources/dcgm.go, pkg/sensors/accelerator/device/sources/habana.go, pkg/sensors/accelerator/device/sources/nvml.go
fixes the habana image build failure: https://github.com/sustainable-computing-io/kepler/actions/runs/10677475719/job/29592701656#step:7:1579
=> fix: habana image build

e2e/tools/validator/scripts/stressor.sh, e2e/tools/validator/src/validator/cli/__init__.py, manifests/compose/validation/metal/compose.yaml, manifests/compose/validation/metal/override.yaml, manifests/compose/validation/metal/prometheus/scrape-configs/metal.yaml
Show if any of the calculations dropped samples.
=> chore(validator): show dropped samples

pkg/model/process_energy.go
Rewrite CreateProcessPowerEstimatorModel() to remove duplicate code.
=> refactor: CreateProcessPowerEstimatorModel()

build/Dockerfile, pkg/config/config.go, pkg/config/types.go, pkg/sensors/accelerator/device/sources/dcgm.go
Fixes: https://github.com/sustainable-computing-io/kepler/issues/1783#issuecomment-2358246908
The `DCGMHostEngineEndpoint` configuration variable accidentally overwritten with an invalid default during one of the code refactors. This patch resets it to an appropriate default
=> fix: error initializing dcgm

e2e/tools/validator/pyproject.toml, e2e/tools/validator/src/validator/cli/__init__.py, e2e/tools/validator/src/validator/prometheus/__init__.py, e2e/tools/validator/src/validator/report/__init__.py, e2e/tools/validator/src/validator/validations/__init__.py, e2e/tools/validator/tests/validator/prometheus/test_prometheus.py
This commit adds MAE to the computation. The validator runs will now include MAE results in the output.
The MSE, MAE and MAPE are now computed using the scikit-learn library
=> feat(validator): incorporate MAE in validations

.github/workflows/daily.yml, .github/workflows/gosec.yml
fix #1865
ref https://github.com/github/codeql-action?tab=readme-ov-file#workflow-permissions
=> [fix]: adjust gosec permissions settings according to GHA ref

.github/workflows/pre-commit-auto-update.yml
Fixup the committer as the `github-actions[bot]` for autoupdates.
=> fix: pre-commit auto update commit author

pkg/collector/energy/node_energy_collector.go, pkg/collector/metric_collector.go
This commit removes wrong use of go routines accessing and updating maps without using mutexes. Even if mutexes are used, one our lock the other from updating maps simultaenously.
=> fix(collector): data race when updating maps simultaenously

pkg/sensors/accelerator/devices/grace_acpi.go
This commit fixes the issue where Kepler was incorrectly identifying the Grace Hopper GPU when no GPU is actually present om the system.
Addresses #1952
=> fix: false detection of Grace Hopper GPU

Dockerfile, Makefile, cmd/kepler/main.go, go.mod
This commit adds the Initial skeleton for Kepler reboot
* Basic main.go file
* Makefile
* Dockerfile
=> feat: add initial skeleton

internal/device/cpu_power_meter.go, internal/device/energy.go, internal/device/energy_test.go, internal/device/power_meter.go
Added package `pkg/internal/device` containing interfaces for energy / power sensor abstractions.
=> chore(devices): Added device interfaces

.github/workflows/codecov-upload.yaml, .github/workflows/pr-checks.yaml, .github/workflows/push.yaml
This commit adds the ability to upload code coverage reports to codecov.io.
=> feat(ci): add codecov upload

internal/version/version_test.go
This commit adds the simple tests for version
=> chore(tests): add tests for version

hack/experiments/ebpf-proc-comparison/README.md, hack/experiments/ebpf-proc-comparison/ebpf-overhead.md
This commit fixes the linting issues in the docs for eBPF-proc-comparison.
=> fix(docs): linting issues

CONTRIBUTING.md
This commit adds a CONTRIBUTING.md file to the repository.
=> feat(docs): add CONTRIBUTING.md with basic guidelines

config/config.go, config/config_test.go
Changes include
- Introduced Host struct with SysFS field in config
- Added host.sysfs flag and validation
- Updated default configuration and tests
=> feat(config): add host sysfs configuration support

compose/dev/grafana/dashboards/dev/dashboard.json
This commit updates the existing dashboard for Kepler. It displays relevant information and reflect reboot changes accurately.
Dashboard:
=> chore(dashboard): enhance Kepler reboot dashboard

MAINTAINERS.md
=> Update Niki Manoledaki details

internal/exporter/prometheus/collector/power_collector.go, internal/exporter/prometheus/collector/power_collector_test.go
- Added "kepler_node_energy_zone" metric to Power Collector
- Added tests.
```
❯ curl -s localhost:28282/metrics | grep energy_zone
kepler_node_energy_zone{index="0",name="core",path="/sys/class/powercap/intel-rapl:0:0"} 1
kepler_node_energy_zone{index="0",name="package",path="/sys/class/powercap/intel-rapl:0"} 1
kepler_node_energy_zone{index="0",name="psys",path="/sys/class/powercap/intel-rapl:1"} 1
kepler_node_energy_zone{index="0",name="uncore",path="/sys/class/powercap/intel-rapl:0:1"} 1
```
=> feat(energy zone): Added energy zone metric to power collector

.github/workflows/profile.yaml
=> DNM: feat(ci): add pprof job

README.md
This commit adds the initial readme file for the kepler reboot
=> docs: add initial readme

Makefile
* Introduce PRODUCTION variable to strip debug symbols for production builds.
* Refactor LDFLAGS to separate version flags and support production optimizations.
* Add BUILD_ARGS for customizable build arguments (such as -cover) in both build and build-debug targets.
* Output debug builds to a distinct -debug binary with race detection.
=> chore(build): add production build support and enhance debug builds

config/config.go, config/config_test.go, internal/server/server.go, internal/server/server_tls_test.go
- Updated flags/config to support passing web config
- api server uses web config to support TLS
- added tests for config
- added tests for tls support
=> feat(server) : Support TLS with web config

hack/config.yaml
This commit adds the TLS related config to the sample configuration file
=> chore: add TLS config to sample config

compose/dev/grafana/dashboards/dev/dashboard.json
This commit updates the existing dashboard to support process-level and container-level metrics.
=> chore(dashboard): add support for process and container-level metrics

internal/resource/informer.go, internal/resource/procfs_reader_test.go
Fixes the comm and exe not getting updated due to these fields initialized only once by 
populating these fields at every interval if these is a notable cpu time usage. 
Change include:
* Introduce `populateProcessFields` to centralize process field updates in `resourceInformer`.
* Skip updates for existing processes with CPU time delta <= 1e-12 to improve performance.
* Refactor `newProcess` to use `popuplateProcess` for consistency.
* Add tests to verify update behavior for negligible CPU time and zero-CPU-time processes.
=> chore: fixes comm and exe not getting updated due to incorrect optimisation

internal/monitor/process.go
This commit adds the monitor update missed by f303cee1.
=> chore(monitor): refresh process fields on each computation

hack/grafana.sh
Use ./hack/grafana.sh to download the dashboard
=> chore(grafana): add grafana dashboard download script

compose/dev/grafana/dashboards/dev/dashboard.json
This commit addresses the review comments for #2112
=> chore(dashboard): update the variable name for zone

.github/workflows/pr-checks.yaml, .pre-commit-config.yaml, config/config.go, config/config_test.go, go.mod, internal/exporter/stdout/stdout.go, internal/exporter/stdout/stdout_test.go, internal/logger/logger_test.go, internal/monitor/monitor_concurrency_test.go
=> chore(go): use golang 1.23

hack/gen-metric-docs/main_test.go
This commit adds the tests for validating the gen-metric-doc tool.
=> test: add coverage for gen-metric-doc tool

Makefile
This commit adds .PHONY declarations near to targets in the Makefile for better readability and clarity.
=> chore: add .PHONY declarations near to targets

.github/workflows/k8s-equinix.yaml
This commit adds a missing check for file change in one of the jobs in the equinix workflow.
=> ci: add missing check for file changes in equinix workflow

config/config.go, config/config_test.go, internal/exporter/prometheus/collector/power_collector.go, internal/k8s/pod/pod.go, internal/k8s/pod/pod_test.go, internal/logger/logger.go, internal/monitor/container.go, internal/monitor/monitor.go, internal/monitor/monitor_collection_test.go, internal/resource/informer.go, internal/resource/mock_procfs_test.go, internal/resource/procfs_reader_test.go, internal/resource/types.go
- Updated tests for pod-power in #2127 
- Fixed review comments in #2127
=> chore(pod): added tests for pod power

cmd/kepler/main.go, docs/metrics/metrics.md, hack/gen-metric-docs/main.go, hack/gen-metric-docs/main_test.go, internal/exporter/prometheus/collector/power_collector.go, internal/exporter/prometheus/collector/power_collector_concurrency_test.go, internal/exporter/prometheus/collector/power_collector_test.go, internal/exporter/prometheus/prometheus.go
-  add node_name label to power metrics
- updated metric docs
=> feat(node): add node_name to power metrics

cmd/kepler/main.go, internal/exporter/prometheus/collector/power_collector_test.go, internal/resource/procfs_reader_test.go
Moved WithNodeName() option from prometheus exporter to collector
added  tests
=> fix(exporter): move WithNodeName option to collector

.gitignore
These files were ignored by .gitignore because of bin/
=> chore: add missing testdata files

.github/ISSUE_TEMPLATE/maintainer_nominate.yaml, GOVERNANCE.md, MAINTAINERS.md, OWNERS
Replace (change base to reboot)
- https://github.com/sustainable-computing-io/kepler/pull/2194
Include the missing change from
- https://github.com/sustainable-computing-io/kepler/pull/2033
=> docs: update governance maintainer

.github/dependabot.yml, .github/workflows/push.yaml, .github/workflows/scorecard.yml
as title, add depend bot and score cord back in CI.
=> [ci]: add depbot, and scorecord back to CI

Makefile
```
❯  make help
Usage: make [target]
Available targets:
Build Targets:
build                Build production binary
build-debug          Build debug binary with race detection
Development & Testing:
clean                Clean build artifacts and coverage files
test                 Test with race detection and coverage
coverage             Coverage report generation (HTML)
lint                 Lint code using golangci-lint
vet                  Vet code using go vet
fmt                  Format code using go fmt
deps                 Dependencies management (tidy and verify)
Docker & Container:
image                Docker image build
push                 Docker image push to registry
Kubernetes & Deployment:
cluster-up           K8s cluster setup for local development
cluster-restart …
```
=> chore: add make help target

docs/configuration/configuration.md
This commit updates the configuration docs to clarify maxTerminated tracking options for disable and unlimited.
=> docs: add disable and unlimited tracking for maxTerminated

MAINTAINERS.md
Self-nominate for a new maintainer role
- https://github.com/sustainable-computing-io/kepler/issues/2258
=> chore: add maintainer role to sunya-ch

README.md
add github star history to README.md
=> chore(README): add github star history

.github/workflows/k8s-bm.yaml
This commit tracks the k8s bm workflow as part of file changes ensures that the workflow is triggered when the workflow file is changed
=> ci: track k8s bm workflow as part of file changes

MAINTAINERS.md
Please refer to https://github.com/sustainable-computing-io/kepler/discussions/2257
cc:
@sthaha 
@vimalk78
@vprashar2929 
@KaiyiLiu1234 
@jiangphcn
@bradmccoydev 
@huoqifeng 
@SamYuan1990 
@yellowhat
=> chore: update maintainers fall 2025 cycle
